/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetAiTranslateLanguages200ResponsePerformanceTypicalResponseTimeMs } from './GetAiTranslateLanguages200ResponsePerformanceTypicalResponseTimeMs';
import {
    GetAiTranslateLanguages200ResponsePerformanceTypicalResponseTimeMsFromJSON,
    GetAiTranslateLanguages200ResponsePerformanceTypicalResponseTimeMsFromJSONTyped,
    GetAiTranslateLanguages200ResponsePerformanceTypicalResponseTimeMsToJSON,
    GetAiTranslateLanguages200ResponsePerformanceTypicalResponseTimeMsToJSONTyped,
} from './GetAiTranslateLanguages200ResponsePerformanceTypicalResponseTimeMs';

/**
 * 
 * @export
 * @interface GetAiTranslateLanguages200ResponsePerformance
 */
export interface GetAiTranslateLanguages200ResponsePerformance {
    /**
     * 
     * @type {boolean}
     * @memberof GetAiTranslateLanguages200ResponsePerformance
     */
    fastModeAvailable?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GetAiTranslateLanguages200ResponsePerformance
     */
    batchTranslationAvailable?: boolean;
    /**
     * 
     * @type {number}
     * @memberof GetAiTranslateLanguages200ResponsePerformance
     */
    maxTextLength?: number;
    /**
     * 
     * @type {number}
     * @memberof GetAiTranslateLanguages200ResponsePerformance
     */
    maxBatchSize?: number;
    /**
     * 
     * @type {GetAiTranslateLanguages200ResponsePerformanceTypicalResponseTimeMs}
     * @memberof GetAiTranslateLanguages200ResponsePerformance
     */
    typicalResponseTimeMs?: GetAiTranslateLanguages200ResponsePerformanceTypicalResponseTimeMs;
}

/**
 * Check if a given object implements the GetAiTranslateLanguages200ResponsePerformance interface.
 */
export function instanceOfGetAiTranslateLanguages200ResponsePerformance(value: object): value is GetAiTranslateLanguages200ResponsePerformance {
    return true;
}

export function GetAiTranslateLanguages200ResponsePerformanceFromJSON(json: any): GetAiTranslateLanguages200ResponsePerformance {
    return GetAiTranslateLanguages200ResponsePerformanceFromJSONTyped(json, false);
}

export function GetAiTranslateLanguages200ResponsePerformanceFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAiTranslateLanguages200ResponsePerformance {
    if (json == null) {
        return json;
    }
    return {
        
        'fastModeAvailable': json['fast_mode_available'] == null ? undefined : json['fast_mode_available'],
        'batchTranslationAvailable': json['batch_translation_available'] == null ? undefined : json['batch_translation_available'],
        'maxTextLength': json['max_text_length'] == null ? undefined : json['max_text_length'],
        'maxBatchSize': json['max_batch_size'] == null ? undefined : json['max_batch_size'],
        'typicalResponseTimeMs': json['typical_response_time_ms'] == null ? undefined : GetAiTranslateLanguages200ResponsePerformanceTypicalResponseTimeMsFromJSON(json['typical_response_time_ms']),
    };
}

export function GetAiTranslateLanguages200ResponsePerformanceToJSON(json: any): GetAiTranslateLanguages200ResponsePerformance {
    return GetAiTranslateLanguages200ResponsePerformanceToJSONTyped(json, false);
}

export function GetAiTranslateLanguages200ResponsePerformanceToJSONTyped(value?: GetAiTranslateLanguages200ResponsePerformance | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fast_mode_available': value['fastModeAvailable'],
        'batch_translation_available': value['batchTranslationAvailable'],
        'max_text_length': value['maxTextLength'],
        'max_batch_size': value['maxBatchSize'],
        'typical_response_time_ms': GetAiTranslateLanguages200ResponsePerformanceTypicalResponseTimeMsToJSON(value['typicalResponseTimeMs']),
    };
}

