/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetAnswerbookAsk500Response
 */
export interface GetAnswerbookAsk500Response {
    /**
     * 
     * @type {number}
     * @memberof GetAnswerbookAsk500Response
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof GetAnswerbookAsk500Response
     */
    message?: string;
}

/**
 * Check if a given object implements the GetAnswerbookAsk500Response interface.
 */
export function instanceOfGetAnswerbookAsk500Response(value: object): value is GetAnswerbookAsk500Response {
    return true;
}

export function GetAnswerbookAsk500ResponseFromJSON(json: any): GetAnswerbookAsk500Response {
    return GetAnswerbookAsk500ResponseFromJSONTyped(json, false);
}

export function GetAnswerbookAsk500ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAnswerbookAsk500Response {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function GetAnswerbookAsk500ResponseToJSON(json: any): GetAnswerbookAsk500Response {
    return GetAnswerbookAsk500ResponseToJSONTyped(json, false);
}

export function GetAnswerbookAsk500ResponseToJSONTyped(value?: GetAnswerbookAsk500Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
    };
}

