/* tslint:disable */
/* eslint-disable */
/**
 * UAPI OpenAPI
 * Generated from UAPI JSON. Code is the interactive documentation: rich descriptions, examples, and x-extensions preserved.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetDictionaryLookup200ResponseEntryPhoneticsUs
 */
export interface GetDictionaryLookup200ResponseEntryPhoneticsUs {
    /**
     * 
     * @type {string}
     * @memberof GetDictionaryLookup200ResponseEntryPhoneticsUs
     */
    audio?: string;
    /**
     * 
     * @type {string}
     * @memberof GetDictionaryLookup200ResponseEntryPhoneticsUs
     */
    text?: string;
}

/**
 * Check if a given object implements the GetDictionaryLookup200ResponseEntryPhoneticsUs interface.
 */
export function instanceOfGetDictionaryLookup200ResponseEntryPhoneticsUs(value: object): value is GetDictionaryLookup200ResponseEntryPhoneticsUs {
    return true;
}

export function GetDictionaryLookup200ResponseEntryPhoneticsUsFromJSON(json: any): GetDictionaryLookup200ResponseEntryPhoneticsUs {
    return GetDictionaryLookup200ResponseEntryPhoneticsUsFromJSONTyped(json, false);
}

export function GetDictionaryLookup200ResponseEntryPhoneticsUsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetDictionaryLookup200ResponseEntryPhoneticsUs {
    if (json == null) {
        return json;
    }
    return {
        
        'audio': json['audio'] == null ? undefined : json['audio'],
        'text': json['text'] == null ? undefined : json['text'],
    };
}

export function GetDictionaryLookup200ResponseEntryPhoneticsUsToJSON(json: any): GetDictionaryLookup200ResponseEntryPhoneticsUs {
    return GetDictionaryLookup200ResponseEntryPhoneticsUsToJSONTyped(json, false);
}

export function GetDictionaryLookup200ResponseEntryPhoneticsUsToJSONTyped(value?: GetDictionaryLookup200ResponseEntryPhoneticsUs | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'audio': value['audio'],
        'text': value['text'],
    };
}

