/* tslint:disable */
/* eslint-disable */
/**
 * UAPI OpenAPI
 * Generated from UAPI JSON. Code is the interactive documentation: rich descriptions, examples, and x-extensions preserved.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetDictionaryLookup200ResponseEntry } from './GetDictionaryLookup200ResponseEntry';
import {
    GetDictionaryLookup200ResponseEntryFromJSON,
    GetDictionaryLookup200ResponseEntryFromJSONTyped,
    GetDictionaryLookup200ResponseEntryToJSON,
    GetDictionaryLookup200ResponseEntryToJSONTyped,
} from './GetDictionaryLookup200ResponseEntry';

/**
 * 
 * @export
 * @interface GetDictionaryLookup200Response
 */
export interface GetDictionaryLookup200Response {
    /**
     * 
     * @type {GetDictionaryLookup200ResponseEntry}
     * @memberof GetDictionaryLookup200Response
     */
    entry?: GetDictionaryLookup200ResponseEntry;
    /**
     * 
     * @type {boolean}
     * @memberof GetDictionaryLookup200Response
     */
    found?: boolean;
}

/**
 * Check if a given object implements the GetDictionaryLookup200Response interface.
 */
export function instanceOfGetDictionaryLookup200Response(value: object): value is GetDictionaryLookup200Response {
    return true;
}

export function GetDictionaryLookup200ResponseFromJSON(json: any): GetDictionaryLookup200Response {
    return GetDictionaryLookup200ResponseFromJSONTyped(json, false);
}

export function GetDictionaryLookup200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetDictionaryLookup200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'entry': json['entry'] == null ? undefined : GetDictionaryLookup200ResponseEntryFromJSON(json['entry']),
        'found': json['found'] == null ? undefined : json['found'],
    };
}

export function GetDictionaryLookup200ResponseToJSON(json: any): GetDictionaryLookup200Response {
    return GetDictionaryLookup200ResponseToJSONTyped(json, false);
}

export function GetDictionaryLookup200ResponseToJSONTyped(value?: GetDictionaryLookup200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'entry': GetDictionaryLookup200ResponseEntryToJSON(value['entry']),
        'found': value['found'],
    };
}

