/* tslint:disable */
/* eslint-disable */
/**
 * UAPI OpenAPI
 * Generated from UAPI JSON. Code is the interactive documentation: rich descriptions, examples, and x-extensions preserved.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetDictionaryLookup200ResponseEntryPhoneticsUs } from './GetDictionaryLookup200ResponseEntryPhoneticsUs';
import {
    GetDictionaryLookup200ResponseEntryPhoneticsUsFromJSON,
    GetDictionaryLookup200ResponseEntryPhoneticsUsFromJSONTyped,
    GetDictionaryLookup200ResponseEntryPhoneticsUsToJSON,
    GetDictionaryLookup200ResponseEntryPhoneticsUsToJSONTyped,
} from './GetDictionaryLookup200ResponseEntryPhoneticsUs';
import type { GetDictionaryLookup200ResponseEntryPhoneticsUk } from './GetDictionaryLookup200ResponseEntryPhoneticsUk';
import {
    GetDictionaryLookup200ResponseEntryPhoneticsUkFromJSON,
    GetDictionaryLookup200ResponseEntryPhoneticsUkFromJSONTyped,
    GetDictionaryLookup200ResponseEntryPhoneticsUkToJSON,
    GetDictionaryLookup200ResponseEntryPhoneticsUkToJSONTyped,
} from './GetDictionaryLookup200ResponseEntryPhoneticsUk';

/**
 * 
 * @export
 * @interface GetDictionaryLookup200ResponseEntryPhonetics
 */
export interface GetDictionaryLookup200ResponseEntryPhonetics {
    /**
     * 
     * @type {GetDictionaryLookup200ResponseEntryPhoneticsUk}
     * @memberof GetDictionaryLookup200ResponseEntryPhonetics
     */
    uk?: GetDictionaryLookup200ResponseEntryPhoneticsUk;
    /**
     * 
     * @type {GetDictionaryLookup200ResponseEntryPhoneticsUs}
     * @memberof GetDictionaryLookup200ResponseEntryPhonetics
     */
    us?: GetDictionaryLookup200ResponseEntryPhoneticsUs;
}

/**
 * Check if a given object implements the GetDictionaryLookup200ResponseEntryPhonetics interface.
 */
export function instanceOfGetDictionaryLookup200ResponseEntryPhonetics(value: object): value is GetDictionaryLookup200ResponseEntryPhonetics {
    return true;
}

export function GetDictionaryLookup200ResponseEntryPhoneticsFromJSON(json: any): GetDictionaryLookup200ResponseEntryPhonetics {
    return GetDictionaryLookup200ResponseEntryPhoneticsFromJSONTyped(json, false);
}

export function GetDictionaryLookup200ResponseEntryPhoneticsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetDictionaryLookup200ResponseEntryPhonetics {
    if (json == null) {
        return json;
    }
    return {
        
        'uk': json['uk'] == null ? undefined : GetDictionaryLookup200ResponseEntryPhoneticsUkFromJSON(json['uk']),
        'us': json['us'] == null ? undefined : GetDictionaryLookup200ResponseEntryPhoneticsUsFromJSON(json['us']),
    };
}

export function GetDictionaryLookup200ResponseEntryPhoneticsToJSON(json: any): GetDictionaryLookup200ResponseEntryPhonetics {
    return GetDictionaryLookup200ResponseEntryPhoneticsToJSONTyped(json, false);
}

export function GetDictionaryLookup200ResponseEntryPhoneticsToJSONTyped(value?: GetDictionaryLookup200ResponseEntryPhonetics | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'uk': GetDictionaryLookup200ResponseEntryPhoneticsUkToJSON(value['uk']),
        'us': GetDictionaryLookup200ResponseEntryPhoneticsUsToJSON(value['us']),
    };
}

