/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetDailyNewsImage500Response
 */
export interface GetDailyNewsImage500Response {
    /**
     * 机器可读的错误代码。
     * @type {string}
     * @memberof GetDailyNewsImage500Response
     */
    code?: string;
    /**
     * 人类可读的错误描述信息。
     * @type {string}
     * @memberof GetDailyNewsImage500Response
     */
    message?: string;
}

/**
 * Check if a given object implements the GetDailyNewsImage500Response interface.
 */
export function instanceOfGetDailyNewsImage500Response(value: object): value is GetDailyNewsImage500Response {
    return true;
}

export function GetDailyNewsImage500ResponseFromJSON(json: any): GetDailyNewsImage500Response {
    return GetDailyNewsImage500ResponseFromJSONTyped(json, false);
}

export function GetDailyNewsImage500ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetDailyNewsImage500Response {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function GetDailyNewsImage500ResponseToJSON(json: any): GetDailyNewsImage500Response {
    return GetDailyNewsImage500ResponseToJSONTyped(json, false);
}

export function GetDailyNewsImage500ResponseToJSONTyped(value?: GetDailyNewsImage500Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
    };
}

