/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetGameMinecraftHistoryid502Response
 */
export interface GetGameMinecraftHistoryid502Response {
    /**
     * 
     * @type {string}
     * @memberof GetGameMinecraftHistoryid502Response
     */
    code?: string;
    /**
     * 
     * @type {object}
     * @memberof GetGameMinecraftHistoryid502Response
     */
    details?: object;
    /**
     * 
     * @type {string}
     * @memberof GetGameMinecraftHistoryid502Response
     */
    message?: string;
}

/**
 * Check if a given object implements the GetGameMinecraftHistoryid502Response interface.
 */
export function instanceOfGetGameMinecraftHistoryid502Response(value: object): value is GetGameMinecraftHistoryid502Response {
    return true;
}

export function GetGameMinecraftHistoryid502ResponseFromJSON(json: any): GetGameMinecraftHistoryid502Response {
    return GetGameMinecraftHistoryid502ResponseFromJSONTyped(json, false);
}

export function GetGameMinecraftHistoryid502ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetGameMinecraftHistoryid502Response {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'details': json['details'] == null ? undefined : json['details'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function GetGameMinecraftHistoryid502ResponseToJSON(json: any): GetGameMinecraftHistoryid502Response {
    return GetGameMinecraftHistoryid502ResponseToJSONTyped(json, false);
}

export function GetGameMinecraftHistoryid502ResponseToJSONTyped(value?: GetGameMinecraftHistoryid502Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'details': value['details'],
        'message': value['message'],
    };
}

