/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetGithubUser400ResponseOneOf1
 */
export interface GetGithubUser400ResponseOneOf1 {
    /**
     * 错误码。
     * @type {string}
     * @memberof GetGithubUser400ResponseOneOf1
     */
    code?: string;
    /**
     * 错误原因说明。
     * @type {string}
     * @memberof GetGithubUser400ResponseOneOf1
     */
    error?: string;
}

/**
 * Check if a given object implements the GetGithubUser400ResponseOneOf1 interface.
 */
export function instanceOfGetGithubUser400ResponseOneOf1(value: object): value is GetGithubUser400ResponseOneOf1 {
    return true;
}

export function GetGithubUser400ResponseOneOf1FromJSON(json: any): GetGithubUser400ResponseOneOf1 {
    return GetGithubUser400ResponseOneOf1FromJSONTyped(json, false);
}

export function GetGithubUser400ResponseOneOf1FromJSONTyped(json: any, ignoreDiscriminator: boolean): GetGithubUser400ResponseOneOf1 {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function GetGithubUser400ResponseOneOf1ToJSON(json: any): GetGithubUser400ResponseOneOf1 {
    return GetGithubUser400ResponseOneOf1ToJSONTyped(json, false);
}

export function GetGithubUser400ResponseOneOf1ToJSONTyped(value?: GetGithubUser400ResponseOneOf1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'error': value['error'],
    };
}

