/* tslint:disable */
/* eslint-disable */
/**
 * UAPI OpenAPI
 * Generated from UAPI JSON. Code is the interactive documentation: rich descriptions, examples, and x-extensions preserved.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetGameSteamServers200ResponseServersInner } from './GetGameSteamServers200ResponseServersInner';
import {
    GetGameSteamServers200ResponseServersInnerFromJSON,
    GetGameSteamServers200ResponseServersInnerFromJSONTyped,
    GetGameSteamServers200ResponseServersInnerToJSON,
    GetGameSteamServers200ResponseServersInnerToJSONTyped,
} from './GetGameSteamServers200ResponseServersInner';

/**
 * 
 * @export
 * @interface GetGameSteamServers200Response
 */
export interface GetGameSteamServers200Response {
    /**
     * 
     * @type {number}
     * @memberof GetGameSteamServers200Response
     */
    appid?: number;
    /**
     * 
     * @type {number}
     * @memberof GetGameSteamServers200Response
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof GetGameSteamServers200Response
     */
    query?: string;
    /**
     * 
     * @type {Array<GetGameSteamServers200ResponseServersInner>}
     * @memberof GetGameSteamServers200Response
     */
    servers?: Array<GetGameSteamServers200ResponseServersInner>;
}

/**
 * Check if a given object implements the GetGameSteamServers200Response interface.
 */
export function instanceOfGetGameSteamServers200Response(value: object): value is GetGameSteamServers200Response {
    return true;
}

export function GetGameSteamServers200ResponseFromJSON(json: any): GetGameSteamServers200Response {
    return GetGameSteamServers200ResponseFromJSONTyped(json, false);
}

export function GetGameSteamServers200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetGameSteamServers200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'appid': json['appid'] == null ? undefined : json['appid'],
        'count': json['count'] == null ? undefined : json['count'],
        'query': json['query'] == null ? undefined : json['query'],
        'servers': json['servers'] == null ? undefined : ((json['servers'] as Array<any>).map(GetGameSteamServers200ResponseServersInnerFromJSON)),
    };
}

export function GetGameSteamServers200ResponseToJSON(json: any): GetGameSteamServers200Response {
    return GetGameSteamServers200ResponseToJSONTyped(json, false);
}

export function GetGameSteamServers200ResponseToJSONTyped(value?: GetGameSteamServers200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'appid': value['appid'],
        'count': value['count'],
        'query': value['query'],
        'servers': value['servers'] == null ? undefined : ((value['servers'] as Array<any>).map(GetGameSteamServers200ResponseServersInnerToJSON)),
    };
}

