/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetGameMinecraftUserinfo200Response
 */
export interface GetGameMinecraftUserinfo200Response {
    /**
     * 玩家当前使用的皮肤图片URL。
     * @type {string}
     * @memberof GetGameMinecraftUserinfo200Response
     */
    skinUrl?: string;
    /**
     * 玩家当前的准确用户名（注意大小写可能与输入不同）。
     * @type {string}
     * @memberof GetGameMinecraftUserinfo200Response
     */
    username?: string;
    /**
     * 玩家的32位无破折号UUID。
     * @type {string}
     * @memberof GetGameMinecraftUserinfo200Response
     */
    uuid?: string;
}

/**
 * Check if a given object implements the GetGameMinecraftUserinfo200Response interface.
 */
export function instanceOfGetGameMinecraftUserinfo200Response(value: object): value is GetGameMinecraftUserinfo200Response {
    return true;
}

export function GetGameMinecraftUserinfo200ResponseFromJSON(json: any): GetGameMinecraftUserinfo200Response {
    return GetGameMinecraftUserinfo200ResponseFromJSONTyped(json, false);
}

export function GetGameMinecraftUserinfo200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetGameMinecraftUserinfo200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'skinUrl': json['skin_url'] == null ? undefined : json['skin_url'],
        'username': json['username'] == null ? undefined : json['username'],
        'uuid': json['uuid'] == null ? undefined : json['uuid'],
    };
}

export function GetGameMinecraftUserinfo200ResponseToJSON(json: any): GetGameMinecraftUserinfo200Response {
    return GetGameMinecraftUserinfo200ResponseToJSONTyped(json, false);
}

export function GetGameMinecraftUserinfo200ResponseToJSONTyped(value?: GetGameMinecraftUserinfo200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'skin_url': value['skinUrl'],
        'username': value['username'],
        'uuid': value['uuid'],
    };
}

