/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetGameMinecraftServerstatus200ResponseOnlinePlayersInner
 */
export interface GetGameMinecraftServerstatus200ResponseOnlinePlayersInner {
    /**
     * 玩家名称。
     * @type {string}
     * @memberof GetGameMinecraftServerstatus200ResponseOnlinePlayersInner
     */
    name?: string;
    /**
     * 玩家的 UUID。部分服务器可能不返回这个字段。
     * @type {string}
     * @memberof GetGameMinecraftServerstatus200ResponseOnlinePlayersInner
     */
    uuid?: string;
}

/**
 * Check if a given object implements the GetGameMinecraftServerstatus200ResponseOnlinePlayersInner interface.
 */
export function instanceOfGetGameMinecraftServerstatus200ResponseOnlinePlayersInner(value: object): value is GetGameMinecraftServerstatus200ResponseOnlinePlayersInner {
    return true;
}

export function GetGameMinecraftServerstatus200ResponseOnlinePlayersInnerFromJSON(json: any): GetGameMinecraftServerstatus200ResponseOnlinePlayersInner {
    return GetGameMinecraftServerstatus200ResponseOnlinePlayersInnerFromJSONTyped(json, false);
}

export function GetGameMinecraftServerstatus200ResponseOnlinePlayersInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetGameMinecraftServerstatus200ResponseOnlinePlayersInner {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'uuid': json['uuid'] == null ? undefined : json['uuid'],
    };
}

export function GetGameMinecraftServerstatus200ResponseOnlinePlayersInnerToJSON(json: any): GetGameMinecraftServerstatus200ResponseOnlinePlayersInner {
    return GetGameMinecraftServerstatus200ResponseOnlinePlayersInnerToJSONTyped(json, false);
}

export function GetGameMinecraftServerstatus200ResponseOnlinePlayersInnerToJSONTyped(value?: GetGameMinecraftServerstatus200ResponseOnlinePlayersInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'uuid': value['uuid'],
    };
}

