/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetGameSteamSummary404Response
 */
export interface GetGameSteamSummary404Response {
    /**
     * 
     * @type {string}
     * @memberof GetGameSteamSummary404Response
     */
    code?: string;
    /**
     * 
     * @type {object}
     * @memberof GetGameSteamSummary404Response
     */
    details?: object;
    /**
     * 
     * @type {string}
     * @memberof GetGameSteamSummary404Response
     */
    message?: string;
}

/**
 * Check if a given object implements the GetGameSteamSummary404Response interface.
 */
export function instanceOfGetGameSteamSummary404Response(value: object): value is GetGameSteamSummary404Response {
    return true;
}

export function GetGameSteamSummary404ResponseFromJSON(json: any): GetGameSteamSummary404Response {
    return GetGameSteamSummary404ResponseFromJSONTyped(json, false);
}

export function GetGameSteamSummary404ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetGameSteamSummary404Response {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'details': json['details'] == null ? undefined : json['details'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function GetGameSteamSummary404ResponseToJSON(json: any): GetGameSteamSummary404Response {
    return GetGameSteamSummary404ResponseToJSONTyped(json, false);
}

export function GetGameSteamSummary404ResponseToJSONTyped(value?: GetGameSteamSummary404Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'details': value['details'],
        'message': value['message'],
    };
}

