/* tslint:disable */
/* eslint-disable */
/**
 * UAPI OpenAPI
 * Generated from UAPI JSON. Code is the interactive documentation: rich descriptions, examples, and x-extensions preserved.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 仓库最新发布版本信息，如果没有 Release 则为 null。可用于实现应用更新检查功能。
 * @export
 * @interface GetGithubRepo200ResponseLatestRelease
 */
export interface GetGithubRepo200ResponseLatestRelease {
    /**
     * 是否为草稿
     * @type {boolean}
     * @memberof GetGithubRepo200ResponseLatestRelease
     */
    draft?: boolean;
    /**
     * Release 页面链接
     * @type {string}
     * @memberof GetGithubRepo200ResponseLatestRelease
     */
    htmlUrl?: string;
    /**
     * 发布名称
     * @type {string}
     * @memberof GetGithubRepo200ResponseLatestRelease
     */
    name?: string;
    /**
     * 是否为预发布版本
     * @type {boolean}
     * @memberof GetGithubRepo200ResponseLatestRelease
     */
    prerelease?: boolean;
    /**
     * 发布时间
     * @type {Date}
     * @memberof GetGithubRepo200ResponseLatestRelease
     */
    publishedAt?: Date;
    /**
     * 版本标签
     * @type {string}
     * @memberof GetGithubRepo200ResponseLatestRelease
     */
    tagName?: string;
}

/**
 * Check if a given object implements the GetGithubRepo200ResponseLatestRelease interface.
 */
export function instanceOfGetGithubRepo200ResponseLatestRelease(value: object): value is GetGithubRepo200ResponseLatestRelease {
    return true;
}

export function GetGithubRepo200ResponseLatestReleaseFromJSON(json: any): GetGithubRepo200ResponseLatestRelease {
    return GetGithubRepo200ResponseLatestReleaseFromJSONTyped(json, false);
}

export function GetGithubRepo200ResponseLatestReleaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetGithubRepo200ResponseLatestRelease {
    if (json == null) {
        return json;
    }
    return {
        
        'draft': json['draft'] == null ? undefined : json['draft'],
        'htmlUrl': json['html_url'] == null ? undefined : json['html_url'],
        'name': json['name'] == null ? undefined : json['name'],
        'prerelease': json['prerelease'] == null ? undefined : json['prerelease'],
        'publishedAt': json['published_at'] == null ? undefined : (new Date(json['published_at'])),
        'tagName': json['tag_name'] == null ? undefined : json['tag_name'],
    };
}

export function GetGithubRepo200ResponseLatestReleaseToJSON(json: any): GetGithubRepo200ResponseLatestRelease {
    return GetGithubRepo200ResponseLatestReleaseToJSONTyped(json, false);
}

export function GetGithubRepo200ResponseLatestReleaseToJSONTyped(value?: GetGithubRepo200ResponseLatestRelease | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'draft': value['draft'],
        'html_url': value['htmlUrl'],
        'name': value['name'],
        'prerelease': value['prerelease'],
        'published_at': value['publishedAt'] == null ? value['publishedAt'] : value['publishedAt'].toISOString(),
        'tag_name': value['tagName'],
    };
}

