/* tslint:disable */
/* eslint-disable */
/**
 * UAPI OpenAPI
 * Generated from UAPI JSON. Code is the interactive documentation: rich descriptions, examples, and x-extensions preserved.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetGithubUser200ResponseActivityContributionCalendarWeeksInnerContributionDaysInner
 */
export interface GetGithubUser200ResponseActivityContributionCalendarWeeksInnerContributionDaysInner {
    /**
     * 当天贡献等级对应的颜色值。
     * @type {string}
     * @memberof GetGithubUser200ResponseActivityContributionCalendarWeeksInnerContributionDaysInner
     */
    color?: string;
    /**
     * 当天的贡献次数。
     * @type {number}
     * @memberof GetGithubUser200ResponseActivityContributionCalendarWeeksInnerContributionDaysInner
     */
    contributionCount?: number;
    /**
     * 当天日期。
     * @type {string}
     * @memberof GetGithubUser200ResponseActivityContributionCalendarWeeksInnerContributionDaysInner
     */
    date?: string;
    /**
     * 星期索引，0 表示周日，6 表示周六。
     * @type {number}
     * @memberof GetGithubUser200ResponseActivityContributionCalendarWeeksInnerContributionDaysInner
     */
    weekday?: number;
}

/**
 * Check if a given object implements the GetGithubUser200ResponseActivityContributionCalendarWeeksInnerContributionDaysInner interface.
 */
export function instanceOfGetGithubUser200ResponseActivityContributionCalendarWeeksInnerContributionDaysInner(value: object): value is GetGithubUser200ResponseActivityContributionCalendarWeeksInnerContributionDaysInner {
    return true;
}

export function GetGithubUser200ResponseActivityContributionCalendarWeeksInnerContributionDaysInnerFromJSON(json: any): GetGithubUser200ResponseActivityContributionCalendarWeeksInnerContributionDaysInner {
    return GetGithubUser200ResponseActivityContributionCalendarWeeksInnerContributionDaysInnerFromJSONTyped(json, false);
}

export function GetGithubUser200ResponseActivityContributionCalendarWeeksInnerContributionDaysInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetGithubUser200ResponseActivityContributionCalendarWeeksInnerContributionDaysInner {
    if (json == null) {
        return json;
    }
    return {
        
        'color': json['color'] == null ? undefined : json['color'],
        'contributionCount': json['contribution_count'] == null ? undefined : json['contribution_count'],
        'date': json['date'] == null ? undefined : json['date'],
        'weekday': json['weekday'] == null ? undefined : json['weekday'],
    };
}

export function GetGithubUser200ResponseActivityContributionCalendarWeeksInnerContributionDaysInnerToJSON(json: any): GetGithubUser200ResponseActivityContributionCalendarWeeksInnerContributionDaysInner {
    return GetGithubUser200ResponseActivityContributionCalendarWeeksInnerContributionDaysInnerToJSONTyped(json, false);
}

export function GetGithubUser200ResponseActivityContributionCalendarWeeksInnerContributionDaysInnerToJSONTyped(value?: GetGithubUser200ResponseActivityContributionCalendarWeeksInnerContributionDaysInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'color': value['color'],
        'contribution_count': value['contributionCount'],
        'date': value['date'],
        'weekday': value['weekday'],
    };
}

