/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetGameMinecraftServerstatus200ResponseOnlinePlayersInner } from './GetGameMinecraftServerstatus200ResponseOnlinePlayersInner';
import {
    GetGameMinecraftServerstatus200ResponseOnlinePlayersInnerFromJSON,
    GetGameMinecraftServerstatus200ResponseOnlinePlayersInnerFromJSONTyped,
    GetGameMinecraftServerstatus200ResponseOnlinePlayersInnerToJSON,
    GetGameMinecraftServerstatus200ResponseOnlinePlayersInnerToJSONTyped,
} from './GetGameMinecraftServerstatus200ResponseOnlinePlayersInner';

/**
 * 
 * @export
 * @interface GetGameMinecraftServerstatus200Response
 */
export interface GetGameMinecraftServerstatus200Response {
    /**
     * 服务器图标的 Base64 Data URI。你可以直接在 `<img>` 标签的 `src` 属性中使用它。
     * @type {string}
     * @memberof GetGameMinecraftServerstatus200Response
     */
    faviconUrl?: string;
    /**
     * 服务器解析后的IP地址。
     * @type {string}
     * @memberof GetGameMinecraftServerstatus200Response
     */
    ip?: string;
    /**
     * 服务器配置的最大玩家容量。
     * @type {number}
     * @memberof GetGameMinecraftServerstatus200Response
     */
    maxPlayers?: number;
    /**
     * 纯文本格式的服务器MOTD（每日消息），去除了所有颜色和格式代码。
     * @type {string}
     * @memberof GetGameMinecraftServerstatus200Response
     */
    motdClean?: string;
    /**
     * HTML格式的服务器MOTD，保留了颜色和样式，方便你在网页上直接渲染。
     * @type {string}
     * @memberof GetGameMinecraftServerstatus200Response
     */
    motdHtml?: string;
    /**
     * 服务器当前是否在线。
     * @type {boolean}
     * @memberof GetGameMinecraftServerstatus200Response
     */
    online?: boolean;
    /**
     * 当前在线玩家列表。如果服务器没有返回这个字段，它会省略。部分服务器返回的列表可能不完整。
     * @type {Array<GetGameMinecraftServerstatus200ResponseOnlinePlayersInner>}
     * @memberof GetGameMinecraftServerstatus200Response
     */
    onlinePlayers?: Array<GetGameMinecraftServerstatus200ResponseOnlinePlayersInner>;
    /**
     * 当前在线的玩家数量。
     * @type {number}
     * @memberof GetGameMinecraftServerstatus200Response
     */
    players?: number;
    /**
     * 服务器使用的端口。
     * @type {number}
     * @memberof GetGameMinecraftServerstatus200Response
     */
    port?: number;
    /**
     * 服务器报告的版本信息。
     * @type {string}
     * @memberof GetGameMinecraftServerstatus200Response
     */
    version?: string;
}

/**
 * Check if a given object implements the GetGameMinecraftServerstatus200Response interface.
 */
export function instanceOfGetGameMinecraftServerstatus200Response(value: object): value is GetGameMinecraftServerstatus200Response {
    return true;
}

export function GetGameMinecraftServerstatus200ResponseFromJSON(json: any): GetGameMinecraftServerstatus200Response {
    return GetGameMinecraftServerstatus200ResponseFromJSONTyped(json, false);
}

export function GetGameMinecraftServerstatus200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetGameMinecraftServerstatus200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'faviconUrl': json['favicon_url'] == null ? undefined : json['favicon_url'],
        'ip': json['ip'] == null ? undefined : json['ip'],
        'maxPlayers': json['max_players'] == null ? undefined : json['max_players'],
        'motdClean': json['motd_clean'] == null ? undefined : json['motd_clean'],
        'motdHtml': json['motd_html'] == null ? undefined : json['motd_html'],
        'online': json['online'] == null ? undefined : json['online'],
        'onlinePlayers': json['online_players'] == null ? undefined : ((json['online_players'] as Array<any>).map(GetGameMinecraftServerstatus200ResponseOnlinePlayersInnerFromJSON)),
        'players': json['players'] == null ? undefined : json['players'],
        'port': json['port'] == null ? undefined : json['port'],
        'version': json['version'] == null ? undefined : json['version'],
    };
}

export function GetGameMinecraftServerstatus200ResponseToJSON(json: any): GetGameMinecraftServerstatus200Response {
    return GetGameMinecraftServerstatus200ResponseToJSONTyped(json, false);
}

export function GetGameMinecraftServerstatus200ResponseToJSONTyped(value?: GetGameMinecraftServerstatus200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'favicon_url': value['faviconUrl'],
        'ip': value['ip'],
        'max_players': value['maxPlayers'],
        'motd_clean': value['motdClean'],
        'motd_html': value['motdHtml'],
        'online': value['online'],
        'online_players': value['onlinePlayers'] == null ? undefined : ((value['onlinePlayers'] as Array<any>).map(GetGameMinecraftServerstatus200ResponseOnlinePlayersInnerToJSON)),
        'players': value['players'],
        'port': value['port'],
        'version': value['version'],
    };
}

