/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetGithubUser200ResponseActivity } from './GetGithubUser200ResponseActivity';
import {
    GetGithubUser200ResponseActivityFromJSON,
    GetGithubUser200ResponseActivityFromJSONTyped,
    GetGithubUser200ResponseActivityToJSON,
    GetGithubUser200ResponseActivityToJSONTyped,
} from './GetGithubUser200ResponseActivity';
import type { GetGithubUser200ResponseOrganizationsInner } from './GetGithubUser200ResponseOrganizationsInner';
import {
    GetGithubUser200ResponseOrganizationsInnerFromJSON,
    GetGithubUser200ResponseOrganizationsInnerFromJSONTyped,
    GetGithubUser200ResponseOrganizationsInnerToJSON,
    GetGithubUser200ResponseOrganizationsInnerToJSONTyped,
} from './GetGithubUser200ResponseOrganizationsInner';

/**
 * 
 * @export
 * @interface GetGithubUser200Response
 */
export interface GetGithubUser200Response {
    /**
     * GitHub 登录名。
     * @type {string}
     * @memberof GetGithubUser200Response
     */
    login?: string;
    /**
     * 用户公开显示的名称。
     * @type {string}
     * @memberof GetGithubUser200Response
     */
    name?: string;
    /**
     * 用户个人简介。
     * @type {string}
     * @memberof GetGithubUser200Response
     */
    bio?: string;
    /**
     * 用户填写的公司或组织信息。
     * @type {string}
     * @memberof GetGithubUser200Response
     */
    company?: string;
    /**
     * 用户公开展示的地理位置。
     * @type {string}
     * @memberof GetGithubUser200Response
     */
    location?: string;
    /**
     * 用户填写的网站或博客地址。
     * @type {string}
     * @memberof GetGithubUser200Response
     */
    blog?: string;
    /**
     * 用户绑定的 X（Twitter）用户名。
     * @type {string}
     * @memberof GetGithubUser200Response
     */
    twitterUsername?: string;
    /**
     * 用户公开可见的邮箱地址。
     * @type {string}
     * @memberof GetGithubUser200Response
     */
    email?: string;
    /**
     * GitHub 个人主页链接。
     * @type {string}
     * @memberof GetGithubUser200Response
     */
    htmlUrl?: string;
    /**
     * 用户头像图片链接。
     * @type {string}
     * @memberof GetGithubUser200Response
     */
    avatarUrl?: string;
    /**
     * 账号类型，常见值为 User 或 Organization。
     * @type {string}
     * @memberof GetGithubUser200Response
     */
    type?: string;
    /**
     * 公开仓库数量。
     * @type {number}
     * @memberof GetGithubUser200Response
     */
    publicRepos?: number;
    /**
     * 公开 Gist 数量。
     * @type {number}
     * @memberof GetGithubUser200Response
     */
    publicGists?: number;
    /**
     * 关注该用户的人数。
     * @type {number}
     * @memberof GetGithubUser200Response
     */
    followers?: number;
    /**
     * 该用户正在关注的人数。
     * @type {number}
     * @memberof GetGithubUser200Response
     */
    following?: number;
    /**
     * GitHub 账号创建时间（ISO 8601）。
     * @type {Date}
     * @memberof GetGithubUser200Response
     */
    createdAt?: Date;
    /**
     * 用户资料最近更新时间（ISO 8601）。
     * @type {Date}
     * @memberof GetGithubUser200Response
     */
    updatedAt?: Date;
    /**
     * 用户公开加入的组织列表
     * @type {Array<GetGithubUser200ResponseOrganizationsInner>}
     * @memberof GetGithubUser200Response
     */
    organizations?: Array<GetGithubUser200ResponseOrganizationsInner>;
    /**
     * 
     * @type {GetGithubUser200ResponseActivity}
     * @memberof GetGithubUser200Response
     */
    activity?: GetGithubUser200ResponseActivity;
}

/**
 * Check if a given object implements the GetGithubUser200Response interface.
 */
export function instanceOfGetGithubUser200Response(value: object): value is GetGithubUser200Response {
    return true;
}

export function GetGithubUser200ResponseFromJSON(json: any): GetGithubUser200Response {
    return GetGithubUser200ResponseFromJSONTyped(json, false);
}

export function GetGithubUser200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetGithubUser200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'login': json['login'] == null ? undefined : json['login'],
        'name': json['name'] == null ? undefined : json['name'],
        'bio': json['bio'] == null ? undefined : json['bio'],
        'company': json['company'] == null ? undefined : json['company'],
        'location': json['location'] == null ? undefined : json['location'],
        'blog': json['blog'] == null ? undefined : json['blog'],
        'twitterUsername': json['twitter_username'] == null ? undefined : json['twitter_username'],
        'email': json['email'] == null ? undefined : json['email'],
        'htmlUrl': json['html_url'] == null ? undefined : json['html_url'],
        'avatarUrl': json['avatar_url'] == null ? undefined : json['avatar_url'],
        'type': json['type'] == null ? undefined : json['type'],
        'publicRepos': json['public_repos'] == null ? undefined : json['public_repos'],
        'publicGists': json['public_gists'] == null ? undefined : json['public_gists'],
        'followers': json['followers'] == null ? undefined : json['followers'],
        'following': json['following'] == null ? undefined : json['following'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'organizations': json['organizations'] == null ? undefined : ((json['organizations'] as Array<any>).map(GetGithubUser200ResponseOrganizationsInnerFromJSON)),
        'activity': json['activity'] == null ? undefined : GetGithubUser200ResponseActivityFromJSON(json['activity']),
    };
}

export function GetGithubUser200ResponseToJSON(json: any): GetGithubUser200Response {
    return GetGithubUser200ResponseToJSONTyped(json, false);
}

export function GetGithubUser200ResponseToJSONTyped(value?: GetGithubUser200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'login': value['login'],
        'name': value['name'],
        'bio': value['bio'],
        'company': value['company'],
        'location': value['location'],
        'blog': value['blog'],
        'twitter_username': value['twitterUsername'],
        'email': value['email'],
        'html_url': value['htmlUrl'],
        'avatar_url': value['avatarUrl'],
        'type': value['type'],
        'public_repos': value['publicRepos'],
        'public_gists': value['publicGists'],
        'followers': value['followers'],
        'following': value['following'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
        'organizations': value['organizations'] == null ? undefined : ((value['organizations'] as Array<any>).map(GetGithubUser200ResponseOrganizationsInnerToJSON)),
        'activity': GetGithubUser200ResponseActivityToJSON(value['activity']),
    };
}

