/* tslint:disable */
/* eslint-disable */
/**
 * UAPI OpenAPI
 * Generated from UAPI JSON. Code is the interactive documentation: rich descriptions, examples, and x-extensions preserved.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetGameMinecraftVersion503Response
 */
export interface GetGameMinecraftVersion503Response {
    /**
     * 
     * @type {string}
     * @memberof GetGameMinecraftVersion503Response
     */
    error?: string;
}

/**
 * Check if a given object implements the GetGameMinecraftVersion503Response interface.
 */
export function instanceOfGetGameMinecraftVersion503Response(value: object): value is GetGameMinecraftVersion503Response {
    return true;
}

export function GetGameMinecraftVersion503ResponseFromJSON(json: any): GetGameMinecraftVersion503Response {
    return GetGameMinecraftVersion503ResponseFromJSONTyped(json, false);
}

export function GetGameMinecraftVersion503ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetGameMinecraftVersion503Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function GetGameMinecraftVersion503ResponseToJSON(json: any): GetGameMinecraftVersion503Response {
    return GetGameMinecraftVersion503ResponseToJSONTyped(json, false);
}

export function GetGameMinecraftVersion503ResponseToJSONTyped(value?: GetGameMinecraftVersion503Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
    };
}

