/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetHistoryProgrammerToday500Response
 */
export interface GetHistoryProgrammerToday500Response {
    /**
     * 
     * @type {string}
     * @memberof GetHistoryProgrammerToday500Response
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof GetHistoryProgrammerToday500Response
     */
    message?: string;
}

/**
 * Check if a given object implements the GetHistoryProgrammerToday500Response interface.
 */
export function instanceOfGetHistoryProgrammerToday500Response(value: object): value is GetHistoryProgrammerToday500Response {
    return true;
}

export function GetHistoryProgrammerToday500ResponseFromJSON(json: any): GetHistoryProgrammerToday500Response {
    return GetHistoryProgrammerToday500ResponseFromJSONTyped(json, false);
}

export function GetHistoryProgrammerToday500ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetHistoryProgrammerToday500Response {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function GetHistoryProgrammerToday500ResponseToJSON(json: any): GetHistoryProgrammerToday500Response {
    return GetHistoryProgrammerToday500ResponseToJSONTyped(json, false);
}

export function GetHistoryProgrammerToday500ResponseToJSONTyped(value?: GetHistoryProgrammerToday500Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
    };
}

