/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FormatJsonTrivia } from './FormatJsonTrivia';
import {
    FormatJsonTriviaFromJSON,
    FormatJsonTriviaFromJSONTyped,
    FormatJsonTriviaToJSON,
    FormatJsonTriviaToJSONTyped,
} from './FormatJsonTrivia';

/**
 * 
 * @export
 * @interface GetImageBingDailyHistory200ResponseItemsInner
 */
export interface GetImageBingDailyHistory200ResponseItemsInner {
    /**
     * 
     * @type {string}
     * @memberof GetImageBingDailyHistory200ResponseItemsInner
     */
    date?: string;
    /**
     * 
     * @type {string}
     * @memberof GetImageBingDailyHistory200ResponseItemsInner
     */
    market?: string;
    /**
     * 
     * @type {string}
     * @memberof GetImageBingDailyHistory200ResponseItemsInner
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof GetImageBingDailyHistory200ResponseItemsInner
     */
    subtitle?: string;
    /**
     * 
     * @type {string}
     * @memberof GetImageBingDailyHistory200ResponseItemsInner
     */
    headline?: string;
    /**
     * 
     * @type {string}
     * @memberof GetImageBingDailyHistory200ResponseItemsInner
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof GetImageBingDailyHistory200ResponseItemsInner
     */
    copyright?: string;
    /**
     * 
     * @type {string}
     * @memberof GetImageBingDailyHistory200ResponseItemsInner
     */
    copyrightLink?: string;
    /**
     * 
     * @type {string}
     * @memberof GetImageBingDailyHistory200ResponseItemsInner
     */
    quizId?: string;
    /**
     * 
     * @type {FormatJsonTrivia}
     * @memberof GetImageBingDailyHistory200ResponseItemsInner
     */
    trivia?: FormatJsonTrivia;
    /**
     * 
     * @type {string}
     * @memberof GetImageBingDailyHistory200ResponseItemsInner
     */
    resolution?: string;
    /**
     * 
     * @type {string}
     * @memberof GetImageBingDailyHistory200ResponseItemsInner
     */
    imageUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof GetImageBingDailyHistory200ResponseItemsInner
     */
    imageUrl4k?: string;
    /**
     * 
     * @type {string}
     * @memberof GetImageBingDailyHistory200ResponseItemsInner
     */
    imageUrl1080?: string;
    /**
     * 
     * @type {string}
     * @memberof GetImageBingDailyHistory200ResponseItemsInner
     */
    fetchedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof GetImageBingDailyHistory200ResponseItemsInner
     */
    updatedAt?: string;
}

/**
 * Check if a given object implements the GetImageBingDailyHistory200ResponseItemsInner interface.
 */
export function instanceOfGetImageBingDailyHistory200ResponseItemsInner(value: object): value is GetImageBingDailyHistory200ResponseItemsInner {
    return true;
}

export function GetImageBingDailyHistory200ResponseItemsInnerFromJSON(json: any): GetImageBingDailyHistory200ResponseItemsInner {
    return GetImageBingDailyHistory200ResponseItemsInnerFromJSONTyped(json, false);
}

export function GetImageBingDailyHistory200ResponseItemsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetImageBingDailyHistory200ResponseItemsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'date': json['date'] == null ? undefined : json['date'],
        'market': json['market'] == null ? undefined : json['market'],
        'title': json['title'] == null ? undefined : json['title'],
        'subtitle': json['subtitle'] == null ? undefined : json['subtitle'],
        'headline': json['headline'] == null ? undefined : json['headline'],
        'description': json['description'] == null ? undefined : json['description'],
        'copyright': json['copyright'] == null ? undefined : json['copyright'],
        'copyrightLink': json['copyright_link'] == null ? undefined : json['copyright_link'],
        'quizId': json['quiz_id'] == null ? undefined : json['quiz_id'],
        'trivia': json['trivia'] == null ? undefined : FormatJsonTriviaFromJSON(json['trivia']),
        'resolution': json['resolution'] == null ? undefined : json['resolution'],
        'imageUrl': json['image_url'] == null ? undefined : json['image_url'],
        'imageUrl4k': json['image_url_4k'] == null ? undefined : json['image_url_4k'],
        'imageUrl1080': json['image_url_1080'] == null ? undefined : json['image_url_1080'],
        'fetchedAt': json['fetched_at'] == null ? undefined : json['fetched_at'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
    };
}

export function GetImageBingDailyHistory200ResponseItemsInnerToJSON(json: any): GetImageBingDailyHistory200ResponseItemsInner {
    return GetImageBingDailyHistory200ResponseItemsInnerToJSONTyped(json, false);
}

export function GetImageBingDailyHistory200ResponseItemsInnerToJSONTyped(value?: GetImageBingDailyHistory200ResponseItemsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date': value['date'],
        'market': value['market'],
        'title': value['title'],
        'subtitle': value['subtitle'],
        'headline': value['headline'],
        'description': value['description'],
        'copyright': value['copyright'],
        'copyright_link': value['copyrightLink'],
        'quiz_id': value['quizId'],
        'trivia': FormatJsonTriviaToJSON(value['trivia']),
        'resolution': value['resolution'],
        'image_url': value['imageUrl'],
        'image_url_4k': value['imageUrl4k'],
        'image_url_1080': value['imageUrl1080'],
        'fetched_at': value['fetchedAt'],
        'updated_at': value['updatedAt'],
    };
}

