/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetImageMotou500Response
 */
export interface GetImageMotou500Response {
    /**
     * 
     * @type {string}
     * @memberof GetImageMotou500Response
     */
    error?: string;
}

/**
 * Check if a given object implements the GetImageMotou500Response interface.
 */
export function instanceOfGetImageMotou500Response(value: object): value is GetImageMotou500Response {
    return true;
}

export function GetImageMotou500ResponseFromJSON(json: any): GetImageMotou500Response {
    return GetImageMotou500ResponseFromJSONTyped(json, false);
}

export function GetImageMotou500ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetImageMotou500Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function GetImageMotou500ResponseToJSON(json: any): GetImageMotou500Response {
    return GetImageMotou500ResponseToJSONTyped(json, false);
}

export function GetImageMotou500ResponseToJSONTyped(value?: GetImageMotou500Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
    };
}

