/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetMiscRandomnumber200Response
 */
export interface GetMiscRandomnumber200Response {
    /**
     * 生成的随机数列表。
     * @type {Array<number>}
     * @memberof GetMiscRandomnumber200Response
     */
    numbers?: Array<number>;
}

/**
 * Check if a given object implements the GetMiscRandomnumber200Response interface.
 */
export function instanceOfGetMiscRandomnumber200Response(value: object): value is GetMiscRandomnumber200Response {
    return true;
}

export function GetMiscRandomnumber200ResponseFromJSON(json: any): GetMiscRandomnumber200Response {
    return GetMiscRandomnumber200ResponseFromJSONTyped(json, false);
}

export function GetMiscRandomnumber200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetMiscRandomnumber200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'numbers': json['numbers'] == null ? undefined : json['numbers'],
    };
}

export function GetMiscRandomnumber200ResponseToJSON(json: any): GetMiscRandomnumber200Response {
    return GetMiscRandomnumber200ResponseToJSONTyped(json, false);
}

export function GetMiscRandomnumber200ResponseToJSONTyped(value?: GetMiscRandomnumber200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'numbers': value['numbers'],
    };
}

