/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 统计摘要。
 * @export
 * @interface GetMiscHolidayCalendar200ResponseDataSummary
 */
export interface GetMiscHolidayCalendar200ResponseDataSummary {
    /**
     * 查询范围内总天数。
     * @type {number}
     * @memberof GetMiscHolidayCalendar200ResponseDataSummary
     */
    totalDays?: number;
    /**
     * 查询范围内周末天数。
     * @type {number}
     * @memberof GetMiscHolidayCalendar200ResponseDataSummary
     */
    weekendDays?: number;
    /**
     * 查询范围内工作日天数（含法定调休上班）。
     * @type {number}
     * @memberof GetMiscHolidayCalendar200ResponseDataSummary
     */
    workdays?: number;
    /**
     * 查询范围内休息日天数（含周末和法定休假）。
     * @type {number}
     * @memberof GetMiscHolidayCalendar200ResponseDataSummary
     */
    restDays?: number;
    /**
     * 按 holiday_type 过滤后的节日事件总数。
     * @type {number}
     * @memberof GetMiscHolidayCalendar200ResponseDataSummary
     */
    holidayEvents?: number;
    /**
     * 法定休假日天数。
     * @type {number}
     * @memberof GetMiscHolidayCalendar200ResponseDataSummary
     */
    legalRestDays?: number;
    /**
     * 法定调休上班天数。
     * @type {number}
     * @memberof GetMiscHolidayCalendar200ResponseDataSummary
     */
    legalWorkdays?: number;
}

/**
 * Check if a given object implements the GetMiscHolidayCalendar200ResponseDataSummary interface.
 */
export function instanceOfGetMiscHolidayCalendar200ResponseDataSummary(value: object): value is GetMiscHolidayCalendar200ResponseDataSummary {
    return true;
}

export function GetMiscHolidayCalendar200ResponseDataSummaryFromJSON(json: any): GetMiscHolidayCalendar200ResponseDataSummary {
    return GetMiscHolidayCalendar200ResponseDataSummaryFromJSONTyped(json, false);
}

export function GetMiscHolidayCalendar200ResponseDataSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetMiscHolidayCalendar200ResponseDataSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'totalDays': json['total_days'] == null ? undefined : json['total_days'],
        'weekendDays': json['weekend_days'] == null ? undefined : json['weekend_days'],
        'workdays': json['workdays'] == null ? undefined : json['workdays'],
        'restDays': json['rest_days'] == null ? undefined : json['rest_days'],
        'holidayEvents': json['holiday_events'] == null ? undefined : json['holiday_events'],
        'legalRestDays': json['legal_rest_days'] == null ? undefined : json['legal_rest_days'],
        'legalWorkdays': json['legal_workdays'] == null ? undefined : json['legal_workdays'],
    };
}

export function GetMiscHolidayCalendar200ResponseDataSummaryToJSON(json: any): GetMiscHolidayCalendar200ResponseDataSummary {
    return GetMiscHolidayCalendar200ResponseDataSummaryToJSONTyped(json, false);
}

export function GetMiscHolidayCalendar200ResponseDataSummaryToJSONTyped(value?: GetMiscHolidayCalendar200ResponseDataSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total_days': value['totalDays'],
        'weekend_days': value['weekendDays'],
        'workdays': value['workdays'],
        'rest_days': value['restDays'],
        'holiday_events': value['holidayEvents'],
        'legal_rest_days': value['legalRestDays'],
        'legal_workdays': value['legalWorkdays'],
    };
}

