/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetMiscTrackingDetect200ResponseAlternativesInner
 */
export interface GetMiscTrackingDetect200ResponseAlternativesInner {
    /**
     * 快递公司编码
     * @type {string}
     * @memberof GetMiscTrackingDetect200ResponseAlternativesInner
     */
    code?: string;
    /**
     * 快递公司名称
     * @type {string}
     * @memberof GetMiscTrackingDetect200ResponseAlternativesInner
     */
    name?: string;
}

/**
 * Check if a given object implements the GetMiscTrackingDetect200ResponseAlternativesInner interface.
 */
export function instanceOfGetMiscTrackingDetect200ResponseAlternativesInner(value: object): value is GetMiscTrackingDetect200ResponseAlternativesInner {
    return true;
}

export function GetMiscTrackingDetect200ResponseAlternativesInnerFromJSON(json: any): GetMiscTrackingDetect200ResponseAlternativesInner {
    return GetMiscTrackingDetect200ResponseAlternativesInnerFromJSONTyped(json, false);
}

export function GetMiscTrackingDetect200ResponseAlternativesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetMiscTrackingDetect200ResponseAlternativesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function GetMiscTrackingDetect200ResponseAlternativesInnerToJSON(json: any): GetMiscTrackingDetect200ResponseAlternativesInner {
    return GetMiscTrackingDetect200ResponseAlternativesInnerToJSONTyped(json, false);
}

export function GetMiscTrackingDetect200ResponseAlternativesInnerToJSONTyped(value?: GetMiscTrackingDetect200ResponseAlternativesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'name': value['name'],
    };
}

