/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetMiscWeather503Response
 */
export interface GetMiscWeather503Response {
    /**
     * 
     * @type {string}
     * @memberof GetMiscWeather503Response
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof GetMiscWeather503Response
     */
    message?: string;
}

/**
 * Check if a given object implements the GetMiscWeather503Response interface.
 */
export function instanceOfGetMiscWeather503Response(value: object): value is GetMiscWeather503Response {
    return true;
}

export function GetMiscWeather503ResponseFromJSON(json: any): GetMiscWeather503Response {
    return GetMiscWeather503ResponseFromJSONTyped(json, false);
}

export function GetMiscWeather503ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetMiscWeather503Response {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function GetMiscWeather503ResponseToJSON(json: any): GetMiscWeather503Response {
    return GetMiscWeather503ResponseToJSONTyped(json, false);
}

export function GetMiscWeather503ResponseToJSONTyped(value?: GetMiscWeather503Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
    };
}

