/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 空气污染物分项数据（extended=true 时返回，部分数据源可能不返回）
 * @export
 * @interface GetMiscWeather200ResponseAirPollutants
 */
export interface GetMiscWeather200ResponseAirPollutants {
    /**
     * PM2.5 μg/m³
     * @type {number}
     * @memberof GetMiscWeather200ResponseAirPollutants
     */
    pm25?: number;
    /**
     * PM10 μg/m³
     * @type {number}
     * @memberof GetMiscWeather200ResponseAirPollutants
     */
    pm10?: number;
    /**
     * 臭氧 μg/m³
     * @type {number}
     * @memberof GetMiscWeather200ResponseAirPollutants
     */
    o3?: number;
    /**
     * 二氧化氮 μg/m³
     * @type {number}
     * @memberof GetMiscWeather200ResponseAirPollutants
     */
    no2?: number;
    /**
     * 二氧化硫 μg/m³
     * @type {number}
     * @memberof GetMiscWeather200ResponseAirPollutants
     */
    so2?: number;
    /**
     * 一氧化碳 mg/m³
     * @type {number}
     * @memberof GetMiscWeather200ResponseAirPollutants
     */
    co?: number;
}

/**
 * Check if a given object implements the GetMiscWeather200ResponseAirPollutants interface.
 */
export function instanceOfGetMiscWeather200ResponseAirPollutants(value: object): value is GetMiscWeather200ResponseAirPollutants {
    return true;
}

export function GetMiscWeather200ResponseAirPollutantsFromJSON(json: any): GetMiscWeather200ResponseAirPollutants {
    return GetMiscWeather200ResponseAirPollutantsFromJSONTyped(json, false);
}

export function GetMiscWeather200ResponseAirPollutantsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetMiscWeather200ResponseAirPollutants {
    if (json == null) {
        return json;
    }
    return {
        
        'pm25': json['pm25'] == null ? undefined : json['pm25'],
        'pm10': json['pm10'] == null ? undefined : json['pm10'],
        'o3': json['o3'] == null ? undefined : json['o3'],
        'no2': json['no2'] == null ? undefined : json['no2'],
        'so2': json['so2'] == null ? undefined : json['so2'],
        'co': json['co'] == null ? undefined : json['co'],
    };
}

export function GetMiscWeather200ResponseAirPollutantsToJSON(json: any): GetMiscWeather200ResponseAirPollutants {
    return GetMiscWeather200ResponseAirPollutantsToJSONTyped(json, false);
}

export function GetMiscWeather200ResponseAirPollutantsToJSONTyped(value?: GetMiscWeather200ResponseAirPollutants | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pm25': value['pm25'],
        'pm10': value['pm10'],
        'o3': value['o3'],
        'no2': value['no2'],
        'so2': value['so2'],
        'co': value['co'],
    };
}

