/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetMiscDistrict200ResponseResultsInnerCenter } from './GetMiscDistrict200ResponseResultsInnerCenter';
import {
    GetMiscDistrict200ResponseResultsInnerCenterFromJSON,
    GetMiscDistrict200ResponseResultsInnerCenterFromJSONTyped,
    GetMiscDistrict200ResponseResultsInnerCenterToJSON,
    GetMiscDistrict200ResponseResultsInnerCenterToJSONTyped,
} from './GetMiscDistrict200ResponseResultsInnerCenter';

/**
 * 
 * @export
 * @interface GetMiscDistrict200ResponseResultsInner
 */
export interface GetMiscDistrict200ResponseResultsInner {
    /**
     * 地区名称。
     * @type {string}
     * @memberof GetMiscDistrict200ResponseResultsInner
     */
    name?: string;
    /**
     * 行政级别：province / city / district / street。
     * @type {string}
     * @memberof GetMiscDistrict200ResponseResultsInner
     */
    level?: string;
    /**
     * 国家名称。
     * @type {string}
     * @memberof GetMiscDistrict200ResponseResultsInner
     */
    country?: string;
    /**
     * ISO 3166-1 alpha-2 国家代码。
     * @type {string}
     * @memberof GetMiscDistrict200ResponseResultsInner
     */
    countryCode?: string;
    /**
     * 省/州（中国数据）或一级行政区（国际数据）。
     * @type {string}
     * @memberof GetMiscDistrict200ResponseResultsInner
     */
    province?: string;
    /**
     * 市（仅中国数据）。
     * @type {string}
     * @memberof GetMiscDistrict200ResponseResultsInner
     */
    city?: string;
    /**
     * 区/县（仅中国数据）。
     * @type {string}
     * @memberof GetMiscDistrict200ResponseResultsInner
     */
    district?: string;
    /**
     * 街道/乡镇（仅中国数据）。
     * @type {string}
     * @memberof GetMiscDistrict200ResponseResultsInner
     */
    street?: string;
    /**
     * 行政区划代码（仅中国数据）。
     * @type {string}
     * @memberof GetMiscDistrict200ResponseResultsInner
     */
    adcode?: string;
    /**
     * 城市区号（仅中国数据）。
     * @type {string}
     * @memberof GetMiscDistrict200ResponseResultsInner
     */
    citycode?: string;
    /**
     * 
     * @type {GetMiscDistrict200ResponseResultsInnerCenter}
     * @memberof GetMiscDistrict200ResponseResultsInner
     */
    center?: GetMiscDistrict200ResponseResultsInnerCenter;
    /**
     * 人口（仅国际城市数据）。
     * @type {number}
     * @memberof GetMiscDistrict200ResponseResultsInner
     */
    population?: number;
    /**
     * 时区（仅国际城市数据），如 Asia/Tokyo。
     * @type {string}
     * @memberof GetMiscDistrict200ResponseResultsInner
     */
    timezone?: string;
}

/**
 * Check if a given object implements the GetMiscDistrict200ResponseResultsInner interface.
 */
export function instanceOfGetMiscDistrict200ResponseResultsInner(value: object): value is GetMiscDistrict200ResponseResultsInner {
    return true;
}

export function GetMiscDistrict200ResponseResultsInnerFromJSON(json: any): GetMiscDistrict200ResponseResultsInner {
    return GetMiscDistrict200ResponseResultsInnerFromJSONTyped(json, false);
}

export function GetMiscDistrict200ResponseResultsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetMiscDistrict200ResponseResultsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'level': json['level'] == null ? undefined : json['level'],
        'country': json['country'] == null ? undefined : json['country'],
        'countryCode': json['country_code'] == null ? undefined : json['country_code'],
        'province': json['province'] == null ? undefined : json['province'],
        'city': json['city'] == null ? undefined : json['city'],
        'district': json['district'] == null ? undefined : json['district'],
        'street': json['street'] == null ? undefined : json['street'],
        'adcode': json['adcode'] == null ? undefined : json['adcode'],
        'citycode': json['citycode'] == null ? undefined : json['citycode'],
        'center': json['center'] == null ? undefined : GetMiscDistrict200ResponseResultsInnerCenterFromJSON(json['center']),
        'population': json['population'] == null ? undefined : json['population'],
        'timezone': json['timezone'] == null ? undefined : json['timezone'],
    };
}

export function GetMiscDistrict200ResponseResultsInnerToJSON(json: any): GetMiscDistrict200ResponseResultsInner {
    return GetMiscDistrict200ResponseResultsInnerToJSONTyped(json, false);
}

export function GetMiscDistrict200ResponseResultsInnerToJSONTyped(value?: GetMiscDistrict200ResponseResultsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'level': value['level'],
        'country': value['country'],
        'country_code': value['countryCode'],
        'province': value['province'],
        'city': value['city'],
        'district': value['district'],
        'street': value['street'],
        'adcode': value['adcode'],
        'citycode': value['citycode'],
        'center': GetMiscDistrict200ResponseResultsInnerCenterToJSON(value['center']),
        'population': value['population'],
        'timezone': value['timezone'],
    };
}

