/* tslint:disable */
/* eslint-disable */
/**
 * UAPI OpenAPI
 * Generated from UAPI JSON. Code is the interactive documentation: rich descriptions, examples, and x-extensions preserved.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetMiscMovieBoxOffice503Response
 */
export interface GetMiscMovieBoxOffice503Response {
    /**
     * 
     * @type {number}
     * @memberof GetMiscMovieBoxOffice503Response
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof GetMiscMovieBoxOffice503Response
     */
    message?: string;
}

/**
 * Check if a given object implements the GetMiscMovieBoxOffice503Response interface.
 */
export function instanceOfGetMiscMovieBoxOffice503Response(value: object): value is GetMiscMovieBoxOffice503Response {
    return true;
}

export function GetMiscMovieBoxOffice503ResponseFromJSON(json: any): GetMiscMovieBoxOffice503Response {
    return GetMiscMovieBoxOffice503ResponseFromJSONTyped(json, false);
}

export function GetMiscMovieBoxOffice503ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetMiscMovieBoxOffice503Response {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function GetMiscMovieBoxOffice503ResponseToJSON(json: any): GetMiscMovieBoxOffice503Response {
    return GetMiscMovieBoxOffice503ResponseToJSONTyped(json, false);
}

export function GetMiscMovieBoxOffice503ResponseToJSONTyped(value?: GetMiscMovieBoxOffice503Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
    };
}

