/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 防晒指数
 * @export
 * @interface GetMiscWeather200ResponseLifeIndicesSunscreen
 */
export interface GetMiscWeather200ResponseLifeIndicesSunscreen {
    /**
     * 
     * @type {string}
     * @memberof GetMiscWeather200ResponseLifeIndicesSunscreen
     */
    level?: string;
    /**
     * 
     * @type {string}
     * @memberof GetMiscWeather200ResponseLifeIndicesSunscreen
     */
    brief?: string;
    /**
     * 
     * @type {string}
     * @memberof GetMiscWeather200ResponseLifeIndicesSunscreen
     */
    advice?: string;
}

/**
 * Check if a given object implements the GetMiscWeather200ResponseLifeIndicesSunscreen interface.
 */
export function instanceOfGetMiscWeather200ResponseLifeIndicesSunscreen(value: object): value is GetMiscWeather200ResponseLifeIndicesSunscreen {
    return true;
}

export function GetMiscWeather200ResponseLifeIndicesSunscreenFromJSON(json: any): GetMiscWeather200ResponseLifeIndicesSunscreen {
    return GetMiscWeather200ResponseLifeIndicesSunscreenFromJSONTyped(json, false);
}

export function GetMiscWeather200ResponseLifeIndicesSunscreenFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetMiscWeather200ResponseLifeIndicesSunscreen {
    if (json == null) {
        return json;
    }
    return {
        
        'level': json['level'] == null ? undefined : json['level'],
        'brief': json['brief'] == null ? undefined : json['brief'],
        'advice': json['advice'] == null ? undefined : json['advice'],
    };
}

export function GetMiscWeather200ResponseLifeIndicesSunscreenToJSON(json: any): GetMiscWeather200ResponseLifeIndicesSunscreen {
    return GetMiscWeather200ResponseLifeIndicesSunscreenToJSONTyped(json, false);
}

export function GetMiscWeather200ResponseLifeIndicesSunscreenToJSONTyped(value?: GetMiscWeather200ResponseLifeIndicesSunscreen | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'level': value['level'],
        'brief': value['brief'],
        'advice': value['advice'],
    };
}

