/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetMiscTrackingQuery200ResponseTracksInner
 */
export interface GetMiscTrackingQuery200ResponseTracksInner {
    /**
     * 物流更新时间
     * @type {string}
     * @memberof GetMiscTrackingQuery200ResponseTracksInner
     */
    time?: string;
    /**
     * 物流状态描述
     * @type {string}
     * @memberof GetMiscTrackingQuery200ResponseTracksInner
     */
    context?: string;
}

/**
 * Check if a given object implements the GetMiscTrackingQuery200ResponseTracksInner interface.
 */
export function instanceOfGetMiscTrackingQuery200ResponseTracksInner(value: object): value is GetMiscTrackingQuery200ResponseTracksInner {
    return true;
}

export function GetMiscTrackingQuery200ResponseTracksInnerFromJSON(json: any): GetMiscTrackingQuery200ResponseTracksInner {
    return GetMiscTrackingQuery200ResponseTracksInnerFromJSONTyped(json, false);
}

export function GetMiscTrackingQuery200ResponseTracksInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetMiscTrackingQuery200ResponseTracksInner {
    if (json == null) {
        return json;
    }
    return {
        
        'time': json['time'] == null ? undefined : json['time'],
        'context': json['context'] == null ? undefined : json['context'],
    };
}

export function GetMiscTrackingQuery200ResponseTracksInnerToJSON(json: any): GetMiscTrackingQuery200ResponseTracksInner {
    return GetMiscTrackingQuery200ResponseTracksInnerToJSONTyped(json, false);
}

export function GetMiscTrackingQuery200ResponseTracksInnerToJSONTyped(value?: GetMiscTrackingQuery200ResponseTracksInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'time': value['time'],
        'context': value['context'],
    };
}

