/* tslint:disable */
/* eslint-disable */
/**
 * UAPI OpenAPI
 * Generated from UAPI JSON. Code is the interactive documentation: rich descriptions, examples, and x-extensions preserved.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetMiscTrackingQuery200ResponseTracksInner } from './GetMiscTrackingQuery200ResponseTracksInner';
import {
    GetMiscTrackingQuery200ResponseTracksInnerFromJSON,
    GetMiscTrackingQuery200ResponseTracksInnerFromJSONTyped,
    GetMiscTrackingQuery200ResponseTracksInnerToJSON,
    GetMiscTrackingQuery200ResponseTracksInnerToJSONTyped,
} from './GetMiscTrackingQuery200ResponseTracksInner';

/**
 * 
 * @export
 * @interface GetMiscTrackingQuery200Response
 */
export interface GetMiscTrackingQuery200Response {
    /**
     * 快递公司编码
     * @type {string}
     * @memberof GetMiscTrackingQuery200Response
     */
    carrierCode?: string;
    /**
     * 快递公司名称
     * @type {string}
     * @memberof GetMiscTrackingQuery200Response
     */
    carrierName?: string;
    /**
     * 完成时间。仅已完成时返回签收或妥投对应的轨迹时间；未完成时为空字符串。
     * @type {string}
     * @memberof GetMiscTrackingQuery200Response
     */
    completedAt?: string;
    /**
     * 快递是否已完成。仅当状态识别为已签收/已妥投/已完成时为 true。
     * @type {boolean}
     * @memberof GetMiscTrackingQuery200Response
     */
    isCompleted?: boolean;
    /**
     * 快递状态中文名称，例如：待揽收、已揽收、运输中、派送中、已完成、异常、未知。
     * @type {string}
     * @memberof GetMiscTrackingQuery200Response
     */
    status?: string;
    /**
     * 快递状态编码。可能值：pending、picked_up、in_transit、out_for_delivery、delivered、exception、unknown。
     * @type {string}
     * @memberof GetMiscTrackingQuery200Response
     */
    statusCode?: string;
    /**
     * 物流轨迹数量
     * @type {number}
     * @memberof GetMiscTrackingQuery200Response
     */
    trackCount?: number;
    /**
     * 快递单号
     * @type {string}
     * @memberof GetMiscTrackingQuery200Response
     */
    trackingNumber?: string;
    /**
     * 物流轨迹列表，按时间倒序排列
     * @type {Array<GetMiscTrackingQuery200ResponseTracksInner>}
     * @memberof GetMiscTrackingQuery200Response
     */
    tracks?: Array<GetMiscTrackingQuery200ResponseTracksInner>;
}

/**
 * Check if a given object implements the GetMiscTrackingQuery200Response interface.
 */
export function instanceOfGetMiscTrackingQuery200Response(value: object): value is GetMiscTrackingQuery200Response {
    return true;
}

export function GetMiscTrackingQuery200ResponseFromJSON(json: any): GetMiscTrackingQuery200Response {
    return GetMiscTrackingQuery200ResponseFromJSONTyped(json, false);
}

export function GetMiscTrackingQuery200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetMiscTrackingQuery200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'carrierCode': json['carrier_code'] == null ? undefined : json['carrier_code'],
        'carrierName': json['carrier_name'] == null ? undefined : json['carrier_name'],
        'completedAt': json['completed_at'] == null ? undefined : json['completed_at'],
        'isCompleted': json['is_completed'] == null ? undefined : json['is_completed'],
        'status': json['status'] == null ? undefined : json['status'],
        'statusCode': json['status_code'] == null ? undefined : json['status_code'],
        'trackCount': json['track_count'] == null ? undefined : json['track_count'],
        'trackingNumber': json['tracking_number'] == null ? undefined : json['tracking_number'],
        'tracks': json['tracks'] == null ? undefined : ((json['tracks'] as Array<any>).map(GetMiscTrackingQuery200ResponseTracksInnerFromJSON)),
    };
}

export function GetMiscTrackingQuery200ResponseToJSON(json: any): GetMiscTrackingQuery200Response {
    return GetMiscTrackingQuery200ResponseToJSONTyped(json, false);
}

export function GetMiscTrackingQuery200ResponseToJSONTyped(value?: GetMiscTrackingQuery200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'carrier_code': value['carrierCode'],
        'carrier_name': value['carrierName'],
        'completed_at': value['completedAt'],
        'is_completed': value['isCompleted'],
        'status': value['status'],
        'status_code': value['statusCode'],
        'track_count': value['trackCount'],
        'tracking_number': value['trackingNumber'],
        'tracks': value['tracks'] == null ? undefined : ((value['tracks'] as Array<any>).map(GetMiscTrackingQuery200ResponseTracksInnerToJSON)),
    };
}

