/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetMiscHolidayCalendar200ResponseDaysInner
 */
export interface GetMiscHolidayCalendar200ResponseDaysInner {
    /**
     * 公历日期（YYYY-MM-DD）。
     * @type {string}
     * @memberof GetMiscHolidayCalendar200ResponseDaysInner
     */
    date?: string;
    /**
     * 公历年份。
     * @type {number}
     * @memberof GetMiscHolidayCalendar200ResponseDaysInner
     */
    year?: number;
    /**
     * 公历月份。
     * @type {number}
     * @memberof GetMiscHolidayCalendar200ResponseDaysInner
     */
    month?: number;
    /**
     * 公历日期（天）。
     * @type {number}
     * @memberof GetMiscHolidayCalendar200ResponseDaysInner
     */
    day?: number;
    /**
     * 中文星期，如星期三。
     * @type {string}
     * @memberof GetMiscHolidayCalendar200ResponseDaysInner
     */
    weekdayCn?: string;
    /**
     * 是否为周末。
     * @type {boolean}
     * @memberof GetMiscHolidayCalendar200ResponseDaysInner
     */
    isWeekend?: boolean;
    /**
     * 是否为工作日（含法定调休上班日）。
     * @type {boolean}
     * @memberof GetMiscHolidayCalendar200ResponseDaysInner
     */
    isWorkday?: boolean;
    /**
     * 是否为休息日。
     * @type {boolean}
     * @memberof GetMiscHolidayCalendar200ResponseDaysInner
     */
    isRestDay?: boolean;
    /**
     * 当天是否存在节日、节气或法定事件。
     * @type {boolean}
     * @memberof GetMiscHolidayCalendar200ResponseDaysInner
     */
    isHoliday?: boolean;
    /**
     * 法定节假日名称，无则为空或不返回。
     * @type {string}
     * @memberof GetMiscHolidayCalendar200ResponseDaysInner
     */
    legalHolidayName?: string;
    /**
     * 法定假日类型：rest 或 workday_adjust。
     * @type {string}
     * @memberof GetMiscHolidayCalendar200ResponseDaysInner
     */
    legalHolidayType?: string;
    /**
     * 公历节日名称。有值时返回。
     * @type {string}
     * @memberof GetMiscHolidayCalendar200ResponseDaysInner
     */
    solarFestival?: string;
    /**
     * 农历节日名称。有值时返回。
     * @type {string}
     * @memberof GetMiscHolidayCalendar200ResponseDaysInner
     */
    lunarFestival?: string;
    /**
     * 节气名称。有值时返回。
     * @type {string}
     * @memberof GetMiscHolidayCalendar200ResponseDaysInner
     */
    solarTerm?: string;
    /**
     * 农历年份（数字）。
     * @type {number}
     * @memberof GetMiscHolidayCalendar200ResponseDaysInner
     */
    lunarYear?: number;
    /**
     * 农历月份（数字）。
     * @type {number}
     * @memberof GetMiscHolidayCalendar200ResponseDaysInner
     */
    lunarMonth?: number;
    /**
     * 农历日期（数字）。
     * @type {number}
     * @memberof GetMiscHolidayCalendar200ResponseDaysInner
     */
    lunarDay?: number;
    /**
     * 农历月份中文名称。
     * @type {string}
     * @memberof GetMiscHolidayCalendar200ResponseDaysInner
     */
    lunarMonthName?: string;
    /**
     * 农历日期中文名称。
     * @type {string}
     * @memberof GetMiscHolidayCalendar200ResponseDaysInner
     */
    lunarDayName?: string;
    /**
     * 干支年。
     * @type {string}
     * @memberof GetMiscHolidayCalendar200ResponseDaysInner
     */
    ganzhiYear?: string;
    /**
     * 干支月。
     * @type {string}
     * @memberof GetMiscHolidayCalendar200ResponseDaysInner
     */
    ganzhiMonth?: string;
    /**
     * 干支日。
     * @type {string}
     * @memberof GetMiscHolidayCalendar200ResponseDaysInner
     */
    ganzhiDay?: string;
}

/**
 * Check if a given object implements the GetMiscHolidayCalendar200ResponseDaysInner interface.
 */
export function instanceOfGetMiscHolidayCalendar200ResponseDaysInner(value: object): value is GetMiscHolidayCalendar200ResponseDaysInner {
    return true;
}

export function GetMiscHolidayCalendar200ResponseDaysInnerFromJSON(json: any): GetMiscHolidayCalendar200ResponseDaysInner {
    return GetMiscHolidayCalendar200ResponseDaysInnerFromJSONTyped(json, false);
}

export function GetMiscHolidayCalendar200ResponseDaysInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetMiscHolidayCalendar200ResponseDaysInner {
    if (json == null) {
        return json;
    }
    return {
        
        'date': json['date'] == null ? undefined : json['date'],
        'year': json['year'] == null ? undefined : json['year'],
        'month': json['month'] == null ? undefined : json['month'],
        'day': json['day'] == null ? undefined : json['day'],
        'weekdayCn': json['weekday_cn'] == null ? undefined : json['weekday_cn'],
        'isWeekend': json['is_weekend'] == null ? undefined : json['is_weekend'],
        'isWorkday': json['is_workday'] == null ? undefined : json['is_workday'],
        'isRestDay': json['is_rest_day'] == null ? undefined : json['is_rest_day'],
        'isHoliday': json['is_holiday'] == null ? undefined : json['is_holiday'],
        'legalHolidayName': json['legal_holiday_name'] == null ? undefined : json['legal_holiday_name'],
        'legalHolidayType': json['legal_holiday_type'] == null ? undefined : json['legal_holiday_type'],
        'solarFestival': json['solar_festival'] == null ? undefined : json['solar_festival'],
        'lunarFestival': json['lunar_festival'] == null ? undefined : json['lunar_festival'],
        'solarTerm': json['solar_term'] == null ? undefined : json['solar_term'],
        'lunarYear': json['lunar_year'] == null ? undefined : json['lunar_year'],
        'lunarMonth': json['lunar_month'] == null ? undefined : json['lunar_month'],
        'lunarDay': json['lunar_day'] == null ? undefined : json['lunar_day'],
        'lunarMonthName': json['lunar_month_name'] == null ? undefined : json['lunar_month_name'],
        'lunarDayName': json['lunar_day_name'] == null ? undefined : json['lunar_day_name'],
        'ganzhiYear': json['ganzhi_year'] == null ? undefined : json['ganzhi_year'],
        'ganzhiMonth': json['ganzhi_month'] == null ? undefined : json['ganzhi_month'],
        'ganzhiDay': json['ganzhi_day'] == null ? undefined : json['ganzhi_day'],
    };
}

export function GetMiscHolidayCalendar200ResponseDaysInnerToJSON(json: any): GetMiscHolidayCalendar200ResponseDaysInner {
    return GetMiscHolidayCalendar200ResponseDaysInnerToJSONTyped(json, false);
}

export function GetMiscHolidayCalendar200ResponseDaysInnerToJSONTyped(value?: GetMiscHolidayCalendar200ResponseDaysInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date': value['date'],
        'year': value['year'],
        'month': value['month'],
        'day': value['day'],
        'weekday_cn': value['weekdayCn'],
        'is_weekend': value['isWeekend'],
        'is_workday': value['isWorkday'],
        'is_rest_day': value['isRestDay'],
        'is_holiday': value['isHoliday'],
        'legal_holiday_name': value['legalHolidayName'],
        'legal_holiday_type': value['legalHolidayType'],
        'solar_festival': value['solarFestival'],
        'lunar_festival': value['lunarFestival'],
        'solar_term': value['solarTerm'],
        'lunar_year': value['lunarYear'],
        'lunar_month': value['lunarMonth'],
        'lunar_day': value['lunarDay'],
        'lunar_month_name': value['lunarMonthName'],
        'lunar_day_name': value['lunarDayName'],
        'ganzhi_year': value['ganzhiYear'],
        'ganzhi_month': value['ganzhiMonth'],
        'ganzhi_day': value['ganzhiDay'],
    };
}

