/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 请求参数回显。
 * @export
 * @interface GetMiscHolidayCalendar200ResponseDataQuery
 */
export interface GetMiscHolidayCalendar200ResponseDataQuery {
    /**
     * 日视图查询参数（YYYY-MM-DD）。非日视图时可能为空。
     * @type {string}
     * @memberof GetMiscHolidayCalendar200ResponseDataQuery
     */
    date?: string;
    /**
     * 月视图查询参数（YYYY-MM）。非月视图时可能为空。
     * @type {string}
     * @memberof GetMiscHolidayCalendar200ResponseDataQuery
     */
    month?: string;
    /**
     * 年视图查询参数（YYYY）。非年视图时可能为空。
     * @type {string}
     * @memberof GetMiscHolidayCalendar200ResponseDataQuery
     */
    year?: string;
    /**
     * 实际生效的时区。
     * @type {string}
     * @memberof GetMiscHolidayCalendar200ResponseDataQuery
     */
    timezone?: string;
    /**
     * 节日筛选类型。
     * @type {string}
     * @memberof GetMiscHolidayCalendar200ResponseDataQuery
     */
    holidayType?: string;
    /**
     * 是否开启前后最近节日查询。
     * @type {boolean}
     * @memberof GetMiscHolidayCalendar200ResponseDataQuery
     */
    includeNearby?: boolean;
    /**
     * 前后最近节日返回数量上限。
     * @type {number}
     * @memberof GetMiscHolidayCalendar200ResponseDataQuery
     */
    nearbyLimit?: number;
}

/**
 * Check if a given object implements the GetMiscHolidayCalendar200ResponseDataQuery interface.
 */
export function instanceOfGetMiscHolidayCalendar200ResponseDataQuery(value: object): value is GetMiscHolidayCalendar200ResponseDataQuery {
    return true;
}

export function GetMiscHolidayCalendar200ResponseDataQueryFromJSON(json: any): GetMiscHolidayCalendar200ResponseDataQuery {
    return GetMiscHolidayCalendar200ResponseDataQueryFromJSONTyped(json, false);
}

export function GetMiscHolidayCalendar200ResponseDataQueryFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetMiscHolidayCalendar200ResponseDataQuery {
    if (json == null) {
        return json;
    }
    return {
        
        'date': json['date'] == null ? undefined : json['date'],
        'month': json['month'] == null ? undefined : json['month'],
        'year': json['year'] == null ? undefined : json['year'],
        'timezone': json['timezone'] == null ? undefined : json['timezone'],
        'holidayType': json['holiday_type'] == null ? undefined : json['holiday_type'],
        'includeNearby': json['include_nearby'] == null ? undefined : json['include_nearby'],
        'nearbyLimit': json['nearby_limit'] == null ? undefined : json['nearby_limit'],
    };
}

export function GetMiscHolidayCalendar200ResponseDataQueryToJSON(json: any): GetMiscHolidayCalendar200ResponseDataQuery {
    return GetMiscHolidayCalendar200ResponseDataQueryToJSONTyped(json, false);
}

export function GetMiscHolidayCalendar200ResponseDataQueryToJSONTyped(value?: GetMiscHolidayCalendar200ResponseDataQuery | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date': value['date'],
        'month': value['month'],
        'year': value['year'],
        'timezone': value['timezone'],
        'holiday_type': value['holidayType'],
        'include_nearby': value['includeNearby'],
        'nearby_limit': value['nearbyLimit'],
    };
}

