/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetMiscHolidayCalendar200ResponseDataNearbyPreviousInner
 */
export interface GetMiscHolidayCalendar200ResponseDataNearbyPreviousInner {
    /**
     * 事件日期。
     * @type {string}
     * @memberof GetMiscHolidayCalendar200ResponseDataNearbyPreviousInner
     */
    date?: string;
    /**
     * 事件名称。
     * @type {string}
     * @memberof GetMiscHolidayCalendar200ResponseDataNearbyPreviousInner
     */
    name?: string;
    /**
     * 事件类型。
     * @type {string}
     * @memberof GetMiscHolidayCalendar200ResponseDataNearbyPreviousInner
     */
    type?: string;
}

/**
 * Check if a given object implements the GetMiscHolidayCalendar200ResponseDataNearbyPreviousInner interface.
 */
export function instanceOfGetMiscHolidayCalendar200ResponseDataNearbyPreviousInner(value: object): value is GetMiscHolidayCalendar200ResponseDataNearbyPreviousInner {
    return true;
}

export function GetMiscHolidayCalendar200ResponseDataNearbyPreviousInnerFromJSON(json: any): GetMiscHolidayCalendar200ResponseDataNearbyPreviousInner {
    return GetMiscHolidayCalendar200ResponseDataNearbyPreviousInnerFromJSONTyped(json, false);
}

export function GetMiscHolidayCalendar200ResponseDataNearbyPreviousInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetMiscHolidayCalendar200ResponseDataNearbyPreviousInner {
    if (json == null) {
        return json;
    }
    return {
        
        'date': json['date'] == null ? undefined : json['date'],
        'name': json['name'] == null ? undefined : json['name'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function GetMiscHolidayCalendar200ResponseDataNearbyPreviousInnerToJSON(json: any): GetMiscHolidayCalendar200ResponseDataNearbyPreviousInner {
    return GetMiscHolidayCalendar200ResponseDataNearbyPreviousInnerToJSONTyped(json, false);
}

export function GetMiscHolidayCalendar200ResponseDataNearbyPreviousInnerToJSONTyped(value?: GetMiscHolidayCalendar200ResponseDataNearbyPreviousInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date': value['date'],
        'name': value['name'],
        'type': value['type'],
    };
}

