/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetMiscWeather200ResponseMinutelyPrecipDataInner
 */
export interface GetMiscWeather200ResponseMinutelyPrecipDataInner {
    /**
     * 预报时间 ISO8601
     * @type {string}
     * @memberof GetMiscWeather200ResponseMinutelyPrecipDataInner
     */
    time?: string;
    /**
     * 5分钟累计降水量 mm
     * @type {number}
     * @memberof GetMiscWeather200ResponseMinutelyPrecipDataInner
     */
    precip?: number;
    /**
     * 降水类型：rain / snow
     * @type {string}
     * @memberof GetMiscWeather200ResponseMinutelyPrecipDataInner
     */
    type?: string;
}

/**
 * Check if a given object implements the GetMiscWeather200ResponseMinutelyPrecipDataInner interface.
 */
export function instanceOfGetMiscWeather200ResponseMinutelyPrecipDataInner(value: object): value is GetMiscWeather200ResponseMinutelyPrecipDataInner {
    return true;
}

export function GetMiscWeather200ResponseMinutelyPrecipDataInnerFromJSON(json: any): GetMiscWeather200ResponseMinutelyPrecipDataInner {
    return GetMiscWeather200ResponseMinutelyPrecipDataInnerFromJSONTyped(json, false);
}

export function GetMiscWeather200ResponseMinutelyPrecipDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetMiscWeather200ResponseMinutelyPrecipDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        'time': json['time'] == null ? undefined : json['time'],
        'precip': json['precip'] == null ? undefined : json['precip'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function GetMiscWeather200ResponseMinutelyPrecipDataInnerToJSON(json: any): GetMiscWeather200ResponseMinutelyPrecipDataInner {
    return GetMiscWeather200ResponseMinutelyPrecipDataInnerToJSONTyped(json, false);
}

export function GetMiscWeather200ResponseMinutelyPrecipDataInnerToJSONTyped(value?: GetMiscWeather200ResponseMinutelyPrecipDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'time': value['time'],
        'precip': value['precip'],
        'type': value['type'],
    };
}

