/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 紫外线指数
 * @export
 * @interface GetMiscWeather200ResponseLifeIndicesUv
 */
export interface GetMiscWeather200ResponseLifeIndicesUv {
    /**
     * 
     * @type {string}
     * @memberof GetMiscWeather200ResponseLifeIndicesUv
     */
    level?: string;
    /**
     * 
     * @type {string}
     * @memberof GetMiscWeather200ResponseLifeIndicesUv
     */
    brief?: string;
    /**
     * 
     * @type {string}
     * @memberof GetMiscWeather200ResponseLifeIndicesUv
     */
    advice?: string;
}

/**
 * Check if a given object implements the GetMiscWeather200ResponseLifeIndicesUv interface.
 */
export function instanceOfGetMiscWeather200ResponseLifeIndicesUv(value: object): value is GetMiscWeather200ResponseLifeIndicesUv {
    return true;
}

export function GetMiscWeather200ResponseLifeIndicesUvFromJSON(json: any): GetMiscWeather200ResponseLifeIndicesUv {
    return GetMiscWeather200ResponseLifeIndicesUvFromJSONTyped(json, false);
}

export function GetMiscWeather200ResponseLifeIndicesUvFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetMiscWeather200ResponseLifeIndicesUv {
    if (json == null) {
        return json;
    }
    return {
        
        'level': json['level'] == null ? undefined : json['level'],
        'brief': json['brief'] == null ? undefined : json['brief'],
        'advice': json['advice'] == null ? undefined : json['advice'],
    };
}

export function GetMiscWeather200ResponseLifeIndicesUvToJSON(json: any): GetMiscWeather200ResponseLifeIndicesUv {
    return GetMiscWeather200ResponseLifeIndicesUvToJSONTyped(json, false);
}

export function GetMiscWeather200ResponseLifeIndicesUvToJSONTyped(value?: GetMiscWeather200ResponseLifeIndicesUv | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'level': value['level'],
        'brief': value['brief'],
        'advice': value['advice'],
    };
}

