/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 过敏指数
 * @export
 * @interface GetMiscWeather200ResponseLifeIndicesAllergy
 */
export interface GetMiscWeather200ResponseLifeIndicesAllergy {
    /**
     * 
     * @type {string}
     * @memberof GetMiscWeather200ResponseLifeIndicesAllergy
     */
    level?: string;
    /**
     * 
     * @type {string}
     * @memberof GetMiscWeather200ResponseLifeIndicesAllergy
     */
    brief?: string;
    /**
     * 
     * @type {string}
     * @memberof GetMiscWeather200ResponseLifeIndicesAllergy
     */
    advice?: string;
}

/**
 * Check if a given object implements the GetMiscWeather200ResponseLifeIndicesAllergy interface.
 */
export function instanceOfGetMiscWeather200ResponseLifeIndicesAllergy(value: object): value is GetMiscWeather200ResponseLifeIndicesAllergy {
    return true;
}

export function GetMiscWeather200ResponseLifeIndicesAllergyFromJSON(json: any): GetMiscWeather200ResponseLifeIndicesAllergy {
    return GetMiscWeather200ResponseLifeIndicesAllergyFromJSONTyped(json, false);
}

export function GetMiscWeather200ResponseLifeIndicesAllergyFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetMiscWeather200ResponseLifeIndicesAllergy {
    if (json == null) {
        return json;
    }
    return {
        
        'level': json['level'] == null ? undefined : json['level'],
        'brief': json['brief'] == null ? undefined : json['brief'],
        'advice': json['advice'] == null ? undefined : json['advice'],
    };
}

export function GetMiscWeather200ResponseLifeIndicesAllergyToJSON(json: any): GetMiscWeather200ResponseLifeIndicesAllergy {
    return GetMiscWeather200ResponseLifeIndicesAllergyToJSONTyped(json, false);
}

export function GetMiscWeather200ResponseLifeIndicesAllergyToJSONTyped(value?: GetMiscWeather200ResponseLifeIndicesAllergy | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'level': value['level'],
        'brief': value['brief'],
        'advice': value['advice'],
    };
}

