/* tslint:disable */
/* eslint-disable */
/**
 * UAPI OpenAPI
 * Generated from UAPI JSON. Code is the interactive documentation: rich descriptions, examples, and x-extensions preserved.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetMiscHotboard200ResponseOneOfListInner } from './GetMiscHotboard200ResponseOneOfListInner';
import {
    GetMiscHotboard200ResponseOneOfListInnerFromJSON,
    GetMiscHotboard200ResponseOneOfListInnerFromJSONTyped,
    GetMiscHotboard200ResponseOneOfListInnerToJSON,
    GetMiscHotboard200ResponseOneOfListInnerToJSONTyped,
} from './GetMiscHotboard200ResponseOneOfListInner';

/**
 * 
 * @export
 * @interface GetMiscHotboard200ResponseOneOf
 */
export interface GetMiscHotboard200ResponseOneOf {
    /**
     * 热榜条目列表。
     * @type {Array<GetMiscHotboard200ResponseOneOfListInner>}
     * @memberof GetMiscHotboard200ResponseOneOf
     */
    list?: Array<GetMiscHotboard200ResponseOneOfListInner>;
    /**
     * 时光机模式返回的快照实际时间戳（毫秒）。当前热榜模式下通常不返回。
     * @type {number}
     * @memberof GetMiscHotboard200ResponseOneOf
     */
    snapshotTime?: number;
    /**
     * 
     * @type {string}
     * @memberof GetMiscHotboard200ResponseOneOf
     */
    type?: string;
    /**
     * 热榜更新时间。时光机模式下对应返回快照的更新时间。
     * @type {string}
     * @memberof GetMiscHotboard200ResponseOneOf
     */
    updateTime?: string;
}

/**
 * Check if a given object implements the GetMiscHotboard200ResponseOneOf interface.
 */
export function instanceOfGetMiscHotboard200ResponseOneOf(value: object): value is GetMiscHotboard200ResponseOneOf {
    return true;
}

export function GetMiscHotboard200ResponseOneOfFromJSON(json: any): GetMiscHotboard200ResponseOneOf {
    return GetMiscHotboard200ResponseOneOfFromJSONTyped(json, false);
}

export function GetMiscHotboard200ResponseOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetMiscHotboard200ResponseOneOf {
    if (json == null) {
        return json;
    }
    return {
        
        'list': json['list'] == null ? undefined : ((json['list'] as Array<any>).map(GetMiscHotboard200ResponseOneOfListInnerFromJSON)),
        'snapshotTime': json['snapshot_time'] == null ? undefined : json['snapshot_time'],
        'type': json['type'] == null ? undefined : json['type'],
        'updateTime': json['update_time'] == null ? undefined : json['update_time'],
    };
}

export function GetMiscHotboard200ResponseOneOfToJSON(json: any): GetMiscHotboard200ResponseOneOf {
    return GetMiscHotboard200ResponseOneOfToJSONTyped(json, false);
}

export function GetMiscHotboard200ResponseOneOfToJSONTyped(value?: GetMiscHotboard200ResponseOneOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'list': value['list'] == null ? undefined : ((value['list'] as Array<any>).map(GetMiscHotboard200ResponseOneOfListInnerToJSON)),
        'snapshot_time': value['snapshotTime'],
        'type': value['type'],
        'update_time': value['updateTime'],
    };
}

