/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetMiscTrackingDetect404Response
 */
export interface GetMiscTrackingDetect404Response {
    /**
     * 
     * @type {string}
     * @memberof GetMiscTrackingDetect404Response
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof GetMiscTrackingDetect404Response
     */
    message?: string;
}

/**
 * Check if a given object implements the GetMiscTrackingDetect404Response interface.
 */
export function instanceOfGetMiscTrackingDetect404Response(value: object): value is GetMiscTrackingDetect404Response {
    return true;
}

export function GetMiscTrackingDetect404ResponseFromJSON(json: any): GetMiscTrackingDetect404Response {
    return GetMiscTrackingDetect404ResponseFromJSONTyped(json, false);
}

export function GetMiscTrackingDetect404ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetMiscTrackingDetect404Response {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function GetMiscTrackingDetect404ResponseToJSON(json: any): GetMiscTrackingDetect404Response {
    return GetMiscTrackingDetect404ResponseToJSONTyped(json, false);
}

export function GetMiscTrackingDetect404ResponseToJSONTyped(value?: GetMiscTrackingDetect404Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
    };
}

