/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 空气净化器指数
 * @export
 * @interface GetMiscWeather200ResponseLifeIndicesAirPurifier
 */
export interface GetMiscWeather200ResponseLifeIndicesAirPurifier {
    /**
     * 
     * @type {string}
     * @memberof GetMiscWeather200ResponseLifeIndicesAirPurifier
     */
    level?: string;
    /**
     * 
     * @type {string}
     * @memberof GetMiscWeather200ResponseLifeIndicesAirPurifier
     */
    brief?: string;
    /**
     * 
     * @type {string}
     * @memberof GetMiscWeather200ResponseLifeIndicesAirPurifier
     */
    advice?: string;
}

/**
 * Check if a given object implements the GetMiscWeather200ResponseLifeIndicesAirPurifier interface.
 */
export function instanceOfGetMiscWeather200ResponseLifeIndicesAirPurifier(value: object): value is GetMiscWeather200ResponseLifeIndicesAirPurifier {
    return true;
}

export function GetMiscWeather200ResponseLifeIndicesAirPurifierFromJSON(json: any): GetMiscWeather200ResponseLifeIndicesAirPurifier {
    return GetMiscWeather200ResponseLifeIndicesAirPurifierFromJSONTyped(json, false);
}

export function GetMiscWeather200ResponseLifeIndicesAirPurifierFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetMiscWeather200ResponseLifeIndicesAirPurifier {
    if (json == null) {
        return json;
    }
    return {
        
        'level': json['level'] == null ? undefined : json['level'],
        'brief': json['brief'] == null ? undefined : json['brief'],
        'advice': json['advice'] == null ? undefined : json['advice'],
    };
}

export function GetMiscWeather200ResponseLifeIndicesAirPurifierToJSON(json: any): GetMiscWeather200ResponseLifeIndicesAirPurifier {
    return GetMiscWeather200ResponseLifeIndicesAirPurifierToJSONTyped(json, false);
}

export function GetMiscWeather200ResponseLifeIndicesAirPurifierToJSONTyped(value?: GetMiscWeather200ResponseLifeIndicesAirPurifier | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'level': value['level'],
        'brief': value['brief'],
        'advice': value['advice'],
    };
}

