/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetMiscPhoneinfo400Response
 */
export interface GetMiscPhoneinfo400Response {
    /**
     * 
     * @type {string}
     * @memberof GetMiscPhoneinfo400Response
     */
    code?: string;
    /**
     * 
     * @type {object}
     * @memberof GetMiscPhoneinfo400Response
     */
    details?: object;
    /**
     * 
     * @type {string}
     * @memberof GetMiscPhoneinfo400Response
     */
    message?: string;
}

/**
 * Check if a given object implements the GetMiscPhoneinfo400Response interface.
 */
export function instanceOfGetMiscPhoneinfo400Response(value: object): value is GetMiscPhoneinfo400Response {
    return true;
}

export function GetMiscPhoneinfo400ResponseFromJSON(json: any): GetMiscPhoneinfo400Response {
    return GetMiscPhoneinfo400ResponseFromJSONTyped(json, false);
}

export function GetMiscPhoneinfo400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetMiscPhoneinfo400Response {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'details': json['details'] == null ? undefined : json['details'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function GetMiscPhoneinfo400ResponseToJSON(json: any): GetMiscPhoneinfo400Response {
    return GetMiscPhoneinfo400ResponseToJSONTyped(json, false);
}

export function GetMiscPhoneinfo400ResponseToJSONTyped(value?: GetMiscPhoneinfo400Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'details': value['details'],
        'message': value['message'],
    };
}

