/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetMiscDistrict400Response
 */
export interface GetMiscDistrict400Response {
    /**
     * 
     * @type {string}
     * @memberof GetMiscDistrict400Response
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof GetMiscDistrict400Response
     */
    message?: string;
}

/**
 * Check if a given object implements the GetMiscDistrict400Response interface.
 */
export function instanceOfGetMiscDistrict400Response(value: object): value is GetMiscDistrict400Response {
    return true;
}

export function GetMiscDistrict400ResponseFromJSON(json: any): GetMiscDistrict400Response {
    return GetMiscDistrict400ResponseFromJSONTyped(json, false);
}

export function GetMiscDistrict400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetMiscDistrict400Response {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function GetMiscDistrict400ResponseToJSON(json: any): GetMiscDistrict400Response {
    return GetMiscDistrict400ResponseToJSONTyped(json, false);
}

export function GetMiscDistrict400ResponseToJSONTyped(value?: GetMiscDistrict400Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
    };
}

