/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetMiscWorldtime200Response
 */
export interface GetMiscWorldtime200Response {
    /**
     * 
     * @type {string}
     * @memberof GetMiscWorldtime200Response
     */
    datetime?: string;
    /**
     * 
     * @type {number}
     * @memberof GetMiscWorldtime200Response
     */
    offsetSeconds?: number;
    /**
     * 
     * @type {string}
     * @memberof GetMiscWorldtime200Response
     */
    offsetString?: string;
    /**
     * 
     * @type {string}
     * @memberof GetMiscWorldtime200Response
     */
    query?: string;
    /**
     * 
     * @type {number}
     * @memberof GetMiscWorldtime200Response
     */
    timestampUnix?: number;
    /**
     * 
     * @type {string}
     * @memberof GetMiscWorldtime200Response
     */
    timezone?: string;
    /**
     * 
     * @type {string}
     * @memberof GetMiscWorldtime200Response
     */
    weekday?: string;
}

/**
 * Check if a given object implements the GetMiscWorldtime200Response interface.
 */
export function instanceOfGetMiscWorldtime200Response(value: object): value is GetMiscWorldtime200Response {
    return true;
}

export function GetMiscWorldtime200ResponseFromJSON(json: any): GetMiscWorldtime200Response {
    return GetMiscWorldtime200ResponseFromJSONTyped(json, false);
}

export function GetMiscWorldtime200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetMiscWorldtime200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'datetime': json['datetime'] == null ? undefined : json['datetime'],
        'offsetSeconds': json['offset_seconds'] == null ? undefined : json['offset_seconds'],
        'offsetString': json['offset_string'] == null ? undefined : json['offset_string'],
        'query': json['query'] == null ? undefined : json['query'],
        'timestampUnix': json['timestamp_unix'] == null ? undefined : json['timestamp_unix'],
        'timezone': json['timezone'] == null ? undefined : json['timezone'],
        'weekday': json['weekday'] == null ? undefined : json['weekday'],
    };
}

export function GetMiscWorldtime200ResponseToJSON(json: any): GetMiscWorldtime200Response {
    return GetMiscWorldtime200ResponseToJSONTyped(json, false);
}

export function GetMiscWorldtime200ResponseToJSONTyped(value?: GetMiscWorldtime200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'datetime': value['datetime'],
        'offset_seconds': value['offsetSeconds'],
        'offset_string': value['offsetString'],
        'query': value['query'],
        'timestamp_unix': value['timestampUnix'],
        'timezone': value['timezone'],
        'weekday': value['weekday'],
    };
}

