/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetNetworkWhois404Response
 */
export interface GetNetworkWhois404Response {
    /**
     * 
     * @type {string}
     * @memberof GetNetworkWhois404Response
     */
    code?: string;
    /**
     * 
     * @type {object}
     * @memberof GetNetworkWhois404Response
     */
    details?: object;
    /**
     * 
     * @type {string}
     * @memberof GetNetworkWhois404Response
     */
    message?: string;
}

/**
 * Check if a given object implements the GetNetworkWhois404Response interface.
 */
export function instanceOfGetNetworkWhois404Response(value: object): value is GetNetworkWhois404Response {
    return true;
}

export function GetNetworkWhois404ResponseFromJSON(json: any): GetNetworkWhois404Response {
    return GetNetworkWhois404ResponseFromJSONTyped(json, false);
}

export function GetNetworkWhois404ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetNetworkWhois404Response {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'details': json['details'] == null ? undefined : json['details'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function GetNetworkWhois404ResponseToJSON(json: any): GetNetworkWhois404Response {
    return GetNetworkWhois404ResponseToJSONTyped(json, false);
}

export function GetNetworkWhois404ResponseToJSONTyped(value?: GetNetworkWhois404Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'details': value['details'],
        'message': value['message'],
    };
}

