/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetNetworkIpinfo400Response
 */
export interface GetNetworkIpinfo400Response {
    /**
     * 
     * @type {string}
     * @memberof GetNetworkIpinfo400Response
     */
    code?: string;
    /**
     * 
     * @type {object}
     * @memberof GetNetworkIpinfo400Response
     */
    details?: object;
    /**
     * 
     * @type {string}
     * @memberof GetNetworkIpinfo400Response
     */
    message?: string;
}

/**
 * Check if a given object implements the GetNetworkIpinfo400Response interface.
 */
export function instanceOfGetNetworkIpinfo400Response(value: object): value is GetNetworkIpinfo400Response {
    return true;
}

export function GetNetworkIpinfo400ResponseFromJSON(json: any): GetNetworkIpinfo400Response {
    return GetNetworkIpinfo400ResponseFromJSONTyped(json, false);
}

export function GetNetworkIpinfo400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetNetworkIpinfo400Response {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'details': json['details'] == null ? undefined : json['details'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function GetNetworkIpinfo400ResponseToJSON(json: any): GetNetworkIpinfo400Response {
    return GetNetworkIpinfo400ResponseToJSONTyped(json, false);
}

export function GetNetworkIpinfo400ResponseToJSONTyped(value?: GetNetworkIpinfo400Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'details': value['details'],
        'message': value['message'],
    };
}

