/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 当目标 URL 不可达或请求失败（如 DNS 失败、超时、连接失败）时，`status` 为 `0`。
 * @export
 * @interface GetNetworkUrlstatus200ResponseOneOf1
 */
export interface GetNetworkUrlstatus200ResponseOneOf1 {
    /**
     * 目标不可达或请求失败时固定为 0。
     * @type {number}
     * @memberof GetNetworkUrlstatus200ResponseOneOf1
     */
    status?: number;
    /**
     * 
     * @type {string}
     * @memberof GetNetworkUrlstatus200ResponseOneOf1
     */
    url?: string;
}

/**
 * Check if a given object implements the GetNetworkUrlstatus200ResponseOneOf1 interface.
 */
export function instanceOfGetNetworkUrlstatus200ResponseOneOf1(value: object): value is GetNetworkUrlstatus200ResponseOneOf1 {
    return true;
}

export function GetNetworkUrlstatus200ResponseOneOf1FromJSON(json: any): GetNetworkUrlstatus200ResponseOneOf1 {
    return GetNetworkUrlstatus200ResponseOneOf1FromJSONTyped(json, false);
}

export function GetNetworkUrlstatus200ResponseOneOf1FromJSONTyped(json: any, ignoreDiscriminator: boolean): GetNetworkUrlstatus200ResponseOneOf1 {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function GetNetworkUrlstatus200ResponseOneOf1ToJSON(json: any): GetNetworkUrlstatus200ResponseOneOf1 {
    return GetNetworkUrlstatus200ResponseOneOf1ToJSONTyped(json, false);
}

export function GetNetworkUrlstatus200ResponseOneOf1ToJSONTyped(value?: GetNetworkUrlstatus200ResponseOneOf1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'url': value['url'],
    };
}

