/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 当目标 URL 可访问时，`status` 为目标返回的 HTTP 状态码（如 `200`）。
 * @export
 * @interface GetNetworkUrlstatus200ResponseOneOf
 */
export interface GetNetworkUrlstatus200ResponseOneOf {
    /**
     * 目标URL实际返回的HTTP状态码。
     * @type {number}
     * @memberof GetNetworkUrlstatus200ResponseOneOf
     */
    status?: number;
    /**
     * 
     * @type {string}
     * @memberof GetNetworkUrlstatus200ResponseOneOf
     */
    url?: string;
}

/**
 * Check if a given object implements the GetNetworkUrlstatus200ResponseOneOf interface.
 */
export function instanceOfGetNetworkUrlstatus200ResponseOneOf(value: object): value is GetNetworkUrlstatus200ResponseOneOf {
    return true;
}

export function GetNetworkUrlstatus200ResponseOneOfFromJSON(json: any): GetNetworkUrlstatus200ResponseOneOf {
    return GetNetworkUrlstatus200ResponseOneOfFromJSONTyped(json, false);
}

export function GetNetworkUrlstatus200ResponseOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetNetworkUrlstatus200ResponseOneOf {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function GetNetworkUrlstatus200ResponseOneOfToJSON(json: any): GetNetworkUrlstatus200ResponseOneOf {
    return GetNetworkUrlstatus200ResponseOneOfToJSONTyped(json, false);
}

export function GetNetworkUrlstatus200ResponseOneOfToJSONTyped(value?: GetNetworkUrlstatus200ResponseOneOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'url': value['url'],
    };
}

