/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetNetworkDns200ResponseRecordsInner
 */
export interface GetNetworkDns200ResponseRecordsInner {
    /**
     * 
     * @type {string}
     * @memberof GetNetworkDns200ResponseRecordsInner
     */
    content?: string;
    /**
     * 
     * @type {number}
     * @memberof GetNetworkDns200ResponseRecordsInner
     */
    flag?: number;
    /**
     * 
     * @type {number}
     * @memberof GetNetworkDns200ResponseRecordsInner
     */
    port?: number;
    /**
     * 
     * @type {number}
     * @memberof GetNetworkDns200ResponseRecordsInner
     */
    pri?: number;
    /**
     * 
     * @type {string}
     * @memberof GetNetworkDns200ResponseRecordsInner
     */
    tag?: string;
    /**
     * 
     * @type {string}
     * @memberof GetNetworkDns200ResponseRecordsInner
     */
    target?: string;
    /**
     * 
     * @type {number}
     * @memberof GetNetworkDns200ResponseRecordsInner
     */
    weight?: number;
}

/**
 * Check if a given object implements the GetNetworkDns200ResponseRecordsInner interface.
 */
export function instanceOfGetNetworkDns200ResponseRecordsInner(value: object): value is GetNetworkDns200ResponseRecordsInner {
    return true;
}

export function GetNetworkDns200ResponseRecordsInnerFromJSON(json: any): GetNetworkDns200ResponseRecordsInner {
    return GetNetworkDns200ResponseRecordsInnerFromJSONTyped(json, false);
}

export function GetNetworkDns200ResponseRecordsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetNetworkDns200ResponseRecordsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : json['content'],
        'flag': json['flag'] == null ? undefined : json['flag'],
        'port': json['port'] == null ? undefined : json['port'],
        'pri': json['pri'] == null ? undefined : json['pri'],
        'tag': json['tag'] == null ? undefined : json['tag'],
        'target': json['target'] == null ? undefined : json['target'],
        'weight': json['weight'] == null ? undefined : json['weight'],
    };
}

export function GetNetworkDns200ResponseRecordsInnerToJSON(json: any): GetNetworkDns200ResponseRecordsInner {
    return GetNetworkDns200ResponseRecordsInnerToJSONTyped(json, false);
}

export function GetNetworkDns200ResponseRecordsInnerToJSONTyped(value?: GetNetworkDns200ResponseRecordsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
        'flag': value['flag'],
        'port': value['port'],
        'pri': value['pri'],
        'tag': value['tag'],
        'target': value['target'],
        'weight': value['weight'],
    };
}

