/* tslint:disable */
/* eslint-disable */
/**
 * UAPI OpenAPI
 * Generated from UAPI JSON. Code is the interactive documentation: rich descriptions, examples, and x-extensions preserved.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetNetworkMyip200Response
 */
export interface GetNetworkMyip200Response {
    /**
     * 自治系统编号
     * @type {string}
     * @memberof GetNetworkMyip200Response
     */
    asn?: string;
    /**
     * IP段起始地址（标准查询）
     * @type {string}
     * @memberof GetNetworkMyip200Response
     */
    beginip?: string;
    /**
     * 行政区。仅 `source=commercial` 时可能返回。
     * @type {string}
     * @memberof GetNetworkMyip200Response
     */
    district?: string;
    /**
     * IP段结束地址（标准查询）
     * @type {string}
     * @memberof GetNetworkMyip200Response
     */
    endip?: string;
    /**
     * 你的公网IP地址
     * @type {string}
     * @memberof GetNetworkMyip200Response
     */
    ip?: string;
    /**
     * 运营商名称
     * @type {string}
     * @memberof GetNetworkMyip200Response
     */
    isp?: string;
    /**
     * 纬度
     * @type {number}
     * @memberof GetNetworkMyip200Response
     */
    latitude?: number;
    /**
     * 归属机构
     * @type {string}
     * @memberof GetNetworkMyip200Response
     */
    llc?: string;
    /**
     * 经度
     * @type {number}
     * @memberof GetNetworkMyip200Response
     */
    longitude?: number;
    /**
     * 地理位置，格式：国家 省份 城市
     * @type {string}
     * @memberof GetNetworkMyip200Response
     */
    region?: string;
    /**
     * 时区名称。仅 `source=commercial` 时可能返回。
     * @type {string}
     * @memberof GetNetworkMyip200Response
     */
    timeZone?: string;
}

/**
 * Check if a given object implements the GetNetworkMyip200Response interface.
 */
export function instanceOfGetNetworkMyip200Response(value: object): value is GetNetworkMyip200Response {
    return true;
}

export function GetNetworkMyip200ResponseFromJSON(json: any): GetNetworkMyip200Response {
    return GetNetworkMyip200ResponseFromJSONTyped(json, false);
}

export function GetNetworkMyip200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetNetworkMyip200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'asn': json['asn'] == null ? undefined : json['asn'],
        'beginip': json['beginip'] == null ? undefined : json['beginip'],
        'district': json['district'] == null ? undefined : json['district'],
        'endip': json['endip'] == null ? undefined : json['endip'],
        'ip': json['ip'] == null ? undefined : json['ip'],
        'isp': json['isp'] == null ? undefined : json['isp'],
        'latitude': json['latitude'] == null ? undefined : json['latitude'],
        'llc': json['llc'] == null ? undefined : json['llc'],
        'longitude': json['longitude'] == null ? undefined : json['longitude'],
        'region': json['region'] == null ? undefined : json['region'],
        'timeZone': json['time_zone'] == null ? undefined : json['time_zone'],
    };
}

export function GetNetworkMyip200ResponseToJSON(json: any): GetNetworkMyip200Response {
    return GetNetworkMyip200ResponseToJSONTyped(json, false);
}

export function GetNetworkMyip200ResponseToJSONTyped(value?: GetNetworkMyip200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'asn': value['asn'],
        'beginip': value['beginip'],
        'district': value['district'],
        'endip': value['endip'],
        'ip': value['ip'],
        'isp': value['isp'],
        'latitude': value['latitude'],
        'llc': value['llc'],
        'longitude': value['longitude'],
        'region': value['region'],
        'time_zone': value['timeZone'],
    };
}

