/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetRandomImage404Response
 */
export interface GetRandomImage404Response {
    /**
     * 
     * @type {string}
     * @memberof GetRandomImage404Response
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof GetRandomImage404Response
     */
    message?: string;
}

/**
 * Check if a given object implements the GetRandomImage404Response interface.
 */
export function instanceOfGetRandomImage404Response(value: object): value is GetRandomImage404Response {
    return true;
}

export function GetRandomImage404ResponseFromJSON(json: any): GetRandomImage404Response {
    return GetRandomImage404ResponseFromJSONTyped(json, false);
}

export function GetRandomImage404ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetRandomImage404Response {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function GetRandomImage404ResponseToJSON(json: any): GetRandomImage404Response {
    return GetRandomImage404ResponseToJSONTyped(json, false);
}

export function GetRandomImage404ResponseToJSONTyped(value?: GetRandomImage404Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
    };
}

