/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetSocialBilibiliArchives200ResponseVideosInner } from './GetSocialBilibiliArchives200ResponseVideosInner';
import {
    GetSocialBilibiliArchives200ResponseVideosInnerFromJSON,
    GetSocialBilibiliArchives200ResponseVideosInnerFromJSONTyped,
    GetSocialBilibiliArchives200ResponseVideosInnerToJSON,
    GetSocialBilibiliArchives200ResponseVideosInnerToJSONTyped,
} from './GetSocialBilibiliArchives200ResponseVideosInner';

/**
 * 
 * @export
 * @interface GetSocialBilibiliArchives200Response
 */
export interface GetSocialBilibiliArchives200Response {
    /**
     * 总稿件数
     * @type {number}
     * @memberof GetSocialBilibiliArchives200Response
     */
    total?: number;
    /**
     * 当前页码
     * @type {number}
     * @memberof GetSocialBilibiliArchives200Response
     */
    page?: number;
    /**
     * 每页数量
     * @type {number}
     * @memberof GetSocialBilibiliArchives200Response
     */
    size?: number;
    /**
     * 视频列表
     * @type {Array<GetSocialBilibiliArchives200ResponseVideosInner>}
     * @memberof GetSocialBilibiliArchives200Response
     */
    videos?: Array<GetSocialBilibiliArchives200ResponseVideosInner>;
}

/**
 * Check if a given object implements the GetSocialBilibiliArchives200Response interface.
 */
export function instanceOfGetSocialBilibiliArchives200Response(value: object): value is GetSocialBilibiliArchives200Response {
    return true;
}

export function GetSocialBilibiliArchives200ResponseFromJSON(json: any): GetSocialBilibiliArchives200Response {
    return GetSocialBilibiliArchives200ResponseFromJSONTyped(json, false);
}

export function GetSocialBilibiliArchives200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSocialBilibiliArchives200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'] == null ? undefined : json['total'],
        'page': json['page'] == null ? undefined : json['page'],
        'size': json['size'] == null ? undefined : json['size'],
        'videos': json['videos'] == null ? undefined : ((json['videos'] as Array<any>).map(GetSocialBilibiliArchives200ResponseVideosInnerFromJSON)),
    };
}

export function GetSocialBilibiliArchives200ResponseToJSON(json: any): GetSocialBilibiliArchives200Response {
    return GetSocialBilibiliArchives200ResponseToJSONTyped(json, false);
}

export function GetSocialBilibiliArchives200ResponseToJSONTyped(value?: GetSocialBilibiliArchives200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'page': value['page'],
        'size': value['size'],
        'videos': value['videos'] == null ? undefined : ((value['videos'] as Array<any>).map(GetSocialBilibiliArchives200ResponseVideosInnerToJSON)),
    };
}

