/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 该分P的视频分辨率。
 * @export
 * @interface GetSocialBilibiliVideoinfo200ResponsePagesInnerDimension
 */
export interface GetSocialBilibiliVideoinfo200ResponsePagesInnerDimension {
    /**
     * 宽度。
     * @type {number}
     * @memberof GetSocialBilibiliVideoinfo200ResponsePagesInnerDimension
     */
    width?: number;
    /**
     * 高度。
     * @type {number}
     * @memberof GetSocialBilibiliVideoinfo200ResponsePagesInnerDimension
     */
    height?: number;
    /**
     * 旋转角度。
     * @type {number}
     * @memberof GetSocialBilibiliVideoinfo200ResponsePagesInnerDimension
     */
    rotate?: number;
}

/**
 * Check if a given object implements the GetSocialBilibiliVideoinfo200ResponsePagesInnerDimension interface.
 */
export function instanceOfGetSocialBilibiliVideoinfo200ResponsePagesInnerDimension(value: object): value is GetSocialBilibiliVideoinfo200ResponsePagesInnerDimension {
    return true;
}

export function GetSocialBilibiliVideoinfo200ResponsePagesInnerDimensionFromJSON(json: any): GetSocialBilibiliVideoinfo200ResponsePagesInnerDimension {
    return GetSocialBilibiliVideoinfo200ResponsePagesInnerDimensionFromJSONTyped(json, false);
}

export function GetSocialBilibiliVideoinfo200ResponsePagesInnerDimensionFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSocialBilibiliVideoinfo200ResponsePagesInnerDimension {
    if (json == null) {
        return json;
    }
    return {
        
        'width': json['width'] == null ? undefined : json['width'],
        'height': json['height'] == null ? undefined : json['height'],
        'rotate': json['rotate'] == null ? undefined : json['rotate'],
    };
}

export function GetSocialBilibiliVideoinfo200ResponsePagesInnerDimensionToJSON(json: any): GetSocialBilibiliVideoinfo200ResponsePagesInnerDimension {
    return GetSocialBilibiliVideoinfo200ResponsePagesInnerDimensionToJSONTyped(json, false);
}

export function GetSocialBilibiliVideoinfo200ResponsePagesInnerDimensionToJSONTyped(value?: GetSocialBilibiliVideoinfo200ResponsePagesInnerDimension | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'width': value['width'],
        'height': value['height'],
        'rotate': value['rotate'],
    };
}

