/* tslint:disable */
/* eslint-disable */
/**
 * UAPI OpenAPI
 * Generated from UAPI JSON. Code is the interactive documentation: rich descriptions, examples, and x-extensions preserved.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetSayingRandom404Response
 */
export interface GetSayingRandom404Response {
    /**
     * 
     * @type {string}
     * @memberof GetSayingRandom404Response
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof GetSayingRandom404Response
     */
    message?: string;
}

/**
 * Check if a given object implements the GetSayingRandom404Response interface.
 */
export function instanceOfGetSayingRandom404Response(value: object): value is GetSayingRandom404Response {
    return true;
}

export function GetSayingRandom404ResponseFromJSON(json: any): GetSayingRandom404Response {
    return GetSayingRandom404ResponseFromJSONTyped(json, false);
}

export function GetSayingRandom404ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSayingRandom404Response {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function GetSayingRandom404ResponseToJSON(json: any): GetSayingRandom404Response {
    return GetSayingRandom404ResponseToJSONTyped(json, false);
}

export function GetSayingRandom404ResponseToJSONTyped(value?: GetSayingRandom404Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
    };
}

