/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetSocialQqUserinfo200Response
 */
export interface GetSocialQqUserinfo200Response {
    /**
     * QQ号
     * @type {string}
     * @memberof GetSocialQqUserinfo200Response
     */
    qq?: string;
    /**
     * 用户昵称
     * @type {string}
     * @memberof GetSocialQqUserinfo200Response
     */
    nickname?: string;
    /**
     * 个性签名
     * @type {string}
     * @memberof GetSocialQqUserinfo200Response
     */
    longNick?: string;
    /**
     * 头像URL
     * @type {string}
     * @memberof GetSocialQqUserinfo200Response
     */
    avatarUrl?: string;
    /**
     * 年龄
     * @type {number}
     * @memberof GetSocialQqUserinfo200Response
     */
    age?: number;
    /**
     * 性别
     * @type {string}
     * @memberof GetSocialQqUserinfo200Response
     */
    sex?: string;
    /**
     * QQ个性域名
     * @type {string}
     * @memberof GetSocialQqUserinfo200Response
     */
    qid?: string;
    /**
     * QQ等级
     * @type {number}
     * @memberof GetSocialQqUserinfo200Response
     */
    qqLevel?: number;
    /**
     * 地理位置（省市）
     * @type {string}
     * @memberof GetSocialQqUserinfo200Response
     */
    location?: string;
    /**
     * QQ邮箱
     * @type {string}
     * @memberof GetSocialQqUserinfo200Response
     */
    email?: string;
    /**
     * 是否为VIP用户
     * @type {boolean}
     * @memberof GetSocialQqUserinfo200Response
     */
    isVip?: boolean;
    /**
     * VIP等级
     * @type {number}
     * @memberof GetSocialQqUserinfo200Response
     */
    vipLevel?: number;
    /**
     * 注册时间（ISO 8601格式）
     * @type {string}
     * @memberof GetSocialQqUserinfo200Response
     */
    regTime?: string;
    /**
     * 最后更新时间（ISO 8601格式）
     * @type {string}
     * @memberof GetSocialQqUserinfo200Response
     */
    lastUpdated?: string;
}

/**
 * Check if a given object implements the GetSocialQqUserinfo200Response interface.
 */
export function instanceOfGetSocialQqUserinfo200Response(value: object): value is GetSocialQqUserinfo200Response {
    return true;
}

export function GetSocialQqUserinfo200ResponseFromJSON(json: any): GetSocialQqUserinfo200Response {
    return GetSocialQqUserinfo200ResponseFromJSONTyped(json, false);
}

export function GetSocialQqUserinfo200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSocialQqUserinfo200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'qq': json['qq'] == null ? undefined : json['qq'],
        'nickname': json['nickname'] == null ? undefined : json['nickname'],
        'longNick': json['long_nick'] == null ? undefined : json['long_nick'],
        'avatarUrl': json['avatar_url'] == null ? undefined : json['avatar_url'],
        'age': json['age'] == null ? undefined : json['age'],
        'sex': json['sex'] == null ? undefined : json['sex'],
        'qid': json['qid'] == null ? undefined : json['qid'],
        'qqLevel': json['qq_level'] == null ? undefined : json['qq_level'],
        'location': json['location'] == null ? undefined : json['location'],
        'email': json['email'] == null ? undefined : json['email'],
        'isVip': json['is_vip'] == null ? undefined : json['is_vip'],
        'vipLevel': json['vip_level'] == null ? undefined : json['vip_level'],
        'regTime': json['reg_time'] == null ? undefined : json['reg_time'],
        'lastUpdated': json['last_updated'] == null ? undefined : json['last_updated'],
    };
}

export function GetSocialQqUserinfo200ResponseToJSON(json: any): GetSocialQqUserinfo200Response {
    return GetSocialQqUserinfo200ResponseToJSONTyped(json, false);
}

export function GetSocialQqUserinfo200ResponseToJSONTyped(value?: GetSocialQqUserinfo200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'qq': value['qq'],
        'nickname': value['nickname'],
        'long_nick': value['longNick'],
        'avatar_url': value['avatarUrl'],
        'age': value['age'],
        'sex': value['sex'],
        'qid': value['qid'],
        'qq_level': value['qqLevel'],
        'location': value['location'],
        'email': value['email'],
        'is_vip': value['isVip'],
        'vip_level': value['vipLevel'],
        'reg_time': value['regTime'],
        'last_updated': value['lastUpdated'],
    };
}

