/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetStatusRatelimit401Response
 */
export interface GetStatusRatelimit401Response {
    /**
     * 
     * @type {string}
     * @memberof GetStatusRatelimit401Response
     */
    code?: string;
    /**
     * 
     * @type {object}
     * @memberof GetStatusRatelimit401Response
     */
    details?: object;
    /**
     * 
     * @type {string}
     * @memberof GetStatusRatelimit401Response
     */
    message?: string;
}

/**
 * Check if a given object implements the GetStatusRatelimit401Response interface.
 */
export function instanceOfGetStatusRatelimit401Response(value: object): value is GetStatusRatelimit401Response {
    return true;
}

export function GetStatusRatelimit401ResponseFromJSON(json: any): GetStatusRatelimit401Response {
    return GetStatusRatelimit401ResponseFromJSONTyped(json, false);
}

export function GetStatusRatelimit401ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetStatusRatelimit401Response {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'details': json['details'] == null ? undefined : json['details'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function GetStatusRatelimit401ResponseToJSON(json: any): GetStatusRatelimit401Response {
    return GetStatusRatelimit401ResponseToJSONTyped(json, false);
}

export function GetStatusRatelimit401ResponseToJSONTyped(value?: GetStatusRatelimit401Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'details': value['details'],
        'message': value['message'],
    };
}

