/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetSocialBilibiliVideoinfo200ResponseStaffInner
 */
export interface GetSocialBilibiliVideoinfo200ResponseStaffInner {
    /**
     * 成员 UID。
     * @type {number}
     * @memberof GetSocialBilibiliVideoinfo200ResponseStaffInner
     */
    mid?: number;
    /**
     * 成员角色标题。
     * @type {string}
     * @memberof GetSocialBilibiliVideoinfo200ResponseStaffInner
     */
    title?: string;
    /**
     * 成员昵称。
     * @type {string}
     * @memberof GetSocialBilibiliVideoinfo200ResponseStaffInner
     */
    name?: string;
    /**
     * 成员头像链接。
     * @type {string}
     * @memberof GetSocialBilibiliVideoinfo200ResponseStaffInner
     */
    face?: string;
    /**
     * 成员粉丝数。
     * @type {number}
     * @memberof GetSocialBilibiliVideoinfo200ResponseStaffInner
     */
    follower?: number;
}

/**
 * Check if a given object implements the GetSocialBilibiliVideoinfo200ResponseStaffInner interface.
 */
export function instanceOfGetSocialBilibiliVideoinfo200ResponseStaffInner(value: object): value is GetSocialBilibiliVideoinfo200ResponseStaffInner {
    return true;
}

export function GetSocialBilibiliVideoinfo200ResponseStaffInnerFromJSON(json: any): GetSocialBilibiliVideoinfo200ResponseStaffInner {
    return GetSocialBilibiliVideoinfo200ResponseStaffInnerFromJSONTyped(json, false);
}

export function GetSocialBilibiliVideoinfo200ResponseStaffInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSocialBilibiliVideoinfo200ResponseStaffInner {
    if (json == null) {
        return json;
    }
    return {
        
        'mid': json['mid'] == null ? undefined : json['mid'],
        'title': json['title'] == null ? undefined : json['title'],
        'name': json['name'] == null ? undefined : json['name'],
        'face': json['face'] == null ? undefined : json['face'],
        'follower': json['follower'] == null ? undefined : json['follower'],
    };
}

export function GetSocialBilibiliVideoinfo200ResponseStaffInnerToJSON(json: any): GetSocialBilibiliVideoinfo200ResponseStaffInner {
    return GetSocialBilibiliVideoinfo200ResponseStaffInnerToJSONTyped(json, false);
}

export function GetSocialBilibiliVideoinfo200ResponseStaffInnerToJSONTyped(value?: GetSocialBilibiliVideoinfo200ResponseStaffInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mid': value['mid'],
        'title': value['title'],
        'name': value['name'],
        'face': value['face'],
        'follower': value['follower'],
    };
}

