/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EndpointsAggregateUnaggregated } from './EndpointsAggregateUnaggregated';
import {
    EndpointsAggregateUnaggregatedFromJSON,
    EndpointsAggregateUnaggregatedFromJSONTyped,
    EndpointsAggregateUnaggregatedToJSON,
    EndpointsAggregateUnaggregatedToJSONTyped,
} from './EndpointsAggregateUnaggregated';
import type { SingleEndpoint } from './SingleEndpoint';
import {
    SingleEndpointFromJSON,
    SingleEndpointFromJSONTyped,
    SingleEndpointToJSON,
    SingleEndpointToJSONTyped,
} from './SingleEndpoint';
import type { EndpointsAggregate } from './EndpointsAggregate';
import {
    EndpointsAggregateFromJSON,
    EndpointsAggregateFromJSONTyped,
    EndpointsAggregateToJSON,
    EndpointsAggregateToJSONTyped,
} from './EndpointsAggregate';
import type { EndpointsAggregateEndpointsInner } from './EndpointsAggregateEndpointsInner';
import {
    EndpointsAggregateEndpointsInnerFromJSON,
    EndpointsAggregateEndpointsInnerFromJSONTyped,
    EndpointsAggregateEndpointsInnerToJSON,
    EndpointsAggregateEndpointsInnerToJSONTyped,
} from './EndpointsAggregateEndpointsInner';

/**
 * 
 * @export
 * @interface GetStatusUsage200Response
 */
export interface GetStatusUsage200Response {
    /**
     * 
     * @type {Array<EndpointsAggregateEndpointsInner>}
     * @memberof GetStatusUsage200Response
     */
    endpoints?: Array<EndpointsAggregateEndpointsInner>;
    /**
     * 
     * @type {EndpointsAggregateUnaggregated}
     * @memberof GetStatusUsage200Response
     */
    unaggregated?: EndpointsAggregateUnaggregated;
    /**
     * 
     * @type {string}
     * @memberof GetStatusUsage200Response
     */
    path?: string;
    /**
     * 
     * @type {number}
     * @memberof GetStatusUsage200Response
     */
    count?: number;
}

/**
 * Check if a given object implements the GetStatusUsage200Response interface.
 */
export function instanceOfGetStatusUsage200Response(value: object): value is GetStatusUsage200Response {
    return true;
}

export function GetStatusUsage200ResponseFromJSON(json: any): GetStatusUsage200Response {
    return GetStatusUsage200ResponseFromJSONTyped(json, false);
}

export function GetStatusUsage200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetStatusUsage200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'endpoints': json['endpoints'] == null ? undefined : ((json['endpoints'] as Array<any>).map(EndpointsAggregateEndpointsInnerFromJSON)),
        'unaggregated': json['unaggregated'] == null ? undefined : EndpointsAggregateUnaggregatedFromJSON(json['unaggregated']),
        'path': json['path'] == null ? undefined : json['path'],
        'count': json['count'] == null ? undefined : json['count'],
    };
}

export function GetStatusUsage200ResponseToJSON(json: any): GetStatusUsage200Response {
    return GetStatusUsage200ResponseToJSONTyped(json, false);
}

export function GetStatusUsage200ResponseToJSONTyped(value?: GetStatusUsage200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'endpoints': value['endpoints'] == null ? undefined : ((value['endpoints'] as Array<any>).map(EndpointsAggregateEndpointsInnerToJSON)),
        'unaggregated': EndpointsAggregateUnaggregatedToJSON(value['unaggregated']),
        'path': value['path'],
        'count': value['count'],
    };
}

