/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 查询指定path参数时返回的单个端点统计数据
 * @export
 * @interface GetStatusUsage200ResponseAnyOf1
 */
export interface GetStatusUsage200ResponseAnyOf1 {
    /**
     * 
     * @type {string}
     * @memberof GetStatusUsage200ResponseAnyOf1
     */
    path?: string;
    /**
     * 
     * @type {number}
     * @memberof GetStatusUsage200ResponseAnyOf1
     */
    count?: number;
}

/**
 * Check if a given object implements the GetStatusUsage200ResponseAnyOf1 interface.
 */
export function instanceOfGetStatusUsage200ResponseAnyOf1(value: object): value is GetStatusUsage200ResponseAnyOf1 {
    return true;
}

export function GetStatusUsage200ResponseAnyOf1FromJSON(json: any): GetStatusUsage200ResponseAnyOf1 {
    return GetStatusUsage200ResponseAnyOf1FromJSONTyped(json, false);
}

export function GetStatusUsage200ResponseAnyOf1FromJSONTyped(json: any, ignoreDiscriminator: boolean): GetStatusUsage200ResponseAnyOf1 {
    if (json == null) {
        return json;
    }
    return {
        
        'path': json['path'] == null ? undefined : json['path'],
        'count': json['count'] == null ? undefined : json['count'],
    };
}

export function GetStatusUsage200ResponseAnyOf1ToJSON(json: any): GetStatusUsage200ResponseAnyOf1 {
    return GetStatusUsage200ResponseAnyOf1ToJSONTyped(json, false);
}

export function GetStatusUsage200ResponseAnyOf1ToJSONTyped(value?: GetStatusUsage200ResponseAnyOf1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'path': value['path'],
        'count': value['count'],
    };
}

