/* tslint:disable */
/* eslint-disable */
/**
 * UAPI OpenAPI
 * Generated from UAPI JSON. Code is the interactive documentation: rich descriptions, examples, and x-extensions preserved.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetSocialBilibiliArchives200ResponseVideosInner
 */
export interface GetSocialBilibiliArchives200ResponseVideosInner {
    /**
     * 视频AID
     * @type {number}
     * @memberof GetSocialBilibiliArchives200ResponseVideosInner
     */
    aid?: number;
    /**
     * BV号
     * @type {string}
     * @memberof GetSocialBilibiliArchives200ResponseVideosInner
     */
    bvid?: string;
    /**
     * 封面URL
     * @type {string}
     * @memberof GetSocialBilibiliArchives200ResponseVideosInner
     */
    cover?: string;
    /**
     * 创建时间戳
     * @type {number}
     * @memberof GetSocialBilibiliArchives200ResponseVideosInner
     */
    createTime?: number;
    /**
     * 时长(秒)
     * @type {number}
     * @memberof GetSocialBilibiliArchives200ResponseVideosInner
     */
    duration?: number;
    /**
     * 是否为互动视频
     * @type {boolean}
     * @memberof GetSocialBilibiliArchives200ResponseVideosInner
     */
    isInteractive?: boolean;
    /**
     * 是否付费视频。0=免费，1=付费
     * @type {number}
     * @memberof GetSocialBilibiliArchives200ResponseVideosInner
     */
    isUgcPay?: number;
    /**
     * 播放量
     * @type {number}
     * @memberof GetSocialBilibiliArchives200ResponseVideosInner
     */
    playCount?: number;
    /**
     * 发布时间戳
     * @type {number}
     * @memberof GetSocialBilibiliArchives200ResponseVideosInner
     */
    publishTime?: number;
    /**
     * 视频状态
     * @type {number}
     * @memberof GetSocialBilibiliArchives200ResponseVideosInner
     */
    state?: number;
    /**
     * 标题
     * @type {string}
     * @memberof GetSocialBilibiliArchives200ResponseVideosInner
     */
    title?: string;
}

/**
 * Check if a given object implements the GetSocialBilibiliArchives200ResponseVideosInner interface.
 */
export function instanceOfGetSocialBilibiliArchives200ResponseVideosInner(value: object): value is GetSocialBilibiliArchives200ResponseVideosInner {
    return true;
}

export function GetSocialBilibiliArchives200ResponseVideosInnerFromJSON(json: any): GetSocialBilibiliArchives200ResponseVideosInner {
    return GetSocialBilibiliArchives200ResponseVideosInnerFromJSONTyped(json, false);
}

export function GetSocialBilibiliArchives200ResponseVideosInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSocialBilibiliArchives200ResponseVideosInner {
    if (json == null) {
        return json;
    }
    return {
        
        'aid': json['aid'] == null ? undefined : json['aid'],
        'bvid': json['bvid'] == null ? undefined : json['bvid'],
        'cover': json['cover'] == null ? undefined : json['cover'],
        'createTime': json['create_time'] == null ? undefined : json['create_time'],
        'duration': json['duration'] == null ? undefined : json['duration'],
        'isInteractive': json['is_interactive'] == null ? undefined : json['is_interactive'],
        'isUgcPay': json['is_ugc_pay'] == null ? undefined : json['is_ugc_pay'],
        'playCount': json['play_count'] == null ? undefined : json['play_count'],
        'publishTime': json['publish_time'] == null ? undefined : json['publish_time'],
        'state': json['state'] == null ? undefined : json['state'],
        'title': json['title'] == null ? undefined : json['title'],
    };
}

export function GetSocialBilibiliArchives200ResponseVideosInnerToJSON(json: any): GetSocialBilibiliArchives200ResponseVideosInner {
    return GetSocialBilibiliArchives200ResponseVideosInnerToJSONTyped(json, false);
}

export function GetSocialBilibiliArchives200ResponseVideosInnerToJSONTyped(value?: GetSocialBilibiliArchives200ResponseVideosInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'aid': value['aid'],
        'bvid': value['bvid'],
        'cover': value['cover'],
        'create_time': value['createTime'],
        'duration': value['duration'],
        'is_interactive': value['isInteractive'],
        'is_ugc_pay': value['isUgcPay'],
        'play_count': value['playCount'],
        'publish_time': value['publishTime'],
        'state': value['state'],
        'title': value['title'],
    };
}

