/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetSocialBilibiliVideoinfo200ResponseSubtitleListInnerAuthor } from './GetSocialBilibiliVideoinfo200ResponseSubtitleListInnerAuthor';
import {
    GetSocialBilibiliVideoinfo200ResponseSubtitleListInnerAuthorFromJSON,
    GetSocialBilibiliVideoinfo200ResponseSubtitleListInnerAuthorFromJSONTyped,
    GetSocialBilibiliVideoinfo200ResponseSubtitleListInnerAuthorToJSON,
    GetSocialBilibiliVideoinfo200ResponseSubtitleListInnerAuthorToJSONTyped,
} from './GetSocialBilibiliVideoinfo200ResponseSubtitleListInnerAuthor';

/**
 * 
 * @export
 * @interface GetSocialBilibiliVideoinfo200ResponseSubtitleListInner
 */
export interface GetSocialBilibiliVideoinfo200ResponseSubtitleListInner {
    /**
     * 字幕 ID。
     * @type {number}
     * @memberof GetSocialBilibiliVideoinfo200ResponseSubtitleListInner
     */
    id?: number;
    /**
     * 语言代码。
     * @type {string}
     * @memberof GetSocialBilibiliVideoinfo200ResponseSubtitleListInner
     */
    lan?: string;
    /**
     * 语言名称。
     * @type {string}
     * @memberof GetSocialBilibiliVideoinfo200ResponseSubtitleListInner
     */
    lanDoc?: string;
    /**
     * 是否锁定。
     * @type {boolean}
     * @memberof GetSocialBilibiliVideoinfo200ResponseSubtitleListInner
     */
    isLock?: boolean;
    /**
     * 字幕作者 UID。
     * @type {number}
     * @memberof GetSocialBilibiliVideoinfo200ResponseSubtitleListInner
     */
    authorMid?: number;
    /**
     * 字幕文件链接。
     * @type {string}
     * @memberof GetSocialBilibiliVideoinfo200ResponseSubtitleListInner
     */
    subtitleUrl?: string;
    /**
     * 
     * @type {GetSocialBilibiliVideoinfo200ResponseSubtitleListInnerAuthor}
     * @memberof GetSocialBilibiliVideoinfo200ResponseSubtitleListInner
     */
    author?: GetSocialBilibiliVideoinfo200ResponseSubtitleListInnerAuthor;
}

/**
 * Check if a given object implements the GetSocialBilibiliVideoinfo200ResponseSubtitleListInner interface.
 */
export function instanceOfGetSocialBilibiliVideoinfo200ResponseSubtitleListInner(value: object): value is GetSocialBilibiliVideoinfo200ResponseSubtitleListInner {
    return true;
}

export function GetSocialBilibiliVideoinfo200ResponseSubtitleListInnerFromJSON(json: any): GetSocialBilibiliVideoinfo200ResponseSubtitleListInner {
    return GetSocialBilibiliVideoinfo200ResponseSubtitleListInnerFromJSONTyped(json, false);
}

export function GetSocialBilibiliVideoinfo200ResponseSubtitleListInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSocialBilibiliVideoinfo200ResponseSubtitleListInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'lan': json['lan'] == null ? undefined : json['lan'],
        'lanDoc': json['lan_doc'] == null ? undefined : json['lan_doc'],
        'isLock': json['is_lock'] == null ? undefined : json['is_lock'],
        'authorMid': json['author_mid'] == null ? undefined : json['author_mid'],
        'subtitleUrl': json['subtitle_url'] == null ? undefined : json['subtitle_url'],
        'author': json['author'] == null ? undefined : GetSocialBilibiliVideoinfo200ResponseSubtitleListInnerAuthorFromJSON(json['author']),
    };
}

export function GetSocialBilibiliVideoinfo200ResponseSubtitleListInnerToJSON(json: any): GetSocialBilibiliVideoinfo200ResponseSubtitleListInner {
    return GetSocialBilibiliVideoinfo200ResponseSubtitleListInnerToJSONTyped(json, false);
}

export function GetSocialBilibiliVideoinfo200ResponseSubtitleListInnerToJSONTyped(value?: GetSocialBilibiliVideoinfo200ResponseSubtitleListInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'lan': value['lan'],
        'lan_doc': value['lanDoc'],
        'is_lock': value['isLock'],
        'author_mid': value['authorMid'],
        'subtitle_url': value['subtitleUrl'],
        'author': GetSocialBilibiliVideoinfo200ResponseSubtitleListInnerAuthorToJSON(value['author']),
    };
}

