/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetSearchEngines200ResponseLimits } from './GetSearchEngines200ResponseLimits';
import {
    GetSearchEngines200ResponseLimitsFromJSON,
    GetSearchEngines200ResponseLimitsFromJSONTyped,
    GetSearchEngines200ResponseLimitsToJSON,
    GetSearchEngines200ResponseLimitsToJSONTyped,
} from './GetSearchEngines200ResponseLimits';
import type { GetSearchEngines200ResponseEngine } from './GetSearchEngines200ResponseEngine';
import {
    GetSearchEngines200ResponseEngineFromJSON,
    GetSearchEngines200ResponseEngineFromJSONTyped,
    GetSearchEngines200ResponseEngineToJSON,
    GetSearchEngines200ResponseEngineToJSONTyped,
} from './GetSearchEngines200ResponseEngine';

/**
 * 
 * @export
 * @interface GetSearchEngines200Response
 */
export interface GetSearchEngines200Response {
    /**
     * 
     * @type {GetSearchEngines200ResponseEngine}
     * @memberof GetSearchEngines200Response
     */
    engine?: GetSearchEngines200ResponseEngine;
    /**
     * 
     * @type {GetSearchEngines200ResponseLimits}
     * @memberof GetSearchEngines200Response
     */
    limits?: GetSearchEngines200ResponseLimits;
    /**
     * 支持的所有参数说明列表
     * @type {Array<string>}
     * @memberof GetSearchEngines200Response
     */
    supportedParameters?: Array<string>;
}

/**
 * Check if a given object implements the GetSearchEngines200Response interface.
 */
export function instanceOfGetSearchEngines200Response(value: object): value is GetSearchEngines200Response {
    return true;
}

export function GetSearchEngines200ResponseFromJSON(json: any): GetSearchEngines200Response {
    return GetSearchEngines200ResponseFromJSONTyped(json, false);
}

export function GetSearchEngines200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSearchEngines200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'engine': json['engine'] == null ? undefined : GetSearchEngines200ResponseEngineFromJSON(json['engine']),
        'limits': json['limits'] == null ? undefined : GetSearchEngines200ResponseLimitsFromJSON(json['limits']),
        'supportedParameters': json['supported_parameters'] == null ? undefined : json['supported_parameters'],
    };
}

export function GetSearchEngines200ResponseToJSON(json: any): GetSearchEngines200Response {
    return GetSearchEngines200ResponseToJSONTyped(json, false);
}

export function GetSearchEngines200ResponseToJSONTyped(value?: GetSearchEngines200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'engine': GetSearchEngines200ResponseEngineToJSON(value['engine']),
        'limits': GetSearchEngines200ResponseLimitsToJSON(value['limits']),
        'supported_parameters': value['supportedParameters'],
    };
}

