/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetSaying200Response
 */
export interface GetSaying200Response {
    /**
     * 随机获取到的名言或诗词内容。
     * @type {string}
     * @memberof GetSaying200Response
     */
    text?: string;
}

/**
 * Check if a given object implements the GetSaying200Response interface.
 */
export function instanceOfGetSaying200Response(value: object): value is GetSaying200Response {
    return true;
}

export function GetSaying200ResponseFromJSON(json: any): GetSaying200Response {
    return GetSaying200ResponseFromJSONTyped(json, false);
}

export function GetSaying200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSaying200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'] == null ? undefined : json['text'],
    };
}

export function GetSaying200ResponseToJSON(json: any): GetSaying200Response {
    return GetSaying200ResponseToJSONTyped(json, false);
}

export function GetSaying200ResponseToJSONTyped(value?: GetSaying200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text': value['text'],
    };
}

