/* tslint:disable */
/* eslint-disable */
/**
 * UAPI OpenAPI
 * Generated from UAPI JSON. Code is the interactive documentation: rich descriptions, examples, and x-extensions preserved.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetSocialBilibiliUserinfo200Response
 */
export interface GetSocialBilibiliUserinfo200Response {
    /**
     * 
     * @type {number}
     * @memberof GetSocialBilibiliUserinfo200Response
     */
    archiveCount?: number;
    /**
     * 
     * @type {number}
     * @memberof GetSocialBilibiliUserinfo200Response
     */
    articleCount?: number;
    /**
     * 
     * @type {string}
     * @memberof GetSocialBilibiliUserinfo200Response
     */
    birthday?: string;
    /**
     * 
     * @type {string}
     * @memberof GetSocialBilibiliUserinfo200Response
     */
    face?: string;
    /**
     * 
     * @type {number}
     * @memberof GetSocialBilibiliUserinfo200Response
     */
    follower?: number;
    /**
     * 
     * @type {number}
     * @memberof GetSocialBilibiliUserinfo200Response
     */
    following?: number;
    /**
     * 
     * @type {number}
     * @memberof GetSocialBilibiliUserinfo200Response
     */
    level?: number;
    /**
     * 
     * @type {number}
     * @memberof GetSocialBilibiliUserinfo200Response
     */
    mid?: number;
    /**
     * 
     * @type {string}
     * @memberof GetSocialBilibiliUserinfo200Response
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof GetSocialBilibiliUserinfo200Response
     */
    sex?: string;
    /**
     * 
     * @type {string}
     * @memberof GetSocialBilibiliUserinfo200Response
     */
    sign?: string;
    /**
     * 
     * @type {number}
     * @memberof GetSocialBilibiliUserinfo200Response
     */
    vipStatus?: number;
    /**
     * 
     * @type {number}
     * @memberof GetSocialBilibiliUserinfo200Response
     */
    vipType?: number;
}

/**
 * Check if a given object implements the GetSocialBilibiliUserinfo200Response interface.
 */
export function instanceOfGetSocialBilibiliUserinfo200Response(value: object): value is GetSocialBilibiliUserinfo200Response {
    return true;
}

export function GetSocialBilibiliUserinfo200ResponseFromJSON(json: any): GetSocialBilibiliUserinfo200Response {
    return GetSocialBilibiliUserinfo200ResponseFromJSONTyped(json, false);
}

export function GetSocialBilibiliUserinfo200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSocialBilibiliUserinfo200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'archiveCount': json['archive_count'] == null ? undefined : json['archive_count'],
        'articleCount': json['article_count'] == null ? undefined : json['article_count'],
        'birthday': json['birthday'] == null ? undefined : json['birthday'],
        'face': json['face'] == null ? undefined : json['face'],
        'follower': json['follower'] == null ? undefined : json['follower'],
        'following': json['following'] == null ? undefined : json['following'],
        'level': json['level'] == null ? undefined : json['level'],
        'mid': json['mid'] == null ? undefined : json['mid'],
        'name': json['name'] == null ? undefined : json['name'],
        'sex': json['sex'] == null ? undefined : json['sex'],
        'sign': json['sign'] == null ? undefined : json['sign'],
        'vipStatus': json['vip_status'] == null ? undefined : json['vip_status'],
        'vipType': json['vip_type'] == null ? undefined : json['vip_type'],
    };
}

export function GetSocialBilibiliUserinfo200ResponseToJSON(json: any): GetSocialBilibiliUserinfo200Response {
    return GetSocialBilibiliUserinfo200ResponseToJSONTyped(json, false);
}

export function GetSocialBilibiliUserinfo200ResponseToJSONTyped(value?: GetSocialBilibiliUserinfo200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'archive_count': value['archiveCount'],
        'article_count': value['articleCount'],
        'birthday': value['birthday'],
        'face': value['face'],
        'follower': value['follower'],
        'following': value['following'],
        'level': value['level'],
        'mid': value['mid'],
        'name': value['name'],
        'sex': value['sex'],
        'sign': value['sign'],
        'vip_status': value['vipStatus'],
        'vip_type': value['vipType'],
    };
}

