/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetSocialBilibiliVideoinfo200ResponseDescV2Inner
 */
export interface GetSocialBilibiliVideoinfo200ResponseDescV2Inner {
    /**
     * 简介文本。
     * @type {string}
     * @memberof GetSocialBilibiliVideoinfo200ResponseDescV2Inner
     */
    rawText?: string;
    /**
     * 片段类型。
     * @type {number}
     * @memberof GetSocialBilibiliVideoinfo200ResponseDescV2Inner
     */
    type?: number;
    /**
     * 业务 ID，被关联对象的 ID。
     * @type {number}
     * @memberof GetSocialBilibiliVideoinfo200ResponseDescV2Inner
     */
    bizId?: number;
}

/**
 * Check if a given object implements the GetSocialBilibiliVideoinfo200ResponseDescV2Inner interface.
 */
export function instanceOfGetSocialBilibiliVideoinfo200ResponseDescV2Inner(value: object): value is GetSocialBilibiliVideoinfo200ResponseDescV2Inner {
    return true;
}

export function GetSocialBilibiliVideoinfo200ResponseDescV2InnerFromJSON(json: any): GetSocialBilibiliVideoinfo200ResponseDescV2Inner {
    return GetSocialBilibiliVideoinfo200ResponseDescV2InnerFromJSONTyped(json, false);
}

export function GetSocialBilibiliVideoinfo200ResponseDescV2InnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSocialBilibiliVideoinfo200ResponseDescV2Inner {
    if (json == null) {
        return json;
    }
    return {
        
        'rawText': json['raw_text'] == null ? undefined : json['raw_text'],
        'type': json['type'] == null ? undefined : json['type'],
        'bizId': json['biz_id'] == null ? undefined : json['biz_id'],
    };
}

export function GetSocialBilibiliVideoinfo200ResponseDescV2InnerToJSON(json: any): GetSocialBilibiliVideoinfo200ResponseDescV2Inner {
    return GetSocialBilibiliVideoinfo200ResponseDescV2InnerToJSONTyped(json, false);
}

export function GetSocialBilibiliVideoinfo200ResponseDescV2InnerToJSONTyped(value?: GetSocialBilibiliVideoinfo200ResponseDescV2Inner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'raw_text': value['rawText'],
        'type': value['type'],
        'biz_id': value['bizId'],
    };
}

