/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetStatusUsage200ResponseAnyOf1 } from './GetStatusUsage200ResponseAnyOf1';
import {
    GetStatusUsage200ResponseAnyOf1FromJSON,
    GetStatusUsage200ResponseAnyOf1FromJSONTyped,
    GetStatusUsage200ResponseAnyOf1ToJSON,
    GetStatusUsage200ResponseAnyOf1ToJSONTyped,
} from './GetStatusUsage200ResponseAnyOf1';
import type { GetStatusUsage200ResponseAnyOfEndpointsInner } from './GetStatusUsage200ResponseAnyOfEndpointsInner';
import {
    GetStatusUsage200ResponseAnyOfEndpointsInnerFromJSON,
    GetStatusUsage200ResponseAnyOfEndpointsInnerFromJSONTyped,
    GetStatusUsage200ResponseAnyOfEndpointsInnerToJSON,
    GetStatusUsage200ResponseAnyOfEndpointsInnerToJSONTyped,
} from './GetStatusUsage200ResponseAnyOfEndpointsInner';
import type { GetStatusUsage200ResponseAnyOf } from './GetStatusUsage200ResponseAnyOf';
import {
    GetStatusUsage200ResponseAnyOfFromJSON,
    GetStatusUsage200ResponseAnyOfFromJSONTyped,
    GetStatusUsage200ResponseAnyOfToJSON,
    GetStatusUsage200ResponseAnyOfToJSONTyped,
} from './GetStatusUsage200ResponseAnyOf';
import type { GetStatusUsage200ResponseAnyOfUnaggregated } from './GetStatusUsage200ResponseAnyOfUnaggregated';
import {
    GetStatusUsage200ResponseAnyOfUnaggregatedFromJSON,
    GetStatusUsage200ResponseAnyOfUnaggregatedFromJSONTyped,
    GetStatusUsage200ResponseAnyOfUnaggregatedToJSON,
    GetStatusUsage200ResponseAnyOfUnaggregatedToJSONTyped,
} from './GetStatusUsage200ResponseAnyOfUnaggregated';

/**
 * 
 * @export
 * @interface GetStatusUsage200Response
 */
export interface GetStatusUsage200Response {
    /**
     * 
     * @type {Array<GetStatusUsage200ResponseAnyOfEndpointsInner>}
     * @memberof GetStatusUsage200Response
     */
    endpoints?: Array<GetStatusUsage200ResponseAnyOfEndpointsInner>;
    /**
     * 
     * @type {GetStatusUsage200ResponseAnyOfUnaggregated}
     * @memberof GetStatusUsage200Response
     */
    unaggregated?: GetStatusUsage200ResponseAnyOfUnaggregated;
    /**
     * 
     * @type {string}
     * @memberof GetStatusUsage200Response
     */
    path?: string;
    /**
     * 
     * @type {number}
     * @memberof GetStatusUsage200Response
     */
    count?: number;
}

/**
 * Check if a given object implements the GetStatusUsage200Response interface.
 */
export function instanceOfGetStatusUsage200Response(value: object): value is GetStatusUsage200Response {
    return true;
}

export function GetStatusUsage200ResponseFromJSON(json: any): GetStatusUsage200Response {
    return GetStatusUsage200ResponseFromJSONTyped(json, false);
}

export function GetStatusUsage200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetStatusUsage200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'endpoints': json['endpoints'] == null ? undefined : ((json['endpoints'] as Array<any>).map(GetStatusUsage200ResponseAnyOfEndpointsInnerFromJSON)),
        'unaggregated': json['unaggregated'] == null ? undefined : GetStatusUsage200ResponseAnyOfUnaggregatedFromJSON(json['unaggregated']),
        'path': json['path'] == null ? undefined : json['path'],
        'count': json['count'] == null ? undefined : json['count'],
    };
}

export function GetStatusUsage200ResponseToJSON(json: any): GetStatusUsage200Response {
    return GetStatusUsage200ResponseToJSONTyped(json, false);
}

export function GetStatusUsage200ResponseToJSONTyped(value?: GetStatusUsage200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'endpoints': value['endpoints'] == null ? undefined : ((value['endpoints'] as Array<any>).map(GetStatusUsage200ResponseAnyOfEndpointsInnerToJSON)),
        'unaggregated': GetStatusUsage200ResponseAnyOfUnaggregatedToJSON(value['unaggregated']),
        'path': value['path'],
        'count': value['count'],
    };
}

