/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetStatusUsage200ResponseAnyOfEndpointsInner
 */
export interface GetStatusUsage200ResponseAnyOfEndpointsInner {
    /**
     * 
     * @type {string}
     * @memberof GetStatusUsage200ResponseAnyOfEndpointsInner
     */
    path?: string;
    /**
     * 
     * @type {number}
     * @memberof GetStatusUsage200ResponseAnyOfEndpointsInner
     */
    count?: number;
}

/**
 * Check if a given object implements the GetStatusUsage200ResponseAnyOfEndpointsInner interface.
 */
export function instanceOfGetStatusUsage200ResponseAnyOfEndpointsInner(value: object): value is GetStatusUsage200ResponseAnyOfEndpointsInner {
    return true;
}

export function GetStatusUsage200ResponseAnyOfEndpointsInnerFromJSON(json: any): GetStatusUsage200ResponseAnyOfEndpointsInner {
    return GetStatusUsage200ResponseAnyOfEndpointsInnerFromJSONTyped(json, false);
}

export function GetStatusUsage200ResponseAnyOfEndpointsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetStatusUsage200ResponseAnyOfEndpointsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'path': json['path'] == null ? undefined : json['path'],
        'count': json['count'] == null ? undefined : json['count'],
    };
}

export function GetStatusUsage200ResponseAnyOfEndpointsInnerToJSON(json: any): GetStatusUsage200ResponseAnyOfEndpointsInner {
    return GetStatusUsage200ResponseAnyOfEndpointsInnerToJSONTyped(json, false);
}

export function GetStatusUsage200ResponseAnyOfEndpointsInnerToJSONTyped(value?: GetStatusUsage200ResponseAnyOfEndpointsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'path': value['path'],
        'count': value['count'],
    };
}

