/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetSocialQqGroupinfo500Response
 */
export interface GetSocialQqGroupinfo500Response {
    /**
     * 
     * @type {string}
     * @memberof GetSocialQqGroupinfo500Response
     */
    code?: string;
    /**
     * 
     * @type {object}
     * @memberof GetSocialQqGroupinfo500Response
     */
    details?: object;
    /**
     * 
     * @type {string}
     * @memberof GetSocialQqGroupinfo500Response
     */
    message?: string;
}

/**
 * Check if a given object implements the GetSocialQqGroupinfo500Response interface.
 */
export function instanceOfGetSocialQqGroupinfo500Response(value: object): value is GetSocialQqGroupinfo500Response {
    return true;
}

export function GetSocialQqGroupinfo500ResponseFromJSON(json: any): GetSocialQqGroupinfo500Response {
    return GetSocialQqGroupinfo500ResponseFromJSONTyped(json, false);
}

export function GetSocialQqGroupinfo500ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSocialQqGroupinfo500Response {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'details': json['details'] == null ? undefined : json['details'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function GetSocialQqGroupinfo500ResponseToJSON(json: any): GetSocialQqGroupinfo500Response {
    return GetSocialQqGroupinfo500ResponseToJSONTyped(json, false);
}

export function GetSocialQqGroupinfo500ResponseToJSONTyped(value?: GetSocialQqGroupinfo500Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'details': value['details'],
        'message': value['message'],
    };
}

