/* tslint:disable */
/* eslint-disable */
/**
 * UAPI OpenAPI
 * Generated from UAPI JSON. Code is the interactive documentation: rich descriptions, examples, and x-extensions preserved.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetSocialBilibiliLiveroom200ResponseNewPendants } from './GetSocialBilibiliLiveroom200ResponseNewPendants';
import {
    GetSocialBilibiliLiveroom200ResponseNewPendantsFromJSON,
    GetSocialBilibiliLiveroom200ResponseNewPendantsFromJSONTyped,
    GetSocialBilibiliLiveroom200ResponseNewPendantsToJSON,
    GetSocialBilibiliLiveroom200ResponseNewPendantsToJSONTyped,
} from './GetSocialBilibiliLiveroom200ResponseNewPendants';

/**
 * 
 * @export
 * @interface GetSocialBilibiliLiveroom200Response
 */
export interface GetSocialBilibiliLiveroom200Response {
    /**
     * 分区ID。
     * @type {number}
     * @memberof GetSocialBilibiliLiveroom200Response
     */
    areaId?: number;
    /**
     * 子分区名称。
     * @type {string}
     * @memberof GetSocialBilibiliLiveroom200Response
     */
    areaName?: string;
    /**
     * 主播的粉丝数（关注数量）。
     * @type {number}
     * @memberof GetSocialBilibiliLiveroom200Response
     */
    attention?: number;
    /**
     * 直播间背景图的URL。
     * @type {string}
     * @memberof GetSocialBilibiliLiveroom200Response
     */
    background?: string;
    /**
     * 直播间公告或描述，支持换行符。
     * @type {string}
     * @memberof GetSocialBilibiliLiveroom200Response
     */
    description?: string;
    /**
     * 直播间热词列表，通常用于弹幕互动。
     * @type {Array<string>}
     * @memberof GetSocialBilibiliLiveroom200Response
     */
    hotWords?: Array<string>;
    /**
     * 是否为竖屏直播。
     * @type {boolean}
     * @memberof GetSocialBilibiliLiveroom200Response
     */
    isPortrait?: boolean;
    /**
     * 关键帧封面图链接。
     * @type {string}
     * @memberof GetSocialBilibiliLiveroom200Response
     */
    keyframe?: string;
    /**
     * 直播状态。0:未开播, 1:直播中, 2:轮播中。
     * @type {number}
     * @memberof GetSocialBilibiliLiveroom200Response
     */
    liveStatus?: number;
    /**
     * 本次直播开始的时间，格式为 `YYYY-MM-DD HH:mm:ss`。如果未开播，则为空字符串。
     * @type {string}
     * @memberof GetSocialBilibiliLiveroom200Response
     */
    liveTime?: string;
    /**
     * 
     * @type {GetSocialBilibiliLiveroom200ResponseNewPendants}
     * @memberof GetSocialBilibiliLiveroom200Response
     */
    newPendants?: GetSocialBilibiliLiveroom200ResponseNewPendants | null;
    /**
     * 直播间当前的人气值（对应你文档里的 PopularValue，不代表真实在线人数）。
     * @type {number}
     * @memberof GetSocialBilibiliLiveroom200Response
     */
    online?: number;
    /**
     * 父分区 ID。
     * @type {number}
     * @memberof GetSocialBilibiliLiveroom200Response
     */
    parentAreaId?: number;
    /**
     * 父分区名称。
     * @type {string}
     * @memberof GetSocialBilibiliLiveroom200Response
     */
    parentAreaName?: string;
    /**
     * 直播间的真实房间号（长号）。
     * @type {number}
     * @memberof GetSocialBilibiliLiveroom200Response
     */
    roomId?: number;
    /**
     * 直播间的短号（靓号）。如果没有设置，则为0。
     * @type {number}
     * @memberof GetSocialBilibiliLiveroom200Response
     */
    shortId?: number;
    /**
     * 直播间设置的标签，以逗号分隔。
     * @type {string}
     * @memberof GetSocialBilibiliLiveroom200Response
     */
    tags?: string;
    /**
     * 当前直播间的标题。
     * @type {string}
     * @memberof GetSocialBilibiliLiveroom200Response
     */
    title?: string;
    /**
     * 主播的用户ID (mid)。
     * @type {number}
     * @memberof GetSocialBilibiliLiveroom200Response
     */
    uid?: number;
    /**
     * 用户设置的直播间封面URL。
     * @type {string}
     * @memberof GetSocialBilibiliLiveroom200Response
     */
    userCover?: string;
}

/**
 * Check if a given object implements the GetSocialBilibiliLiveroom200Response interface.
 */
export function instanceOfGetSocialBilibiliLiveroom200Response(value: object): value is GetSocialBilibiliLiveroom200Response {
    return true;
}

export function GetSocialBilibiliLiveroom200ResponseFromJSON(json: any): GetSocialBilibiliLiveroom200Response {
    return GetSocialBilibiliLiveroom200ResponseFromJSONTyped(json, false);
}

export function GetSocialBilibiliLiveroom200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSocialBilibiliLiveroom200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'areaId': json['area_id'] == null ? undefined : json['area_id'],
        'areaName': json['area_name'] == null ? undefined : json['area_name'],
        'attention': json['attention'] == null ? undefined : json['attention'],
        'background': json['background'] == null ? undefined : json['background'],
        'description': json['description'] == null ? undefined : json['description'],
        'hotWords': json['hot_words'] == null ? undefined : json['hot_words'],
        'isPortrait': json['is_portrait'] == null ? undefined : json['is_portrait'],
        'keyframe': json['keyframe'] == null ? undefined : json['keyframe'],
        'liveStatus': json['live_status'] == null ? undefined : json['live_status'],
        'liveTime': json['live_time'] == null ? undefined : json['live_time'],
        'newPendants': json['new_pendants'] == null ? undefined : GetSocialBilibiliLiveroom200ResponseNewPendantsFromJSON(json['new_pendants']),
        'online': json['online'] == null ? undefined : json['online'],
        'parentAreaId': json['parent_area_id'] == null ? undefined : json['parent_area_id'],
        'parentAreaName': json['parent_area_name'] == null ? undefined : json['parent_area_name'],
        'roomId': json['room_id'] == null ? undefined : json['room_id'],
        'shortId': json['short_id'] == null ? undefined : json['short_id'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'title': json['title'] == null ? undefined : json['title'],
        'uid': json['uid'] == null ? undefined : json['uid'],
        'userCover': json['user_cover'] == null ? undefined : json['user_cover'],
    };
}

export function GetSocialBilibiliLiveroom200ResponseToJSON(json: any): GetSocialBilibiliLiveroom200Response {
    return GetSocialBilibiliLiveroom200ResponseToJSONTyped(json, false);
}

export function GetSocialBilibiliLiveroom200ResponseToJSONTyped(value?: GetSocialBilibiliLiveroom200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'area_id': value['areaId'],
        'area_name': value['areaName'],
        'attention': value['attention'],
        'background': value['background'],
        'description': value['description'],
        'hot_words': value['hotWords'],
        'is_portrait': value['isPortrait'],
        'keyframe': value['keyframe'],
        'live_status': value['liveStatus'],
        'live_time': value['liveTime'],
        'new_pendants': GetSocialBilibiliLiveroom200ResponseNewPendantsToJSON(value['newPendants']),
        'online': value['online'],
        'parent_area_id': value['parentAreaId'],
        'parent_area_name': value['parentAreaName'],
        'room_id': value['roomId'],
        'short_id': value['shortId'],
        'tags': value['tags'],
        'title': value['title'],
        'uid': value['uid'],
        'user_cover': value['userCover'],
    };
}

