/* tslint:disable */
/* eslint-disable */
/**
 * UAPI OpenAPI
 * Generated from UAPI JSON. Code is the interactive documentation: rich descriptions, examples, and x-extensions preserved.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 分页信息概览。
 * @export
 * @interface GetSocialBilibiliReplies200ResponsePage
 */
export interface GetSocialBilibiliReplies200ResponsePage {
    /**
     * 评论区总评论数，包含了所有的楼中楼回复。
     * @type {number}
     * @memberof GetSocialBilibiliReplies200ResponsePage
     */
    acount?: number;
    /**
     * 根评论（即直接评论视频的评论）的总数。
     * @type {number}
     * @memberof GetSocialBilibiliReplies200ResponsePage
     */
    count?: number;
    /**
     * 当前所在的页码。
     * @type {number}
     * @memberof GetSocialBilibiliReplies200ResponsePage
     */
    num?: number;
    /**
     * 每页的项数。
     * @type {number}
     * @memberof GetSocialBilibiliReplies200ResponsePage
     */
    size?: number;
}

/**
 * Check if a given object implements the GetSocialBilibiliReplies200ResponsePage interface.
 */
export function instanceOfGetSocialBilibiliReplies200ResponsePage(value: object): value is GetSocialBilibiliReplies200ResponsePage {
    return true;
}

export function GetSocialBilibiliReplies200ResponsePageFromJSON(json: any): GetSocialBilibiliReplies200ResponsePage {
    return GetSocialBilibiliReplies200ResponsePageFromJSONTyped(json, false);
}

export function GetSocialBilibiliReplies200ResponsePageFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSocialBilibiliReplies200ResponsePage {
    if (json == null) {
        return json;
    }
    return {
        
        'acount': json['acount'] == null ? undefined : json['acount'],
        'count': json['count'] == null ? undefined : json['count'],
        'num': json['num'] == null ? undefined : json['num'],
        'size': json['size'] == null ? undefined : json['size'],
    };
}

export function GetSocialBilibiliReplies200ResponsePageToJSON(json: any): GetSocialBilibiliReplies200ResponsePage {
    return GetSocialBilibiliReplies200ResponsePageToJSONTyped(json, false);
}

export function GetSocialBilibiliReplies200ResponsePageToJSONTyped(value?: GetSocialBilibiliReplies200ResponsePage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'acount': value['acount'],
        'count': value['count'],
        'num': value['num'],
        'size': value['size'],
    };
}

