/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetWebparseExtractimages200Response
 */
export interface GetWebparseExtractimages200Response {
    /**
     * 
     * @type {number}
     * @memberof GetWebparseExtractimages200Response
     */
    count?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof GetWebparseExtractimages200Response
     */
    images?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof GetWebparseExtractimages200Response
     */
    url?: string;
}

/**
 * Check if a given object implements the GetWebparseExtractimages200Response interface.
 */
export function instanceOfGetWebparseExtractimages200Response(value: object): value is GetWebparseExtractimages200Response {
    return true;
}

export function GetWebparseExtractimages200ResponseFromJSON(json: any): GetWebparseExtractimages200Response {
    return GetWebparseExtractimages200ResponseFromJSONTyped(json, false);
}

export function GetWebparseExtractimages200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetWebparseExtractimages200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'] == null ? undefined : json['count'],
        'images': json['images'] == null ? undefined : json['images'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function GetWebparseExtractimages200ResponseToJSON(json: any): GetWebparseExtractimages200Response {
    return GetWebparseExtractimages200ResponseToJSONTyped(json, false);
}

export function GetWebparseExtractimages200ResponseToJSONTyped(value?: GetWebparseExtractimages200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'images': value['images'],
        'url': value['url'],
    };
}

