/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetWebTomarkdownAsyncStatus200ResponseAnyOf2Result
 */
export interface GetWebTomarkdownAsyncStatus200ResponseAnyOf2Result {
    /**
     * 
     * @type {string}
     * @memberof GetWebTomarkdownAsyncStatus200ResponseAnyOf2Result
     */
    markdown?: string;
    /**
     * 
     * @type {number}
     * @memberof GetWebTomarkdownAsyncStatus200ResponseAnyOf2Result
     */
    size?: number;
}

/**
 * Check if a given object implements the GetWebTomarkdownAsyncStatus200ResponseAnyOf2Result interface.
 */
export function instanceOfGetWebTomarkdownAsyncStatus200ResponseAnyOf2Result(value: object): value is GetWebTomarkdownAsyncStatus200ResponseAnyOf2Result {
    return true;
}

export function GetWebTomarkdownAsyncStatus200ResponseAnyOf2ResultFromJSON(json: any): GetWebTomarkdownAsyncStatus200ResponseAnyOf2Result {
    return GetWebTomarkdownAsyncStatus200ResponseAnyOf2ResultFromJSONTyped(json, false);
}

export function GetWebTomarkdownAsyncStatus200ResponseAnyOf2ResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetWebTomarkdownAsyncStatus200ResponseAnyOf2Result {
    if (json == null) {
        return json;
    }
    return {
        
        'markdown': json['markdown'] == null ? undefined : json['markdown'],
        'size': json['size'] == null ? undefined : json['size'],
    };
}

export function GetWebTomarkdownAsyncStatus200ResponseAnyOf2ResultToJSON(json: any): GetWebTomarkdownAsyncStatus200ResponseAnyOf2Result {
    return GetWebTomarkdownAsyncStatus200ResponseAnyOf2ResultToJSONTyped(json, false);
}

export function GetWebTomarkdownAsyncStatus200ResponseAnyOf2ResultToJSONTyped(value?: GetWebTomarkdownAsyncStatus200ResponseAnyOf2Result | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'markdown': value['markdown'],
        'size': value['size'],
    };
}

