/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetWebparseExtractimages200Response
 */
export interface GetWebparseExtractimages200Response {
    /**
     * 实际解析的网页地址。
     * @type {string}
     * @memberof GetWebparseExtractimages200Response
     */
    pageUrl?: string;
    /**
     * 页面中提取到的图片链接列表。
     * @type {Array<string>}
     * @memberof GetWebparseExtractimages200Response
     */
    imageUrls?: Array<string>;
}

/**
 * Check if a given object implements the GetWebparseExtractimages200Response interface.
 */
export function instanceOfGetWebparseExtractimages200Response(value: object): value is GetWebparseExtractimages200Response {
    return true;
}

export function GetWebparseExtractimages200ResponseFromJSON(json: any): GetWebparseExtractimages200Response {
    return GetWebparseExtractimages200ResponseFromJSONTyped(json, false);
}

export function GetWebparseExtractimages200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetWebparseExtractimages200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'pageUrl': json['page_url'] == null ? undefined : json['page_url'],
        'imageUrls': json['image_urls'] == null ? undefined : json['image_urls'],
    };
}

export function GetWebparseExtractimages200ResponseToJSON(json: any): GetWebparseExtractimages200Response {
    return GetWebparseExtractimages200ResponseToJSONTyped(json, false);
}

export function GetWebparseExtractimages200ResponseToJSONTyped(value?: GetWebparseExtractimages200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page_url': value['pageUrl'],
        'image_urls': value['imageUrls'],
    };
}

