/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HTML
 */
export interface HTML {
    /**
     * 
     * @type {string}
     * @memberof HTML
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof HTML
     */
    message?: string;
}

/**
 * Check if a given object implements the HTML interface.
 */
export function instanceOfHTML(value: object): value is HTML {
    return true;
}

export function HTMLFromJSON(json: any): HTML {
    return HTMLFromJSONTyped(json, false);
}

export function HTMLFromJSONTyped(json: any, ignoreDiscriminator: boolean): HTML {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function HTMLToJSON(json: any): HTML {
    return HTMLToJSONTyped(json, false);
}

export function HTMLToJSONTyped(value?: HTML | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
    };
}

