/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostSearchAggregate400Response
 */
export interface PostSearchAggregate400Response {
    /**
     * 
     * @type {string}
     * @memberof PostSearchAggregate400Response
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof PostSearchAggregate400Response
     */
    message?: string;
}

/**
 * Check if a given object implements the PostSearchAggregate400Response interface.
 */
export function instanceOfPostSearchAggregate400Response(value: object): value is PostSearchAggregate400Response {
    return true;
}

export function PostSearchAggregate400ResponseFromJSON(json: any): PostSearchAggregate400Response {
    return PostSearchAggregate400ResponseFromJSONTyped(json, false);
}

export function PostSearchAggregate400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostSearchAggregate400Response {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function PostSearchAggregate400ResponseToJSON(json: any): PostSearchAggregate400Response {
    return PostSearchAggregate400ResponseToJSONTyped(json, false);
}

export function PostSearchAggregate400ResponseToJSONTyped(value?: PostSearchAggregate400Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
    };
}

