/* tslint:disable */
/* eslint-disable */
/**
 * UAPI OpenAPI
 * Generated from UAPI JSON. Code is the interactive documentation: rich descriptions, examples, and x-extensions preserved.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostSearchAggregate200ResponseSourcesInner
 */
export interface PostSearchAggregate200ResponseSourcesInner {
    /**
     * 该搜索引擎的耗时（毫秒）
     * @type {number}
     * @memberof PostSearchAggregate200ResponseSourcesInner
     */
    elapsedMs?: number;
    /**
     * 该搜索源首条结果的域名
     * @type {string}
     * @memberof PostSearchAggregate200ResponseSourcesInner
     */
    firstResultHost?: string;
    /**
     * 搜索引擎版本
     * @type {string}
     * @memberof PostSearchAggregate200ResponseSourcesInner
     */
    name?: string;
    /**
     * 该搜索引擎返回的结果数
     * @type {number}
     * @memberof PostSearchAggregate200ResponseSourcesInner
     */
    resultCount?: number;
    /**
     * 本次搜索引擎调用状态
     * @type {string}
     * @memberof PostSearchAggregate200ResponseSourcesInner
     */
    status?: string;
}

/**
 * Check if a given object implements the PostSearchAggregate200ResponseSourcesInner interface.
 */
export function instanceOfPostSearchAggregate200ResponseSourcesInner(value: object): value is PostSearchAggregate200ResponseSourcesInner {
    return true;
}

export function PostSearchAggregate200ResponseSourcesInnerFromJSON(json: any): PostSearchAggregate200ResponseSourcesInner {
    return PostSearchAggregate200ResponseSourcesInnerFromJSONTyped(json, false);
}

export function PostSearchAggregate200ResponseSourcesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostSearchAggregate200ResponseSourcesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'elapsedMs': json['elapsed_ms'] == null ? undefined : json['elapsed_ms'],
        'firstResultHost': json['first_result_host'] == null ? undefined : json['first_result_host'],
        'name': json['name'] == null ? undefined : json['name'],
        'resultCount': json['result_count'] == null ? undefined : json['result_count'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function PostSearchAggregate200ResponseSourcesInnerToJSON(json: any): PostSearchAggregate200ResponseSourcesInner {
    return PostSearchAggregate200ResponseSourcesInnerToJSONTyped(json, false);
}

export function PostSearchAggregate200ResponseSourcesInnerToJSONTyped(value?: PostSearchAggregate200ResponseSourcesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'elapsed_ms': value['elapsedMs'],
        'first_result_host': value['firstResultHost'],
        'name': value['name'],
        'result_count': value['resultCount'],
        'status': value['status'],
    };
}

