/* tslint:disable */
/* eslint-disable */
/**
 * UAPI OpenAPI
 * Generated from UAPI JSON. Code is the interactive documentation: rich descriptions, examples, and x-extensions preserved.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostTextMarkdownToPdfRequest
 */
export interface PostTextMarkdownToPdfRequest {
    /**
     * PDF 的纸张大小。可选 `A4` 或 `Letter`，默认是 `A4`。
     * @type {string}
     * @memberof PostTextMarkdownToPdfRequest
     */
    paperSize?: PostTextMarkdownToPdfRequestPaperSizeEnum;
    /**
     * 原始 Markdown 字符串，最大不超过 1MB。
     * @type {string}
     * @memberof PostTextMarkdownToPdfRequest
     */
    text: string;
    /**
     * PDF 的排版主题。可选 `github`、`minimal`、`light`、`dark`，默认是 `github`。
     * @type {string}
     * @memberof PostTextMarkdownToPdfRequest
     */
    theme?: PostTextMarkdownToPdfRequestThemeEnum;
}


/**
 * @export
 */
export const PostTextMarkdownToPdfRequestPaperSizeEnum = {
    A4: 'A4',
    Letter: 'Letter'
} as const;
export type PostTextMarkdownToPdfRequestPaperSizeEnum = typeof PostTextMarkdownToPdfRequestPaperSizeEnum[keyof typeof PostTextMarkdownToPdfRequestPaperSizeEnum];

/**
 * @export
 */
export const PostTextMarkdownToPdfRequestThemeEnum = {
    Github: 'github',
    Minimal: 'minimal',
    Light: 'light',
    Dark: 'dark'
} as const;
export type PostTextMarkdownToPdfRequestThemeEnum = typeof PostTextMarkdownToPdfRequestThemeEnum[keyof typeof PostTextMarkdownToPdfRequestThemeEnum];


/**
 * Check if a given object implements the PostTextMarkdownToPdfRequest interface.
 */
export function instanceOfPostTextMarkdownToPdfRequest(value: object): value is PostTextMarkdownToPdfRequest {
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function PostTextMarkdownToPdfRequestFromJSON(json: any): PostTextMarkdownToPdfRequest {
    return PostTextMarkdownToPdfRequestFromJSONTyped(json, false);
}

export function PostTextMarkdownToPdfRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostTextMarkdownToPdfRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'paperSize': json['paper_size'] == null ? undefined : json['paper_size'],
        'text': json['text'],
        'theme': json['theme'] == null ? undefined : json['theme'],
    };
}

export function PostTextMarkdownToPdfRequestToJSON(json: any): PostTextMarkdownToPdfRequest {
    return PostTextMarkdownToPdfRequestToJSONTyped(json, false);
}

export function PostTextMarkdownToPdfRequestToJSONTyped(value?: PostTextMarkdownToPdfRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'paper_size': value['paperSize'],
        'text': value['text'],
        'theme': value['theme'],
    };
}

