/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostImageOcr503Response
 */
export interface PostImageOcr503Response {
    /**
     * 
     * @type {string}
     * @memberof PostImageOcr503Response
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof PostImageOcr503Response
     */
    message?: string;
}

/**
 * Check if a given object implements the PostImageOcr503Response interface.
 */
export function instanceOfPostImageOcr503Response(value: object): value is PostImageOcr503Response {
    return true;
}

export function PostImageOcr503ResponseFromJSON(json: any): PostImageOcr503Response {
    return PostImageOcr503ResponseFromJSONTyped(json, false);
}

export function PostImageOcr503ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostImageOcr503Response {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function PostImageOcr503ResponseToJSON(json: any): PostImageOcr503Response {
    return PostImageOcr503ResponseToJSONTyped(json, false);
}

export function PostImageOcr503ResponseToJSONTyped(value?: PostImageOcr503Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
    };
}

