/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostImageNsfw413Response
 */
export interface PostImageNsfw413Response {
    /**
     * 
     * @type {string}
     * @memberof PostImageNsfw413Response
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof PostImageNsfw413Response
     */
    message?: string;
}

/**
 * Check if a given object implements the PostImageNsfw413Response interface.
 */
export function instanceOfPostImageNsfw413Response(value: object): value is PostImageNsfw413Response {
    return true;
}

export function PostImageNsfw413ResponseFromJSON(json: any): PostImageNsfw413Response {
    return PostImageNsfw413ResponseFromJSONTyped(json, false);
}

export function PostImageNsfw413ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostImageNsfw413Response {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function PostImageNsfw413ResponseToJSON(json: any): PostImageNsfw413Response {
    return PostImageNsfw413ResponseToJSONTyped(json, false);
}

export function PostImageNsfw413ResponseToJSONTyped(value?: PostImageNsfw413Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
    };
}

