/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostTextMd5Request
 */
export interface PostTextMd5Request {
    /**
     * 需要计算哈希值的文本
     * @type {string}
     * @memberof PostTextMd5Request
     */
    text: string;
}

/**
 * Check if a given object implements the PostTextMd5Request interface.
 */
export function instanceOfPostTextMd5Request(value: object): value is PostTextMd5Request {
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function PostTextMd5RequestFromJSON(json: any): PostTextMd5Request {
    return PostTextMd5RequestFromJSONTyped(json, false);
}

export function PostTextMd5RequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostTextMd5Request {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'],
    };
}

export function PostTextMd5RequestToJSON(json: any): PostTextMd5Request {
    return PostTextMd5RequestToJSONTyped(json, false);
}

export function PostTextMd5RequestToJSONTyped(value?: PostTextMd5Request | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text': value['text'],
    };
}

