/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostTextMarkdownToHtml200ResponseData } from './PostTextMarkdownToHtml200ResponseData';
import {
    PostTextMarkdownToHtml200ResponseDataFromJSON,
    PostTextMarkdownToHtml200ResponseDataFromJSONTyped,
    PostTextMarkdownToHtml200ResponseDataToJSON,
    PostTextMarkdownToHtml200ResponseDataToJSONTyped,
} from './PostTextMarkdownToHtml200ResponseData';

/**
 * 
 * @export
 * @interface PostTextMarkdownToHtml200Response
 */
export interface PostTextMarkdownToHtml200Response {
    /**
     * 
     * @type {PostTextMarkdownToHtml200ResponseData}
     * @memberof PostTextMarkdownToHtml200Response
     */
    data?: PostTextMarkdownToHtml200ResponseData;
}

/**
 * Check if a given object implements the PostTextMarkdownToHtml200Response interface.
 */
export function instanceOfPostTextMarkdownToHtml200Response(value: object): value is PostTextMarkdownToHtml200Response {
    return true;
}

export function PostTextMarkdownToHtml200ResponseFromJSON(json: any): PostTextMarkdownToHtml200Response {
    return PostTextMarkdownToHtml200ResponseFromJSONTyped(json, false);
}

export function PostTextMarkdownToHtml200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostTextMarkdownToHtml200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : PostTextMarkdownToHtml200ResponseDataFromJSON(json['data']),
    };
}

export function PostTextMarkdownToHtml200ResponseToJSON(json: any): PostTextMarkdownToHtml200Response {
    return PostTextMarkdownToHtml200ResponseToJSONTyped(json, false);
}

export function PostTextMarkdownToHtml200ResponseToJSONTyped(value?: PostTextMarkdownToHtml200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': PostTextMarkdownToHtml200ResponseDataToJSON(value['data']),
    };
}

