/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostSensitiveWordQuickCheck200Response
 */
export interface PostSensitiveWordQuickCheck200Response {
    /**
     * 
     * @type {string}
     * @memberof PostSensitiveWordQuickCheck200Response
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof PostSensitiveWordQuickCheck200Response
     */
    originalText?: string;
    /**
     * 
     * @type {string}
     * @memberof PostSensitiveWordQuickCheck200Response
     */
    maskedText?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof PostSensitiveWordQuickCheck200Response
     */
    forbiddenWords?: Array<string>;
}

/**
 * Check if a given object implements the PostSensitiveWordQuickCheck200Response interface.
 */
export function instanceOfPostSensitiveWordQuickCheck200Response(value: object): value is PostSensitiveWordQuickCheck200Response {
    return true;
}

export function PostSensitiveWordQuickCheck200ResponseFromJSON(json: any): PostSensitiveWordQuickCheck200Response {
    return PostSensitiveWordQuickCheck200ResponseFromJSONTyped(json, false);
}

export function PostSensitiveWordQuickCheck200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostSensitiveWordQuickCheck200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'originalText': json['original_text'] == null ? undefined : json['original_text'],
        'maskedText': json['masked_text'] == null ? undefined : json['masked_text'],
        'forbiddenWords': json['forbidden_words'] == null ? undefined : json['forbidden_words'],
    };
}

export function PostSensitiveWordQuickCheck200ResponseToJSON(json: any): PostSensitiveWordQuickCheck200Response {
    return PostSensitiveWordQuickCheck200ResponseToJSONTyped(json, false);
}

export function PostSensitiveWordQuickCheck200ResponseToJSONTyped(value?: PostSensitiveWordQuickCheck200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'original_text': value['originalText'],
        'masked_text': value['maskedText'],
        'forbidden_words': value['forbiddenWords'],
    };
}

