/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostImageCompress400Response
 */
export interface PostImageCompress400Response {
    /**
     * 机器可读的错误代码。
     * @type {string}
     * @memberof PostImageCompress400Response
     */
    code?: string;
    /**
     * 人类可读的错误描述信息。
     * @type {string}
     * @memberof PostImageCompress400Response
     */
    message?: string;
}

/**
 * Check if a given object implements the PostImageCompress400Response interface.
 */
export function instanceOfPostImageCompress400Response(value: object): value is PostImageCompress400Response {
    return true;
}

export function PostImageCompress400ResponseFromJSON(json: any): PostImageCompress400Response {
    return PostImageCompress400ResponseFromJSONTyped(json, false);
}

export function PostImageCompress400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostImageCompress400Response {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function PostImageCompress400ResponseToJSON(json: any): PostImageCompress400Response {
    return PostImageCompress400ResponseToJSONTyped(json, false);
}

export function PostImageCompress400ResponseToJSONTyped(value?: PostImageCompress400Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
    };
}

