/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostMiscDateDiff400Response
 */
export interface PostMiscDateDiff400Response {
    /**
     * 
     * @type {string}
     * @memberof PostMiscDateDiff400Response
     */
    errorCode?: string;
    /**
     * 
     * @type {string}
     * @memberof PostMiscDateDiff400Response
     */
    errorMessage?: string;
    /**
     * 
     * @type {string}
     * @memberof PostMiscDateDiff400Response
     */
    errorDetails?: string;
}

/**
 * Check if a given object implements the PostMiscDateDiff400Response interface.
 */
export function instanceOfPostMiscDateDiff400Response(value: object): value is PostMiscDateDiff400Response {
    return true;
}

export function PostMiscDateDiff400ResponseFromJSON(json: any): PostMiscDateDiff400Response {
    return PostMiscDateDiff400ResponseFromJSONTyped(json, false);
}

export function PostMiscDateDiff400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostMiscDateDiff400Response {
    if (json == null) {
        return json;
    }
    return {
        
        'errorCode': json['error_code'] == null ? undefined : json['error_code'],
        'errorMessage': json['error_message'] == null ? undefined : json['error_message'],
        'errorDetails': json['error_details'] == null ? undefined : json['error_details'],
    };
}

export function PostMiscDateDiff400ResponseToJSON(json: any): PostMiscDateDiff400Response {
    return PostMiscDateDiff400ResponseToJSONTyped(json, false);
}

export function PostMiscDateDiff400ResponseToJSONTyped(value?: PostMiscDateDiff400Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error_code': value['errorCode'],
        'error_message': value['errorMessage'],
        'error_details': value['errorDetails'],
    };
}

