/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostTextConvertRequest
 */
export interface PostTextConvertRequest {
    /**
     * 待转换的文本内容
     * @type {string}
     * @memberof PostTextConvertRequest
     */
    text: string;
    /**
     * 源格式类型
     * @type {string}
     * @memberof PostTextConvertRequest
     */
    from: PostTextConvertRequestFromEnum;
    /**
     * 目标格式类型
     * @type {string}
     * @memberof PostTextConvertRequest
     */
    to: PostTextConvertRequestToEnum;
    /**
     * 可选参数（预留，当前未使用）
     * @type {{ [key: string]: any; }}
     * @memberof PostTextConvertRequest
     */
    options?: { [key: string]: any; };
}


/**
 * @export
 */
export const PostTextConvertRequestFromEnum = {
    Plain: 'plain',
    Base64: 'base64',
    Hex: 'hex',
    Url: 'url',
    Html: 'html',
    Unicode: 'unicode',
    Binary: 'binary',
    Md5: 'md5',
    Sha1: 'sha1',
    Sha256: 'sha256',
    Sha512: 'sha512'
} as const;
export type PostTextConvertRequestFromEnum = typeof PostTextConvertRequestFromEnum[keyof typeof PostTextConvertRequestFromEnum];

/**
 * @export
 */
export const PostTextConvertRequestToEnum = {
    Plain: 'plain',
    Base64: 'base64',
    Hex: 'hex',
    Url: 'url',
    Html: 'html',
    Unicode: 'unicode',
    Binary: 'binary',
    Md5: 'md5',
    Sha1: 'sha1',
    Sha256: 'sha256',
    Sha512: 'sha512'
} as const;
export type PostTextConvertRequestToEnum = typeof PostTextConvertRequestToEnum[keyof typeof PostTextConvertRequestToEnum];


/**
 * Check if a given object implements the PostTextConvertRequest interface.
 */
export function instanceOfPostTextConvertRequest(value: object): value is PostTextConvertRequest {
    if (!('text' in value) || value['text'] === undefined) return false;
    if (!('from' in value) || value['from'] === undefined) return false;
    if (!('to' in value) || value['to'] === undefined) return false;
    return true;
}

export function PostTextConvertRequestFromJSON(json: any): PostTextConvertRequest {
    return PostTextConvertRequestFromJSONTyped(json, false);
}

export function PostTextConvertRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostTextConvertRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'],
        'from': json['from'],
        'to': json['to'],
        'options': json['options'] == null ? undefined : json['options'],
    };
}

export function PostTextConvertRequestToJSON(json: any): PostTextConvertRequest {
    return PostTextConvertRequestToJSONTyped(json, false);
}

export function PostTextConvertRequestToJSONTyped(value?: PostTextConvertRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text': value['text'],
        'from': value['from'],
        'to': value['to'],
        'options': value['options'],
    };
}

