/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostAnswerbookAsk200Response
 */
export interface PostAnswerbookAsk200Response {
    /**
     * 
     * @type {string}
     * @memberof PostAnswerbookAsk200Response
     */
    question?: string;
    /**
     * 
     * @type {string}
     * @memberof PostAnswerbookAsk200Response
     */
    answer?: string;
}

/**
 * Check if a given object implements the PostAnswerbookAsk200Response interface.
 */
export function instanceOfPostAnswerbookAsk200Response(value: object): value is PostAnswerbookAsk200Response {
    return true;
}

export function PostAnswerbookAsk200ResponseFromJSON(json: any): PostAnswerbookAsk200Response {
    return PostAnswerbookAsk200ResponseFromJSONTyped(json, false);
}

export function PostAnswerbookAsk200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostAnswerbookAsk200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'question': json['question'] == null ? undefined : json['question'],
        'answer': json['answer'] == null ? undefined : json['answer'],
    };
}

export function PostAnswerbookAsk200ResponseToJSON(json: any): PostAnswerbookAsk200Response {
    return PostAnswerbookAsk200ResponseToJSONTyped(json, false);
}

export function PostAnswerbookAsk200ResponseToJSONTyped(value?: PostAnswerbookAsk200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'question': value['question'],
        'answer': value['answer'],
    };
}

