/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostTextMarkdownToPdf400ResponseOneOf3
 */
export interface PostTextMarkdownToPdf400ResponseOneOf3 {
    /**
     * 
     * @type {string}
     * @memberof PostTextMarkdownToPdf400ResponseOneOf3
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof PostTextMarkdownToPdf400ResponseOneOf3
     */
    message?: string;
}

/**
 * Check if a given object implements the PostTextMarkdownToPdf400ResponseOneOf3 interface.
 */
export function instanceOfPostTextMarkdownToPdf400ResponseOneOf3(value: object): value is PostTextMarkdownToPdf400ResponseOneOf3 {
    return true;
}

export function PostTextMarkdownToPdf400ResponseOneOf3FromJSON(json: any): PostTextMarkdownToPdf400ResponseOneOf3 {
    return PostTextMarkdownToPdf400ResponseOneOf3FromJSONTyped(json, false);
}

export function PostTextMarkdownToPdf400ResponseOneOf3FromJSONTyped(json: any, ignoreDiscriminator: boolean): PostTextMarkdownToPdf400ResponseOneOf3 {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function PostTextMarkdownToPdf400ResponseOneOf3ToJSON(json: any): PostTextMarkdownToPdf400ResponseOneOf3 {
    return PostTextMarkdownToPdf400ResponseOneOf3ToJSONTyped(json, false);
}

export function PostTextMarkdownToPdf400ResponseOneOf3ToJSONTyped(value?: PostTextMarkdownToPdf400ResponseOneOf3 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
    };
}

