/* tslint:disable */
/* eslint-disable */
/**
 * UAPI OpenAPI
 * Generated from UAPI JSON. Code is the interactive documentation: rich descriptions, examples, and x-extensions preserved.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostWatermarkLabel400Response
 */
export interface PostWatermarkLabel400Response {
    /**
     * 
     * @type {string}
     * @memberof PostWatermarkLabel400Response
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof PostWatermarkLabel400Response
     */
    message?: string;
}

/**
 * Check if a given object implements the PostWatermarkLabel400Response interface.
 */
export function instanceOfPostWatermarkLabel400Response(value: object): value is PostWatermarkLabel400Response {
    return true;
}

export function PostWatermarkLabel400ResponseFromJSON(json: any): PostWatermarkLabel400Response {
    return PostWatermarkLabel400ResponseFromJSONTyped(json, false);
}

export function PostWatermarkLabel400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostWatermarkLabel400Response {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function PostWatermarkLabel400ResponseToJSON(json: any): PostWatermarkLabel400Response {
    return PostWatermarkLabel400ResponseToJSONTyped(json, false);
}

export function PostWatermarkLabel400ResponseToJSONTyped(value?: PostWatermarkLabel400Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
    };
}

