/* tslint:disable */
/* eslint-disable */
/**
 * UAPI OpenAPI
 * Generated from UAPI JSON. Code is the interactive documentation: rich descriptions, examples, and x-extensions preserved.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostTranslateStream500Response
 */
export interface PostTranslateStream500Response {
    /**
     * 
     * @type {string}
     * @memberof PostTranslateStream500Response
     */
    code?: string;
    /**
     * 错误描述
     * @type {string}
     * @memberof PostTranslateStream500Response
     */
    error?: string;
}

/**
 * Check if a given object implements the PostTranslateStream500Response interface.
 */
export function instanceOfPostTranslateStream500Response(value: object): value is PostTranslateStream500Response {
    return true;
}

export function PostTranslateStream500ResponseFromJSON(json: any): PostTranslateStream500Response {
    return PostTranslateStream500ResponseFromJSONTyped(json, false);
}

export function PostTranslateStream500ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostTranslateStream500Response {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function PostTranslateStream500ResponseToJSON(json: any): PostTranslateStream500Response {
    return PostTranslateStream500ResponseToJSONTyped(json, false);
}

export function PostTranslateStream500ResponseToJSONTyped(value?: PostTranslateStream500Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'error': value['error'],
    };
}

