/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostImageSpeechlessRequest
 */
export interface PostImageSpeechlessRequest {
    /**
     * 表情包上方的文字内容。你们怎么不说话了，是不是都在偷偷 _______
     * @type {string}
     * @memberof PostImageSpeechlessRequest
     */
    topText?: string;
    /**
     * 表情包下方的文字内容。求求你_______
     * @type {string}
     * @memberof PostImageSpeechlessRequest
     */
    bottomText?: string;
}

/**
 * Check if a given object implements the PostImageSpeechlessRequest interface.
 */
export function instanceOfPostImageSpeechlessRequest(value: object): value is PostImageSpeechlessRequest {
    return true;
}

export function PostImageSpeechlessRequestFromJSON(json: any): PostImageSpeechlessRequest {
    return PostImageSpeechlessRequestFromJSONTyped(json, false);
}

export function PostImageSpeechlessRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostImageSpeechlessRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'topText': json['top_text'] == null ? undefined : json['top_text'],
        'bottomText': json['bottom_text'] == null ? undefined : json['bottom_text'],
    };
}

export function PostImageSpeechlessRequestToJSON(json: any): PostImageSpeechlessRequest {
    return PostImageSpeechlessRequestToJSONTyped(json, false);
}

export function PostImageSpeechlessRequestToJSONTyped(value?: PostImageSpeechlessRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'top_text': value['topText'],
        'bottom_text': value['bottomText'],
    };
}

