/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostTextAesEncryptAdvanced200Response
 */
export interface PostTextAesEncryptAdvanced200Response {
    /**
     * 加密后的密文（Base64编码）
     * @type {string}
     * @memberof PostTextAesEncryptAdvanced200Response
     */
    ciphertext?: string;
    /**
     * 使用的加密模式
     * @type {string}
     * @memberof PostTextAesEncryptAdvanced200Response
     */
    mode?: string;
    /**
     * 使用的填充方式
     * @type {string}
     * @memberof PostTextAesEncryptAdvanced200Response
     */
    padding?: string;
    /**
     * 使用的IV（Base64编码）。GCM模式不返回此字段
     * @type {string}
     * @memberof PostTextAesEncryptAdvanced200Response
     */
    iv?: string;
}

/**
 * Check if a given object implements the PostTextAesEncryptAdvanced200Response interface.
 */
export function instanceOfPostTextAesEncryptAdvanced200Response(value: object): value is PostTextAesEncryptAdvanced200Response {
    return true;
}

export function PostTextAesEncryptAdvanced200ResponseFromJSON(json: any): PostTextAesEncryptAdvanced200Response {
    return PostTextAesEncryptAdvanced200ResponseFromJSONTyped(json, false);
}

export function PostTextAesEncryptAdvanced200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostTextAesEncryptAdvanced200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'ciphertext': json['ciphertext'] == null ? undefined : json['ciphertext'],
        'mode': json['mode'] == null ? undefined : json['mode'],
        'padding': json['padding'] == null ? undefined : json['padding'],
        'iv': json['iv'] == null ? undefined : json['iv'],
    };
}

export function PostTextAesEncryptAdvanced200ResponseToJSON(json: any): PostTextAesEncryptAdvanced200Response {
    return PostTextAesEncryptAdvanced200ResponseToJSONTyped(json, false);
}

export function PostTextAesEncryptAdvanced200ResponseToJSONTyped(value?: PostTextAesEncryptAdvanced200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ciphertext': value['ciphertext'],
        'mode': value['mode'],
        'padding': value['padding'],
        'iv': value['iv'],
    };
}

