/* tslint:disable */
/* eslint-disable */
/**
 * UAPI OpenAPI
 * Generated from UAPI JSON. Code is the interactive documentation: rich descriptions, examples, and x-extensions preserved.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostSearchAggregate200ResponseMetadata } from './PostSearchAggregate200ResponseMetadata';
import {
    PostSearchAggregate200ResponseMetadataFromJSON,
    PostSearchAggregate200ResponseMetadataFromJSONTyped,
    PostSearchAggregate200ResponseMetadataToJSON,
    PostSearchAggregate200ResponseMetadataToJSONTyped,
} from './PostSearchAggregate200ResponseMetadata';
import type { PostSearchAggregate200ResponseSourcesInner } from './PostSearchAggregate200ResponseSourcesInner';
import {
    PostSearchAggregate200ResponseSourcesInnerFromJSON,
    PostSearchAggregate200ResponseSourcesInnerFromJSONTyped,
    PostSearchAggregate200ResponseSourcesInnerToJSON,
    PostSearchAggregate200ResponseSourcesInnerToJSONTyped,
} from './PostSearchAggregate200ResponseSourcesInner';
import type { PostSearchAggregate200ResponseResultsInner } from './PostSearchAggregate200ResponseResultsInner';
import {
    PostSearchAggregate200ResponseResultsInnerFromJSON,
    PostSearchAggregate200ResponseResultsInnerFromJSONTyped,
    PostSearchAggregate200ResponseResultsInnerToJSON,
    PostSearchAggregate200ResponseResultsInnerToJSONTyped,
} from './PostSearchAggregate200ResponseResultsInner';

/**
 * 
 * @export
 * @interface PostSearchAggregate200Response
 */
export interface PostSearchAggregate200Response {
    /**
     * 
     * @type {PostSearchAggregate200ResponseMetadata}
     * @memberof PostSearchAggregate200Response
     */
    metadata?: PostSearchAggregate200ResponseMetadata;
    /**
     * 本次请求总耗时（毫秒）
     * @type {number}
     * @memberof PostSearchAggregate200Response
     */
    processTimeMs?: number;
    /**
     * 执行的搜索查询
     * @type {string}
     * @memberof PostSearchAggregate200Response
     */
    query?: string;
    /**
     * 搜索结果列表
     * @type {Array<PostSearchAggregate200ResponseResultsInner>}
     * @memberof PostSearchAggregate200Response
     */
    results?: Array<PostSearchAggregate200ResponseResultsInner>;
    /**
     * 本次请求实际命中的搜索引擎信息
     * @type {Array<PostSearchAggregate200ResponseSourcesInner>}
     * @memberof PostSearchAggregate200Response
     */
    sources?: Array<PostSearchAggregate200ResponseSourcesInner>;
    /**
     * 返回的搜索结果总数
     * @type {number}
     * @memberof PostSearchAggregate200Response
     */
    totalResults?: number;
}

/**
 * Check if a given object implements the PostSearchAggregate200Response interface.
 */
export function instanceOfPostSearchAggregate200Response(value: object): value is PostSearchAggregate200Response {
    return true;
}

export function PostSearchAggregate200ResponseFromJSON(json: any): PostSearchAggregate200Response {
    return PostSearchAggregate200ResponseFromJSONTyped(json, false);
}

export function PostSearchAggregate200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostSearchAggregate200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'metadata': json['metadata'] == null ? undefined : PostSearchAggregate200ResponseMetadataFromJSON(json['metadata']),
        'processTimeMs': json['process_time_ms'] == null ? undefined : json['process_time_ms'],
        'query': json['query'] == null ? undefined : json['query'],
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(PostSearchAggregate200ResponseResultsInnerFromJSON)),
        'sources': json['sources'] == null ? undefined : ((json['sources'] as Array<any>).map(PostSearchAggregate200ResponseSourcesInnerFromJSON)),
        'totalResults': json['total_results'] == null ? undefined : json['total_results'],
    };
}

export function PostSearchAggregate200ResponseToJSON(json: any): PostSearchAggregate200Response {
    return PostSearchAggregate200ResponseToJSONTyped(json, false);
}

export function PostSearchAggregate200ResponseToJSONTyped(value?: PostSearchAggregate200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'metadata': PostSearchAggregate200ResponseMetadataToJSON(value['metadata']),
        'process_time_ms': value['processTimeMs'],
        'query': value['query'],
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(PostSearchAggregate200ResponseResultsInnerToJSON)),
        'sources': value['sources'] == null ? undefined : ((value['sources'] as Array<any>).map(PostSearchAggregate200ResponseSourcesInnerToJSON)),
        'total_results': value['totalResults'],
    };
}

