/* tslint:disable */
/* eslint-disable */
/**
 * UAPI OpenAPI
 * Generated from UAPI JSON. Code is the interactive documentation: rich descriptions, examples, and x-extensions preserved.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 当前文字片段的矩形坐标。只有在 `need_location=true` 时才会返回。
 * @export
 * @interface PostImageOcr200ResponseWordsResultInnerLocation
 */
export interface PostImageOcr200ResponseWordsResultInnerLocation {
    /**
     * 
     * @type {number}
     * @memberof PostImageOcr200ResponseWordsResultInnerLocation
     */
    height?: number;
    /**
     * 
     * @type {number}
     * @memberof PostImageOcr200ResponseWordsResultInnerLocation
     */
    left?: number;
    /**
     * 
     * @type {number}
     * @memberof PostImageOcr200ResponseWordsResultInnerLocation
     */
    top?: number;
    /**
     * 
     * @type {number}
     * @memberof PostImageOcr200ResponseWordsResultInnerLocation
     */
    width?: number;
}

/**
 * Check if a given object implements the PostImageOcr200ResponseWordsResultInnerLocation interface.
 */
export function instanceOfPostImageOcr200ResponseWordsResultInnerLocation(value: object): value is PostImageOcr200ResponseWordsResultInnerLocation {
    return true;
}

export function PostImageOcr200ResponseWordsResultInnerLocationFromJSON(json: any): PostImageOcr200ResponseWordsResultInnerLocation {
    return PostImageOcr200ResponseWordsResultInnerLocationFromJSONTyped(json, false);
}

export function PostImageOcr200ResponseWordsResultInnerLocationFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostImageOcr200ResponseWordsResultInnerLocation {
    if (json == null) {
        return json;
    }
    return {
        
        'height': json['height'] == null ? undefined : json['height'],
        'left': json['left'] == null ? undefined : json['left'],
        'top': json['top'] == null ? undefined : json['top'],
        'width': json['width'] == null ? undefined : json['width'],
    };
}

export function PostImageOcr200ResponseWordsResultInnerLocationToJSON(json: any): PostImageOcr200ResponseWordsResultInnerLocation {
    return PostImageOcr200ResponseWordsResultInnerLocationToJSONTyped(json, false);
}

export function PostImageOcr200ResponseWordsResultInnerLocationToJSONTyped(value?: PostImageOcr200ResponseWordsResultInnerLocation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'height': value['height'],
        'left': value['left'],
        'top': value['top'],
        'width': value['width'],
    };
}

