/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostImageOcr200ResponseWordsResultInnerVertexesLocationInner
 */
export interface PostImageOcr200ResponseWordsResultInnerVertexesLocationInner {
    /**
     * 
     * @type {number}
     * @memberof PostImageOcr200ResponseWordsResultInnerVertexesLocationInner
     */
    x?: number;
    /**
     * 
     * @type {number}
     * @memberof PostImageOcr200ResponseWordsResultInnerVertexesLocationInner
     */
    y?: number;
}

/**
 * Check if a given object implements the PostImageOcr200ResponseWordsResultInnerVertexesLocationInner interface.
 */
export function instanceOfPostImageOcr200ResponseWordsResultInnerVertexesLocationInner(value: object): value is PostImageOcr200ResponseWordsResultInnerVertexesLocationInner {
    return true;
}

export function PostImageOcr200ResponseWordsResultInnerVertexesLocationInnerFromJSON(json: any): PostImageOcr200ResponseWordsResultInnerVertexesLocationInner {
    return PostImageOcr200ResponseWordsResultInnerVertexesLocationInnerFromJSONTyped(json, false);
}

export function PostImageOcr200ResponseWordsResultInnerVertexesLocationInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostImageOcr200ResponseWordsResultInnerVertexesLocationInner {
    if (json == null) {
        return json;
    }
    return {
        
        'x': json['x'] == null ? undefined : json['x'],
        'y': json['y'] == null ? undefined : json['y'],
    };
}

export function PostImageOcr200ResponseWordsResultInnerVertexesLocationInnerToJSON(json: any): PostImageOcr200ResponseWordsResultInnerVertexesLocationInner {
    return PostImageOcr200ResponseWordsResultInnerVertexesLocationInnerToJSONTyped(json, false);
}

export function PostImageOcr200ResponseWordsResultInnerVertexesLocationInnerToJSONTyped(value?: PostImageOcr200ResponseWordsResultInnerVertexesLocationInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'x': value['x'],
        'y': value['y'],
    };
}

