/* tslint:disable */
/* eslint-disable */
/**
 * UAPI OpenAPI
 * Generated from UAPI JSON. Code is the interactive documentation: rich descriptions, examples, and x-extensions preserved.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostClipzyStore400Response
 */
export interface PostClipzyStore400Response {
    /**
     * 
     * @type {string}
     * @memberof PostClipzyStore400Response
     */
    details?: string;
    /**
     * 
     * @type {string}
     * @memberof PostClipzyStore400Response
     */
    error?: string;
}

/**
 * Check if a given object implements the PostClipzyStore400Response interface.
 */
export function instanceOfPostClipzyStore400Response(value: object): value is PostClipzyStore400Response {
    return true;
}

export function PostClipzyStore400ResponseFromJSON(json: any): PostClipzyStore400Response {
    return PostClipzyStore400ResponseFromJSONTyped(json, false);
}

export function PostClipzyStore400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostClipzyStore400Response {
    if (json == null) {
        return json;
    }
    return {
        
        'details': json['details'] == null ? undefined : json['details'],
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function PostClipzyStore400ResponseToJSON(json: any): PostClipzyStore400Response {
    return PostClipzyStore400ResponseToJSONTyped(json, false);
}

export function PostClipzyStore400ResponseToJSONTyped(value?: PostClipzyStore400Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'details': value['details'],
        'error': value['error'],
    };
}

