/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostTextAnalyzeRequest
 */
export interface PostTextAnalyzeRequest {
    /**
     * 
     * @type {string}
     * @memberof PostTextAnalyzeRequest
     */
    text: string;
}

/**
 * Check if a given object implements the PostTextAnalyzeRequest interface.
 */
export function instanceOfPostTextAnalyzeRequest(value: object): value is PostTextAnalyzeRequest {
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function PostTextAnalyzeRequestFromJSON(json: any): PostTextAnalyzeRequest {
    return PostTextAnalyzeRequestFromJSONTyped(json, false);
}

export function PostTextAnalyzeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostTextAnalyzeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'],
    };
}

export function PostTextAnalyzeRequestToJSON(json: any): PostTextAnalyzeRequest {
    return PostTextAnalyzeRequestToJSONTyped(json, false);
}

export function PostTextAnalyzeRequestToJSONTyped(value?: PostTextAnalyzeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text': value['text'],
    };
}

