/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostTextBase64Encode200Response
 */
export interface PostTextBase64Encode200Response {
    /**
     * 
     * @type {string}
     * @memberof PostTextBase64Encode200Response
     */
    encoded?: string;
}

/**
 * Check if a given object implements the PostTextBase64Encode200Response interface.
 */
export function instanceOfPostTextBase64Encode200Response(value: object): value is PostTextBase64Encode200Response {
    return true;
}

export function PostTextBase64Encode200ResponseFromJSON(json: any): PostTextBase64Encode200Response {
    return PostTextBase64Encode200ResponseFromJSONTyped(json, false);
}

export function PostTextBase64Encode200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostTextBase64Encode200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'encoded': json['encoded'] == null ? undefined : json['encoded'],
    };
}

export function PostTextBase64Encode200ResponseToJSON(json: any): PostTextBase64Encode200Response {
    return PostTextBase64Encode200ResponseToJSONTyped(json, false);
}

export function PostTextBase64Encode200ResponseToJSONTyped(value?: PostTextBase64Encode200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'encoded': value['encoded'],
    };
}

