/* tslint:disable */
/* eslint-disable */
/**
 * UAPI OpenAPI
 * Generated from UAPI JSON. Code is the interactive documentation: rich descriptions, examples, and x-extensions preserved.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostAiTranslate400Response
 */
export interface PostAiTranslate400Response {
    /**
     * 
     * @type {number}
     * @memberof PostAiTranslate400Response
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof PostAiTranslate400Response
     */
    error?: string;
    /**
     * 
     * @type {string}
     * @memberof PostAiTranslate400Response
     */
    message?: string;
}

/**
 * Check if a given object implements the PostAiTranslate400Response interface.
 */
export function instanceOfPostAiTranslate400Response(value: object): value is PostAiTranslate400Response {
    return true;
}

export function PostAiTranslate400ResponseFromJSON(json: any): PostAiTranslate400Response {
    return PostAiTranslate400ResponseFromJSONTyped(json, false);
}

export function PostAiTranslate400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostAiTranslate400Response {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'error': json['error'] == null ? undefined : json['error'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function PostAiTranslate400ResponseToJSON(json: any): PostAiTranslate400Response {
    return PostAiTranslate400ResponseToJSONTyped(json, false);
}

export function PostAiTranslate400ResponseToJSONTyped(value?: PostAiTranslate400Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'error': value['error'],
        'message': value['message'],
    };
}

