/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostImageOcr413Response
 */
export interface PostImageOcr413Response {
    /**
     * 
     * @type {string}
     * @memberof PostImageOcr413Response
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof PostImageOcr413Response
     */
    message?: string;
}

/**
 * Check if a given object implements the PostImageOcr413Response interface.
 */
export function instanceOfPostImageOcr413Response(value: object): value is PostImageOcr413Response {
    return true;
}

export function PostImageOcr413ResponseFromJSON(json: any): PostImageOcr413Response {
    return PostImageOcr413ResponseFromJSONTyped(json, false);
}

export function PostImageOcr413ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostImageOcr413Response {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function PostImageOcr413ResponseToJSON(json: any): PostImageOcr413Response {
    return PostImageOcr413ResponseToJSONTyped(json, false);
}

export function PostImageOcr413ResponseToJSONTyped(value?: PostImageOcr413Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
    };
}

