/* tslint:disable */
/* eslint-disable */
/**
 * UAPI OpenAPI
 * Generated from UAPI JSON. Code is the interactive documentation: rich descriptions, examples, and x-extensions preserved.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostWebTomarkdownAsync400Response
 */
export interface PostWebTomarkdownAsync400Response {
    /**
     * 
     * @type {number}
     * @memberof PostWebTomarkdownAsync400Response
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof PostWebTomarkdownAsync400Response
     */
    error?: string;
    /**
     * 
     * @type {string}
     * @memberof PostWebTomarkdownAsync400Response
     */
    message?: string;
}

/**
 * Check if a given object implements the PostWebTomarkdownAsync400Response interface.
 */
export function instanceOfPostWebTomarkdownAsync400Response(value: object): value is PostWebTomarkdownAsync400Response {
    return true;
}

export function PostWebTomarkdownAsync400ResponseFromJSON(json: any): PostWebTomarkdownAsync400Response {
    return PostWebTomarkdownAsync400ResponseFromJSONTyped(json, false);
}

export function PostWebTomarkdownAsync400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostWebTomarkdownAsync400Response {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'error': json['error'] == null ? undefined : json['error'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function PostWebTomarkdownAsync400ResponseToJSON(json: any): PostWebTomarkdownAsync400Response {
    return PostWebTomarkdownAsync400ResponseToJSONTyped(json, false);
}

export function PostWebTomarkdownAsync400ResponseToJSONTyped(value?: PostWebTomarkdownAsync400Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'error': value['error'],
        'message': value['message'],
    };
}

