/* tslint:disable */
/* eslint-disable */
/**
 * UAPI OpenAPI
 * Generated from UAPI JSON. Code is the interactive documentation: rich descriptions, examples, and x-extensions preserved.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RandomAuthorinfo } from './RandomAuthorinfo';
import {
    RandomAuthorinfoFromJSON,
    RandomAuthorinfoFromJSONTyped,
    RandomAuthorinfoToJSON,
    RandomAuthorinfoToJSONTyped,
} from './RandomAuthorinfo';

/**
 * 
 * @export
 * @interface Random
 */
export interface Random {
    /**
     * 作者或说话者。
     * @type {string}
     * @memberof Random
     */
    author?: string;
    /**
     * 
     * @type {RandomAuthorinfo}
     * @memberof Random
     */
    authorinfo?: RandomAuthorinfo;
    /**
     * 语录分类。
     * @type {string}
     * @memberof Random
     */
    category?: string;
    /**
     * 语录正文。
     * @type {string}
     * @memberof Random
     */
    content?: string;
    /**
     * 正文字数。
     * @type {number}
     * @memberof Random
     */
    contentLength?: number;
    /**
     * 所属语料库标识。
     * @type {string}
     * @memberof Random
     */
    corpus?: string;
    /**
     * 语料入库时间戳（秒），部分语料返回。
     * @type {string}
     * @memberof Random
     */
    createdAt?: string;
    /**
     * 命中的标签，部分模式返回。
     * @type {Array<string>}
     * @memberof Random
     */
    matchedTags?: Array<string>;
    /**
     * 语录出处或来源。
     * @type {string}
     * @memberof Random
     */
    source?: string;
    /**
     * 语录唯一标识。
     * @type {string}
     * @memberof Random
     */
    uuid?: string;
}

/**
 * Check if a given object implements the Random interface.
 */
export function instanceOfRandom(value: object): value is Random {
    return true;
}

export function RandomFromJSON(json: any): Random {
    return RandomFromJSONTyped(json, false);
}

export function RandomFromJSONTyped(json: any, ignoreDiscriminator: boolean): Random {
    if (json == null) {
        return json;
    }
    return {
        
        'author': json['author'] == null ? undefined : json['author'],
        'authorinfo': json['authorinfo'] == null ? undefined : RandomAuthorinfoFromJSON(json['authorinfo']),
        'category': json['category'] == null ? undefined : json['category'],
        'content': json['content'] == null ? undefined : json['content'],
        'contentLength': json['contentLength'] == null ? undefined : json['contentLength'],
        'corpus': json['corpus'] == null ? undefined : json['corpus'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'matchedTags': json['matchedTags'] == null ? undefined : json['matchedTags'],
        'source': json['source'] == null ? undefined : json['source'],
        'uuid': json['uuid'] == null ? undefined : json['uuid'],
    };
}

export function RandomToJSON(json: any): Random {
    return RandomToJSONTyped(json, false);
}

export function RandomToJSONTyped(value?: Random | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'author': value['author'],
        'authorinfo': RandomAuthorinfoToJSON(value['authorinfo']),
        'category': value['category'],
        'content': value['content'],
        'contentLength': value['contentLength'],
        'corpus': value['corpus'],
        'createdAt': value['createdAt'],
        'matchedTags': value['matchedTags'],
        'source': value['source'],
        'uuid': value['uuid'],
    };
}

