/* tslint:disable */
/* eslint-disable */
/**
 * UAPI OpenAPI
 * Generated from UAPI JSON. Code is the interactive documentation: rich descriptions, examples, and x-extensions preserved.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 作者扩展信息，部分语料返回。
 * @export
 * @interface RandomAuthorinfo
 */
export interface RandomAuthorinfo {
    /**
     * 
     * @type {string}
     * @memberof RandomAuthorinfo
     */
    bio?: string;
    /**
     * 
     * @type {string}
     * @memberof RandomAuthorinfo
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof RandomAuthorinfo
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof RandomAuthorinfo
     */
    link?: string;
    /**
     * 
     * @type {string}
     * @memberof RandomAuthorinfo
     */
    name?: string;
}

/**
 * Check if a given object implements the RandomAuthorinfo interface.
 */
export function instanceOfRandomAuthorinfo(value: object): value is RandomAuthorinfo {
    return true;
}

export function RandomAuthorinfoFromJSON(json: any): RandomAuthorinfo {
    return RandomAuthorinfoFromJSONTyped(json, false);
}

export function RandomAuthorinfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RandomAuthorinfo {
    if (json == null) {
        return json;
    }
    return {
        
        'bio': json['bio'] == null ? undefined : json['bio'],
        'description': json['description'] == null ? undefined : json['description'],
        'id': json['id'] == null ? undefined : json['id'],
        'link': json['link'] == null ? undefined : json['link'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function RandomAuthorinfoToJSON(json: any): RandomAuthorinfo {
    return RandomAuthorinfoToJSONTyped(json, false);
}

export function RandomAuthorinfoToJSONTyped(value?: RandomAuthorinfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bio': value['bio'],
        'description': value['description'],
        'id': value['id'],
        'link': value['link'],
        'name': value['name'],
    };
}

