/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetSearchEngines200Response,
  GetSensitiveWordAnalyzeQuery400Response,
  PostSearchAggregate200Response,
  PostSearchAggregate400Response,
  PostSearchAggregate401Response,
  PostSearchAggregate429Response,
  PostSearchAggregate500Response,
  PostSearchAggregateRequest,
  PostSensitiveWordAnalyze200Response,
  PostSensitiveWordAnalyze400Response,
  PostSensitiveWordAnalyze401Response,
  PostSensitiveWordAnalyze429Response,
  PostSensitiveWordAnalyzeRequest,
  PostSensitiveWordQuickCheck200Response,
  PostSensitiveWordQuickCheckRequest,
  PostTextAnalyze400Response,
} from '../models/index';
import {
    GetSearchEngines200ResponseFromJSON,
    GetSearchEngines200ResponseToJSON,
    GetSensitiveWordAnalyzeQuery400ResponseFromJSON,
    GetSensitiveWordAnalyzeQuery400ResponseToJSON,
    PostSearchAggregate200ResponseFromJSON,
    PostSearchAggregate200ResponseToJSON,
    PostSearchAggregate400ResponseFromJSON,
    PostSearchAggregate400ResponseToJSON,
    PostSearchAggregate401ResponseFromJSON,
    PostSearchAggregate401ResponseToJSON,
    PostSearchAggregate429ResponseFromJSON,
    PostSearchAggregate429ResponseToJSON,
    PostSearchAggregate500ResponseFromJSON,
    PostSearchAggregate500ResponseToJSON,
    PostSearchAggregateRequestFromJSON,
    PostSearchAggregateRequestToJSON,
    PostSensitiveWordAnalyze200ResponseFromJSON,
    PostSensitiveWordAnalyze200ResponseToJSON,
    PostSensitiveWordAnalyze400ResponseFromJSON,
    PostSensitiveWordAnalyze400ResponseToJSON,
    PostSensitiveWordAnalyze401ResponseFromJSON,
    PostSensitiveWordAnalyze401ResponseToJSON,
    PostSensitiveWordAnalyze429ResponseFromJSON,
    PostSensitiveWordAnalyze429ResponseToJSON,
    PostSensitiveWordAnalyzeRequestFromJSON,
    PostSensitiveWordAnalyzeRequestToJSON,
    PostSensitiveWordQuickCheck200ResponseFromJSON,
    PostSensitiveWordQuickCheck200ResponseToJSON,
    PostSensitiveWordQuickCheckRequestFromJSON,
    PostSensitiveWordQuickCheckRequestToJSON,
    PostTextAnalyze400ResponseFromJSON,
    PostTextAnalyze400ResponseToJSON,
} from '../models/index';

export interface GetSensitiveWordAnalyzeQueryRequest {
    keyword: string;
}

export interface PostSearchAggregateOperationRequest {
    postSearchAggregateRequest: PostSearchAggregateRequest;
}

export interface PostSensitiveWordAnalyzeOperationRequest {
    postSensitiveWordAnalyzeRequest: PostSensitiveWordAnalyzeRequest;
}

export interface PostSensitiveWordQuickCheckOperationRequest {
    postSensitiveWordQuickCheckRequest: PostSensitiveWordQuickCheckRequest;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * 获取搜索功能的详细信息，包括支持的能力、参数限制和使用说明。  ## 功能概述  此接口返回搜索功能的完整配置信息，你可以用它来： - 了解当前可用的搜索能力（如站内搜索、文件类型过滤等） - 获取参数的默认值和限制范围 - 查看当前配置版本和可用状态  适合在应用初始化时调用，或用于动态配置搜索界面。       
     * 搜索引擎配置
     */
    async getSearchEnginesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetSearchEngines200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/search/engines`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetSearchEngines200ResponseFromJSON(jsonValue));
    }

    /**
     * 获取搜索功能的详细信息，包括支持的能力、参数限制和使用说明。  ## 功能概述  此接口返回搜索功能的完整配置信息，你可以用它来： - 了解当前可用的搜索能力（如站内搜索、文件类型过滤等） - 获取参数的默认值和限制范围 - 查看当前配置版本和可用状态  适合在应用初始化时调用，或用于动态配置搜索界面。       
     * 搜索引擎配置
     */
    async getSearchEngines(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetSearchEngines200Response> {
        const response = await this.getSearchEnginesRaw(initOverrides);
        return await response.value();
    }

    /**
     * 通过URL查询参数分析单个关键词，便于GET请求调用。
     * 敏感词分析 (GET)
     */
    async getSensitiveWordAnalyzeQueryRaw(requestParameters: GetSensitiveWordAnalyzeQueryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostSensitiveWordAnalyze200Response>> {
        if (requestParameters['keyword'] == null) {
            throw new runtime.RequiredError(
                'keyword',
                'Required parameter "keyword" was null or undefined when calling getSensitiveWordAnalyzeQuery().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['keyword'] != null) {
            queryParameters['keyword'] = requestParameters['keyword'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/sensitive-word/analyze-query`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostSensitiveWordAnalyze200ResponseFromJSON(jsonValue));
    }

    /**
     * 通过URL查询参数分析单个关键词，便于GET请求调用。
     * 敏感词分析 (GET)
     */
    async getSensitiveWordAnalyzeQuery(requestParameters: GetSensitiveWordAnalyzeQueryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostSensitiveWordAnalyze200Response> {
        const response = await this.getSensitiveWordAnalyzeQueryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 想在你的应用中集成搜索功能？这个接口可以帮你轻松实现实时网页搜索。  ## 功能概述  UAPI Pro Search 可以根据查询内容返回更相关的搜索结果。你可以用它搜索任何关键词，也可以限定在特定网站或特定文件类型中搜索。  - **实时网页搜索**: 毫秒级响应，快速返回搜索结果 - **智能排序**: 根据查询内容返回更相关的结果 - **时间排序**: 支持按发布时间排序，获取最新内容 - **时间范围过滤**: 支持按天/周/月/年过滤结果 - **站内搜索**: 支持 `site:` 操作符，在指定网站内搜索 - **文件类型过滤**: 支持 `filetype:` 操作符，快速找到 PDF、Word 等特定格式文件       
     * 智能搜索
     */
    async postSearchAggregateRaw(requestParameters: PostSearchAggregateOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostSearchAggregate200Response>> {
        if (requestParameters['postSearchAggregateRequest'] == null) {
            throw new runtime.RequiredError(
                'postSearchAggregateRequest',
                'Required parameter "postSearchAggregateRequest" was null or undefined when calling postSearchAggregate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/search/aggregate`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostSearchAggregateRequestToJSON(requestParameters['postSearchAggregateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostSearchAggregate200ResponseFromJSON(jsonValue));
    }

    /**
     * 想在你的应用中集成搜索功能？这个接口可以帮你轻松实现实时网页搜索。  ## 功能概述  UAPI Pro Search 可以根据查询内容返回更相关的搜索结果。你可以用它搜索任何关键词，也可以限定在特定网站或特定文件类型中搜索。  - **实时网页搜索**: 毫秒级响应，快速返回搜索结果 - **智能排序**: 根据查询内容返回更相关的结果 - **时间排序**: 支持按发布时间排序，获取最新内容 - **时间范围过滤**: 支持按天/周/月/年过滤结果 - **站内搜索**: 支持 `site:` 操作符，在指定网站内搜索 - **文件类型过滤**: 支持 `filetype:` 操作符，快速找到 PDF、Word 等特定格式文件       
     * 智能搜索
     */
    async postSearchAggregate(requestParameters: PostSearchAggregateOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostSearchAggregate200Response> {
        const response = await this.postSearchAggregateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 分析单个或多个关键词的敏感程度，返回标准化风险标签与置信度结果。  ## 功能概述  - **风险分析**: 结合文本内容给出语义层面的风险判断。 - **响应稳定**: 兼顾高频调用场景下的处理效率和响应速度。 - **并发支持**: 支持批量并发处理，单次最多可分析100个关键词。 - **输入限制**: 单条关键词最多 1,000 字符，总字符数最多 20,000。 - **标准标签**: 返回 `label` 字段，明确区分 `sensitive` 与 `normal`。 - **分类清晰**: 返回 `category` 字段，用于标识具体风险类别。 - **置信度输出**: 返回 `confidence` 字段，范围为0.0到1.0。  ## 响应字段说明  | 字段 | 类型 | 说明 | |------|------|------| | `results` | array | 分析结果对象的数组。 | | `results[].k` | string | 您在请求中提供的原始关键词。 | | `results[].label` | string | 核心判断字段：`sensitive`(敏感)、`normal`(正常)。 | | `results[].category` | string | 风险分类：`safe`(安全)、`threat`(威胁)、`porn`(色情)、`fraud`(欺诈)、`insult`(辱骂)。 | | `results[].confidence` | number | 当前分类的置信度，范围0.0到1.0。 | | `total` | integer | 本次请求成功分析的关键词总数。 |       
     * 分析敏感词
     */
    async postSensitiveWordAnalyzeRaw(requestParameters: PostSensitiveWordAnalyzeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostSensitiveWordAnalyze200Response>> {
        if (requestParameters['postSensitiveWordAnalyzeRequest'] == null) {
            throw new runtime.RequiredError(
                'postSensitiveWordAnalyzeRequest',
                'Required parameter "postSensitiveWordAnalyzeRequest" was null or undefined when calling postSensitiveWordAnalyze().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/sensitive-word/analyze`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostSensitiveWordAnalyzeRequestToJSON(requestParameters['postSensitiveWordAnalyzeRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostSensitiveWordAnalyze200ResponseFromJSON(jsonValue));
    }

    /**
     * 分析单个或多个关键词的敏感程度，返回标准化风险标签与置信度结果。  ## 功能概述  - **风险分析**: 结合文本内容给出语义层面的风险判断。 - **响应稳定**: 兼顾高频调用场景下的处理效率和响应速度。 - **并发支持**: 支持批量并发处理，单次最多可分析100个关键词。 - **输入限制**: 单条关键词最多 1,000 字符，总字符数最多 20,000。 - **标准标签**: 返回 `label` 字段，明确区分 `sensitive` 与 `normal`。 - **分类清晰**: 返回 `category` 字段，用于标识具体风险类别。 - **置信度输出**: 返回 `confidence` 字段，范围为0.0到1.0。  ## 响应字段说明  | 字段 | 类型 | 说明 | |------|------|------| | `results` | array | 分析结果对象的数组。 | | `results[].k` | string | 您在请求中提供的原始关键词。 | | `results[].label` | string | 核心判断字段：`sensitive`(敏感)、`normal`(正常)。 | | `results[].category` | string | 风险分类：`safe`(安全)、`threat`(威胁)、`porn`(色情)、`fraud`(欺诈)、`insult`(辱骂)。 | | `results[].confidence` | number | 当前分类的置信度，范围0.0到1.0。 | | `total` | integer | 本次请求成功分析的关键词总数。 |       
     * 分析敏感词
     */
    async postSensitiveWordAnalyze(requestParameters: PostSensitiveWordAnalyzeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostSensitiveWordAnalyze200Response> {
        const response = await this.postSensitiveWordAnalyzeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 在你的社区或应用中，需要过滤不适合展示的内容时，这个接口可以帮你快速完成检测。  ## 功能概述  这个接口可以识别文本中的敏感词，并返回是否命中、命中词列表等结果，适合用于评论区、社区、论坛和内容发布场景。  ### 主要特性  - **快速检测**：能够一次处理整段文本中的多个命中内容 - **简繁体支持**：支持简体中文、繁体中文和混合文本检测 - **结果直观**：返回清晰的检测结果，方便直接接入审核流程 - **响应稳定**：适合日常内容审核和批量检查场景  无论是论坛、社交平台还是评论系统，这个接口都能帮你快速构建内容审核功能。
     * 敏感词检测（快速）
     */
    async postSensitiveWordQuickCheckRaw(requestParameters: PostSensitiveWordQuickCheckOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostSensitiveWordQuickCheck200Response>> {
        if (requestParameters['postSensitiveWordQuickCheckRequest'] == null) {
            throw new runtime.RequiredError(
                'postSensitiveWordQuickCheckRequest',
                'Required parameter "postSensitiveWordQuickCheckRequest" was null or undefined when calling postSensitiveWordQuickCheck().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/text/profanitycheck`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostSensitiveWordQuickCheckRequestToJSON(requestParameters['postSensitiveWordQuickCheckRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostSensitiveWordQuickCheck200ResponseFromJSON(jsonValue));
    }

    /**
     * 在你的社区或应用中，需要过滤不适合展示的内容时，这个接口可以帮你快速完成检测。  ## 功能概述  这个接口可以识别文本中的敏感词，并返回是否命中、命中词列表等结果，适合用于评论区、社区、论坛和内容发布场景。  ### 主要特性  - **快速检测**：能够一次处理整段文本中的多个命中内容 - **简繁体支持**：支持简体中文、繁体中文和混合文本检测 - **结果直观**：返回清晰的检测结果，方便直接接入审核流程 - **响应稳定**：适合日常内容审核和批量检查场景  无论是论坛、社交平台还是评论系统，这个接口都能帮你快速构建内容审核功能。
     * 敏感词检测（快速）
     */
    async postSensitiveWordQuickCheck(requestParameters: PostSensitiveWordQuickCheckOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostSensitiveWordQuickCheck200Response> {
        const response = await this.postSensitiveWordQuickCheckRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
