/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  FormatJson,
  GetAvatarGravatar400Response,
  GetAvatarGravatar404Response,
  GetImageBingDaily400Response,
  GetImageBingDaily404Response,
  GetImageBingDaily500Response,
  GetImageBingDailyHistory200Response,
  GetImageBingDailyHistory400Response,
  GetImageMotou400Response,
  GetImageMotou500Response,
  GetImageQrcode200Response,
  GetImageQrcode400Response,
  GetImageQrcode500Response,
  GetImageTobase64200Response,
  GetImageTobase64400Response,
  GetImageTobase64502Response,
  PostImageCompress400Response,
  PostImageCompress500Response,
  PostImageDecode400Response,
  PostImageDecode413Response,
  PostImageDecode500Response,
  PostImageDecode502Response,
  PostImageDecode503Response,
  PostImageDecode504Response,
  PostImageFrombase64200Response,
  PostImageFrombase64400Response,
  PostImageFrombase64500Response,
  PostImageFrombase64Request,
  PostImageMotou400Response,
  PostImageMotou500Response,
  PostImageNsfw200Response,
  PostImageNsfw400Response,
  PostImageNsfw413Response,
  PostImageNsfw500Response,
  PostImageOcr200Response,
  PostImageOcr400Response,
  PostImageOcr413Response,
  PostImageOcr415Response,
  PostImageOcr502Response,
  PostImageOcr503Response,
  PostImageSpeechless400Response,
  PostImageSpeechless500Response,
  PostImageSpeechlessRequest,
  PostImageSvg400Response,
  PostImageSvg500Response,
} from '../models/index';
import {
    FormatJsonFromJSON,
    FormatJsonToJSON,
    GetAvatarGravatar400ResponseFromJSON,
    GetAvatarGravatar400ResponseToJSON,
    GetAvatarGravatar404ResponseFromJSON,
    GetAvatarGravatar404ResponseToJSON,
    GetImageBingDaily400ResponseFromJSON,
    GetImageBingDaily400ResponseToJSON,
    GetImageBingDaily404ResponseFromJSON,
    GetImageBingDaily404ResponseToJSON,
    GetImageBingDaily500ResponseFromJSON,
    GetImageBingDaily500ResponseToJSON,
    GetImageBingDailyHistory200ResponseFromJSON,
    GetImageBingDailyHistory200ResponseToJSON,
    GetImageBingDailyHistory400ResponseFromJSON,
    GetImageBingDailyHistory400ResponseToJSON,
    GetImageMotou400ResponseFromJSON,
    GetImageMotou400ResponseToJSON,
    GetImageMotou500ResponseFromJSON,
    GetImageMotou500ResponseToJSON,
    GetImageQrcode200ResponseFromJSON,
    GetImageQrcode200ResponseToJSON,
    GetImageQrcode400ResponseFromJSON,
    GetImageQrcode400ResponseToJSON,
    GetImageQrcode500ResponseFromJSON,
    GetImageQrcode500ResponseToJSON,
    GetImageTobase64200ResponseFromJSON,
    GetImageTobase64200ResponseToJSON,
    GetImageTobase64400ResponseFromJSON,
    GetImageTobase64400ResponseToJSON,
    GetImageTobase64502ResponseFromJSON,
    GetImageTobase64502ResponseToJSON,
    PostImageCompress400ResponseFromJSON,
    PostImageCompress400ResponseToJSON,
    PostImageCompress500ResponseFromJSON,
    PostImageCompress500ResponseToJSON,
    PostImageDecode400ResponseFromJSON,
    PostImageDecode400ResponseToJSON,
    PostImageDecode413ResponseFromJSON,
    PostImageDecode413ResponseToJSON,
    PostImageDecode500ResponseFromJSON,
    PostImageDecode500ResponseToJSON,
    PostImageDecode502ResponseFromJSON,
    PostImageDecode502ResponseToJSON,
    PostImageDecode503ResponseFromJSON,
    PostImageDecode503ResponseToJSON,
    PostImageDecode504ResponseFromJSON,
    PostImageDecode504ResponseToJSON,
    PostImageFrombase64200ResponseFromJSON,
    PostImageFrombase64200ResponseToJSON,
    PostImageFrombase64400ResponseFromJSON,
    PostImageFrombase64400ResponseToJSON,
    PostImageFrombase64500ResponseFromJSON,
    PostImageFrombase64500ResponseToJSON,
    PostImageFrombase64RequestFromJSON,
    PostImageFrombase64RequestToJSON,
    PostImageMotou400ResponseFromJSON,
    PostImageMotou400ResponseToJSON,
    PostImageMotou500ResponseFromJSON,
    PostImageMotou500ResponseToJSON,
    PostImageNsfw200ResponseFromJSON,
    PostImageNsfw200ResponseToJSON,
    PostImageNsfw400ResponseFromJSON,
    PostImageNsfw400ResponseToJSON,
    PostImageNsfw413ResponseFromJSON,
    PostImageNsfw413ResponseToJSON,
    PostImageNsfw500ResponseFromJSON,
    PostImageNsfw500ResponseToJSON,
    PostImageOcr200ResponseFromJSON,
    PostImageOcr200ResponseToJSON,
    PostImageOcr400ResponseFromJSON,
    PostImageOcr400ResponseToJSON,
    PostImageOcr413ResponseFromJSON,
    PostImageOcr413ResponseToJSON,
    PostImageOcr415ResponseFromJSON,
    PostImageOcr415ResponseToJSON,
    PostImageOcr502ResponseFromJSON,
    PostImageOcr502ResponseToJSON,
    PostImageOcr503ResponseFromJSON,
    PostImageOcr503ResponseToJSON,
    PostImageSpeechless400ResponseFromJSON,
    PostImageSpeechless400ResponseToJSON,
    PostImageSpeechless500ResponseFromJSON,
    PostImageSpeechless500ResponseToJSON,
    PostImageSpeechlessRequestFromJSON,
    PostImageSpeechlessRequestToJSON,
    PostImageSvg400ResponseFromJSON,
    PostImageSvg400ResponseToJSON,
    PostImageSvg500ResponseFromJSON,
    PostImageSvg500ResponseToJSON,
} from '../models/index';

export interface GetAvatarGravatarRequest {
    email?: string;
    hash?: string;
    s?: number;
    d?: string;
    r?: string;
}

export interface GetImageBingDailyRequest {
    date?: string;
    resolution?: GetImageBingDailyResolutionEnum;
    format?: GetImageBingDailyFormatEnum;
}

export interface GetImageBingDailyHistoryRequest {
    date?: string;
    resolution?: GetImageBingDailyHistoryResolutionEnum;
    page?: number;
    pageSize?: number;
}

export interface GetImageMotouRequest {
    qq: string;
    bgColor?: GetImageMotouBgColorEnum;
}

export interface GetImageQrcodeRequest {
    text: string;
    size?: number;
    format?: GetImageQrcodeFormatEnum;
    transparent?: boolean;
    fgcolor?: string;
    bgcolor?: string;
}

export interface GetImageTobase64Request {
    url: string;
}

export interface PostImageCompressRequest {
    file: Blob;
    level?: PostImageCompressLevelEnum;
    format?: PostImageCompressFormatEnum;
}

export interface PostImageDecodeRequest {
    width?: number;
    height?: number;
    maxWidth?: number;
    maxHeight?: number;
    format?: PostImageDecodeFormatEnum;
    colorMode?: PostImageDecodeColorModeEnum;
    fit?: PostImageDecodeFitEnum;
    background?: string;
    file?: Blob;
    url?: string;
}

export interface PostImageFrombase64OperationRequest {
    postImageFrombase64Request: PostImageFrombase64Request;
}

export interface PostImageMotouRequest {
    imageUrl?: string;
    file?: Blob;
    bgColor?: PostImageMotouBgColorEnum;
}

export interface PostImageNsfwRequest {
    file?: Blob;
    url?: string;
}

export interface PostImageOcrRequest {
    file?: Blob;
    url?: string;
    imageBase64?: string;
    imageName?: string;
    needLocation?: PostImageOcrNeedLocationEnum;
    returnMarkdown?: PostImageOcrReturnMarkdownEnum;
    enableCls?: PostImageOcrEnableClsEnum;
}

export interface PostImageSpeechlessOperationRequest {
    postImageSpeechlessRequest: PostImageSpeechlessRequest;
}

export interface PostImageSvgRequest {
    format?: PostImageSvgFormatEnum;
    width?: number;
    height?: number;
    quality?: number;
    file?: Blob;
}

/**
 * 
 */
export class ImageApi extends runtime.BaseAPI {

    /**
     * 提供稳定、易用的头像获取能力，适合在网页或应用中直接展示头像。
     * 获取Gravatar头像
     */
    async getAvatarGravatarRaw(requestParameters: GetAvatarGravatarRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        const queryParameters: any = {};

        if (requestParameters['email'] != null) {
            queryParameters['email'] = requestParameters['email'];
        }

        if (requestParameters['hash'] != null) {
            queryParameters['hash'] = requestParameters['hash'];
        }

        if (requestParameters['s'] != null) {
            queryParameters['s'] = requestParameters['s'];
        }

        if (requestParameters['d'] != null) {
            queryParameters['d'] = requestParameters['d'];
        }

        if (requestParameters['r'] != null) {
            queryParameters['r'] = requestParameters['r'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/avatar/gravatar`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * 提供稳定、易用的头像获取能力，适合在网页或应用中直接展示头像。
     * 获取Gravatar头像
     */
    async getAvatarGravatar(requestParameters: GetAvatarGravatarRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.getAvatarGravatarRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 这个接口可以获取最新或指定日期的必应壁纸。默认直接返回图片，也可以传 `format=json` 获取元数据，或者传 `format=redirect` 直接跳转到最终图片地址。  ## 功能概述 - 不传参数时，默认返回当天壁纸图片二进制 - 可以传 `date` 查询指定日期的壁纸 - 可以传 `resolution` 选择 `4k` 或 `1080` - 可以传 `format` 控制返回图片、JSON 或 302 跳转 - 当传 `format=json` 时，返回的是扁平 JSON 对象，里面会包含标题、副标题、说明文案、版权信息、问答信息和图片地址等字段  ## 参数说明 `resolution` 默认是 `4k`。 `format` 默认是 `image`。
     * 获取必应每日壁纸
     */
    async getImageBingDailyRaw(requestParameters: GetImageBingDailyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        const queryParameters: any = {};

        if (requestParameters['date'] != null) {
            queryParameters['date'] = requestParameters['date'];
        }

        if (requestParameters['resolution'] != null) {
            queryParameters['resolution'] = requestParameters['resolution'];
        }

        if (requestParameters['format'] != null) {
            queryParameters['format'] = requestParameters['format'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/image/bing-daily`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * 这个接口可以获取最新或指定日期的必应壁纸。默认直接返回图片，也可以传 `format=json` 获取元数据，或者传 `format=redirect` 直接跳转到最终图片地址。  ## 功能概述 - 不传参数时，默认返回当天壁纸图片二进制 - 可以传 `date` 查询指定日期的壁纸 - 可以传 `resolution` 选择 `4k` 或 `1080` - 可以传 `format` 控制返回图片、JSON 或 302 跳转 - 当传 `format=json` 时，返回的是扁平 JSON 对象，里面会包含标题、副标题、说明文案、版权信息、问答信息和图片地址等字段  ## 参数说明 `resolution` 默认是 `4k`。 `format` 默认是 `image`。
     * 获取必应每日壁纸
     */
    async getImageBingDaily(requestParameters: GetImageBingDailyRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.getImageBingDailyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 这个接口用于查询必应壁纸历史列表，也可以按日期精确查询某一天。默认按时间倒序返回 JSON。  ## 功能概述 - 可以传 `date` 精确查询某一天，命中后只返回 1 条数据 - 不传 `date` 时，按时间倒序分页返回历史列表 - 可以传 `resolution` 让 `image_url` 直接对应 `4k` 或 `1080` - 可以传 `page` 和 `page_size` 控制分页 - 每条记录都是扁平 JSON 对象，里面会包含标题、副标题、说明文案、版权信息、问答信息和图片地址等字段  ## 参数说明 `resolution` 默认是 `4k`。 `page` 默认是 `1`，`page_size` 默认是 `30`，最大是 `100`。 当传了 `date` 以后，`page` 和 `page_size` 不生效。
     * 查询必应壁纸历史
     */
    async getImageBingDailyHistoryRaw(requestParameters: GetImageBingDailyHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetImageBingDailyHistory200Response>> {
        const queryParameters: any = {};

        if (requestParameters['date'] != null) {
            queryParameters['date'] = requestParameters['date'];
        }

        if (requestParameters['resolution'] != null) {
            queryParameters['resolution'] = requestParameters['resolution'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['page_size'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/image/bing-daily/history`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetImageBingDailyHistory200ResponseFromJSON(jsonValue));
    }

    /**
     * 这个接口用于查询必应壁纸历史列表，也可以按日期精确查询某一天。默认按时间倒序返回 JSON。  ## 功能概述 - 可以传 `date` 精确查询某一天，命中后只返回 1 条数据 - 不传 `date` 时，按时间倒序分页返回历史列表 - 可以传 `resolution` 让 `image_url` 直接对应 `4k` 或 `1080` - 可以传 `page` 和 `page_size` 控制分页 - 每条记录都是扁平 JSON 对象，里面会包含标题、副标题、说明文案、版权信息、问答信息和图片地址等字段  ## 参数说明 `resolution` 默认是 `4k`。 `page` 默认是 `1`，`page_size` 默认是 `30`，最大是 `100`。 当传了 `date` 以后，`page` 和 `page_size` 不生效。
     * 查询必应壁纸历史
     */
    async getImageBingDailyHistory(requestParameters: GetImageBingDailyHistoryRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetImageBingDailyHistory200Response> {
        const response = await this.getImageBingDailyHistoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 想在线rua一下好友的头像吗？这个趣味接口可以满足你。  ## 功能概述 此接口通过GET方法，专门用于通过QQ号生成摸摸头GIF。你只需要提供一个QQ号码，我们就会自动获取其公开头像，并制作成一个可爱的动图。  ## 使用须知 - **响应格式**：接口成功时直接返回 `image/gif` 格式的二进制数据。 - **背景颜色**：你可以通过 `bg_color` 参数来控制GIF的背景。使用 `transparent` 选项可以让它更好地融入各种聊天背景中。
     * 生成摸摸头GIF (QQ号)
     */
    async getImageMotouRaw(requestParameters: GetImageMotouRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        if (requestParameters['qq'] == null) {
            throw new runtime.RequiredError(
                'qq',
                'Required parameter "qq" was null or undefined when calling getImageMotou().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['qq'] != null) {
            queryParameters['qq'] = requestParameters['qq'];
        }

        if (requestParameters['bgColor'] != null) {
            queryParameters['bg_color'] = requestParameters['bgColor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/image/motou`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * 想在线rua一下好友的头像吗？这个趣味接口可以满足你。  ## 功能概述 此接口通过GET方法，专门用于通过QQ号生成摸摸头GIF。你只需要提供一个QQ号码，我们就会自动获取其公开头像，并制作成一个可爱的动图。  ## 使用须知 - **响应格式**：接口成功时直接返回 `image/gif` 格式的二进制数据。 - **背景颜色**：你可以通过 `bg_color` 参数来控制GIF的背景。使用 `transparent` 选项可以让它更好地融入各种聊天背景中。
     * 生成摸摸头GIF (QQ号)
     */
    async getImageMotou(requestParameters: GetImageMotouRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.getImageMotouRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 无论是网址、文本还是联系方式，通通可以变成一个二维码！这是一个非常灵活的二维码生成工具。  ## 功能概述 你提供一段文本内容，我们为你生成对应的二维码图片。你可以自定义尺寸、前景色、背景色，还支持透明背景，并选择不同的返回格式以适应不同场景。
     * 生成二维码
     */
    async getImageQrcodeRaw(requestParameters: GetImageQrcodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        if (requestParameters['text'] == null) {
            throw new runtime.RequiredError(
                'text',
                'Required parameter "text" was null or undefined when calling getImageQrcode().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['text'] != null) {
            queryParameters['text'] = requestParameters['text'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        if (requestParameters['format'] != null) {
            queryParameters['format'] = requestParameters['format'];
        }

        if (requestParameters['transparent'] != null) {
            queryParameters['transparent'] = requestParameters['transparent'];
        }

        if (requestParameters['fgcolor'] != null) {
            queryParameters['fgcolor'] = requestParameters['fgcolor'];
        }

        if (requestParameters['bgcolor'] != null) {
            queryParameters['bgcolor'] = requestParameters['bgcolor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/image/qrcode`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * 无论是网址、文本还是联系方式，通通可以变成一个二维码！这是一个非常灵活的二维码生成工具。  ## 功能概述 你提供一段文本内容，我们为你生成对应的二维码图片。你可以自定义尺寸、前景色、背景色，还支持透明背景，并选择不同的返回格式以适应不同场景。
     * 生成二维码
     */
    async getImageQrcode(requestParameters: GetImageQrcodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.getImageQrcodeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 看到一张网上的图片，想把它转换成 Base64 编码以便嵌入到你的 HTML 或 CSS 中？用这个接口就对了。  ## 功能概述 你提供一个公开可访问的图片 URL，我们帮你把它下载下来，并转换成包含 MIME 类型的 Base64 Data URI 字符串返回给你。
     * 图片转 Base64
     */
    async getImageTobase64Raw(requestParameters: GetImageTobase64Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetImageTobase64200Response>> {
        if (requestParameters['url'] == null) {
            throw new runtime.RequiredError(
                'url',
                'Required parameter "url" was null or undefined when calling getImageTobase64().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['url'] != null) {
            queryParameters['url'] = requestParameters['url'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/image/tobase64`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetImageTobase64200ResponseFromJSON(jsonValue));
    }

    /**
     * 看到一张网上的图片，想把它转换成 Base64 编码以便嵌入到你的 HTML 或 CSS 中？用这个接口就对了。  ## 功能概述 你提供一个公开可访问的图片 URL，我们帮你把它下载下来，并转换成包含 MIME 类型的 Base64 Data URI 字符串返回给你。
     * 图片转 Base64
     */
    async getImageTobase64(requestParameters: GetImageTobase64Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetImageTobase64200Response> {
        const response = await this.getImageTobase64Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 还在为图片体积和加载速度发愁吗？体验一下我们强大的**无损压缩服务**，它能在几乎不牺牲任何肉眼可感知的画质的前提下，将图片体积压缩到极致。  ## 功能概述 你只需要上传一张常见的图片（如 PNG, JPG），选择一个压缩等级，就能获得一个体积小到惊人的压缩文件。这对于需要大量展示高清图片的网站、App 或小程序来说，是优化用户体验、节省带宽和存储成本的利器。  ## 使用须知 > [!TIP] > 图片越大或压缩等级越高，处理时间可能越长，请您耐心等待。  > [!WARNING] > **处理时间提醒** > 在访问量较高时，处理时间可能进一步延长。如果您的业务对返回时间比较敏感，建议预留充足的处理时间。  ### 请求与响应格式 - 请求必须使用 `multipart/form-data` 格式上传文件。 - 成功响应将直接返回压缩后的文件二进制流 (`image/_*`)，并附带 `Content-Disposition` 头，建议客户端根据此头信息保存文件。  ## 参数详解 ### `level` (压缩等级) 这是一个从 `1` 到 `5` 的整数，它决定了压缩的强度和策略，数字越小，压缩率越高。所有等级都经过精心调校，以在最大化压缩率的同时保证出色的视觉质量。 - `1`: **极限压缩** (推荐，体积最小，画质优异) - `2`: **高效压缩** - `3`: **智能均衡** (默认选项) - `4`: **画质优先** - `5`: **专业保真** (压缩率稍低，保留最多图像信息)  ## 错误处理指南 - **400 Bad Request**: 通常因为没有上传文件，或者 `level` 参数不在 1-5 的范围内。 - **500 Internal Server Error**: 如果在压缩过程中服务器发生内部错误，会返回此状态码。
     * 无损压缩图片
     */
    async postImageCompressRaw(requestParameters: PostImageCompressRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling postImageCompress().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['level'] != null) {
            queryParameters['level'] = requestParameters['level'];
        }

        if (requestParameters['format'] != null) {
            queryParameters['format'] = requestParameters['format'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }


        let urlPath = `/image/compress`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * 还在为图片体积和加载速度发愁吗？体验一下我们强大的**无损压缩服务**，它能在几乎不牺牲任何肉眼可感知的画质的前提下，将图片体积压缩到极致。  ## 功能概述 你只需要上传一张常见的图片（如 PNG, JPG），选择一个压缩等级，就能获得一个体积小到惊人的压缩文件。这对于需要大量展示高清图片的网站、App 或小程序来说，是优化用户体验、节省带宽和存储成本的利器。  ## 使用须知 > [!TIP] > 图片越大或压缩等级越高，处理时间可能越长，请您耐心等待。  > [!WARNING] > **处理时间提醒** > 在访问量较高时，处理时间可能进一步延长。如果您的业务对返回时间比较敏感，建议预留充足的处理时间。  ### 请求与响应格式 - 请求必须使用 `multipart/form-data` 格式上传文件。 - 成功响应将直接返回压缩后的文件二进制流 (`image/_*`)，并附带 `Content-Disposition` 头，建议客户端根据此头信息保存文件。  ## 参数详解 ### `level` (压缩等级) 这是一个从 `1` 到 `5` 的整数，它决定了压缩的强度和策略，数字越小，压缩率越高。所有等级都经过精心调校，以在最大化压缩率的同时保证出色的视觉质量。 - `1`: **极限压缩** (推荐，体积最小，画质优异) - `2`: **高效压缩** - `3`: **智能均衡** (默认选项) - `4`: **画质优先** - `5`: **专业保真** (压缩率稍低，保留最多图像信息)  ## 错误处理指南 - **400 Bad Request**: 通常因为没有上传文件，或者 `level` 参数不在 1-5 的范围内。 - **500 Internal Server Error**: 如果在压缩过程中服务器发生内部错误，会返回此状态码。
     * 无损压缩图片
     */
    async postImageCompress(requestParameters: PostImageCompressRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.postImageCompressRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 在 RAM 和 Flash 极其有限的设备上解码图片是一项繁重的任务。这个接口专为 IoT 和嵌入式开发设计，将复杂的图像解码和缩放操作转移到云端，直接输出适用于单片机屏幕的二进制像素流。  ## 功能概述 此接口提供了灵活的云端图像预处理能力，帮助硬件开发者跳过繁琐的图像处理逻辑： - **直接推流渲染**：如果选择输出纯像素流（如 RGB565），单片机收到网络数据后无需解析文件头，可直接将其写入显存，实现极低内存占用的边下边播。 - **完美适配屏幕**：无需在设备端编写裁剪或补边代码。只需传入目标屏幕的物理分辨率，接口会自动完成等比缩放、居中补色或铺满裁剪，确保最终显示画面不变形。 - **精准内存分配**：在动态缩放图片的场景下，服务端会在 HTTP 响应头中提前注入 `X-Image-Width` 和 `X-Image-Height`，方便设备在读取真实的二进制数据前进行准确的内存分配。  ## 使用须知 - **请求格式**：无论是上传本地文件还是传递图片链接，请求体都必须使用 `multipart/form-data` 编码格式。 - **网络资源获取**：当您选择传递图片链接时，服务端会自动尝试获取该资源。请确保您提供的图片链接是公网直接可访问的，且不需要任何形式的登录鉴权。
     * 解码并缩放图片
     */
    async postImageDecodeRaw(requestParameters: PostImageDecodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        const queryParameters: any = {};

        if (requestParameters['width'] != null) {
            queryParameters['width'] = requestParameters['width'];
        }

        if (requestParameters['height'] != null) {
            queryParameters['height'] = requestParameters['height'];
        }

        if (requestParameters['maxWidth'] != null) {
            queryParameters['max_width'] = requestParameters['maxWidth'];
        }

        if (requestParameters['maxHeight'] != null) {
            queryParameters['max_height'] = requestParameters['maxHeight'];
        }

        if (requestParameters['format'] != null) {
            queryParameters['format'] = requestParameters['format'];
        }

        if (requestParameters['colorMode'] != null) {
            queryParameters['color_mode'] = requestParameters['colorMode'];
        }

        if (requestParameters['fit'] != null) {
            queryParameters['fit'] = requestParameters['fit'];
        }

        if (requestParameters['background'] != null) {
            queryParameters['background'] = requestParameters['background'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }

        if (requestParameters['url'] != null) {
            formParams.append('url', requestParameters['url'] as any);
        }


        let urlPath = `/image/decode`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * 在 RAM 和 Flash 极其有限的设备上解码图片是一项繁重的任务。这个接口专为 IoT 和嵌入式开发设计，将复杂的图像解码和缩放操作转移到云端，直接输出适用于单片机屏幕的二进制像素流。  ## 功能概述 此接口提供了灵活的云端图像预处理能力，帮助硬件开发者跳过繁琐的图像处理逻辑： - **直接推流渲染**：如果选择输出纯像素流（如 RGB565），单片机收到网络数据后无需解析文件头，可直接将其写入显存，实现极低内存占用的边下边播。 - **完美适配屏幕**：无需在设备端编写裁剪或补边代码。只需传入目标屏幕的物理分辨率，接口会自动完成等比缩放、居中补色或铺满裁剪，确保最终显示画面不变形。 - **精准内存分配**：在动态缩放图片的场景下，服务端会在 HTTP 响应头中提前注入 `X-Image-Width` 和 `X-Image-Height`，方便设备在读取真实的二进制数据前进行准确的内存分配。  ## 使用须知 - **请求格式**：无论是上传本地文件还是传递图片链接，请求体都必须使用 `multipart/form-data` 编码格式。 - **网络资源获取**：当您选择传递图片链接时，服务端会自动尝试获取该资源。请确保您提供的图片链接是公网直接可访问的，且不需要任何形式的登录鉴权。
     * 解码并缩放图片
     */
    async postImageDecode(requestParameters: PostImageDecodeRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.postImageDecodeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 当你需要在前端处理完图片（比如裁剪、加滤镜后），不通过传统表单，而是直接上传图片的场景，这个接口就派上用场了。  ## 功能概述 你只需要将图片的 Base64 编码字符串发送过来，我们就会把它解码、保存为图片文件，并返回一个可供访问的公开 URL。  ## 使用须知  > [!IMPORTANT] > **关于 `imageData` 格式** > 你发送的 `imageData` 字符串必须是完整的 Base64 Data URI 格式，它需要包含 MIME 类型信息，例如 `data:image/png;base64,iVBORw0KGgo...`。缺少 `data:image/...;base64,` 前缀将导致解码失败。
     * 通过Base64编码上传图片
     */
    async postImageFrombase64Raw(requestParameters: PostImageFrombase64OperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostImageFrombase64200Response>> {
        if (requestParameters['postImageFrombase64Request'] == null) {
            throw new runtime.RequiredError(
                'postImageFrombase64Request',
                'Required parameter "postImageFrombase64Request" was null or undefined when calling postImageFrombase64().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/image/frombase64`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostImageFrombase64RequestToJSON(requestParameters['postImageFrombase64Request']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostImageFrombase64200ResponseFromJSON(jsonValue));
    }

    /**
     * 当你需要在前端处理完图片（比如裁剪、加滤镜后），不通过传统表单，而是直接上传图片的场景，这个接口就派上用场了。  ## 功能概述 你只需要将图片的 Base64 编码字符串发送过来，我们就会把它解码、保存为图片文件，并返回一个可供访问的公开 URL。  ## 使用须知  > [!IMPORTANT] > **关于 `imageData` 格式** > 你发送的 `imageData` 字符串必须是完整的 Base64 Data URI 格式，它需要包含 MIME 类型信息，例如 `data:image/png;base64,iVBORw0KGgo...`。缺少 `data:image/...;base64,` 前缀将导致解码失败。
     * 通过Base64编码上传图片
     */
    async postImageFrombase64(requestParameters: PostImageFrombase64OperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostImageFrombase64200Response> {
        const response = await this.postImageFrombase64Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 除了使用QQ头像，你还可以通过上传自己的图片或提供图片URL来制作独一无二的摸摸头GIF。  ## 功能概述 此接口通过POST方法，支持两种方式生成GIF： 1.  **图片URL**：在表单中提供 `image_url` 字段。 2.  **上传图片**：在表单中上传 `file` 文件。  ## 使用须知 - **响应格式**：接口成功时直接返回 `image/gif` 格式的二进制数据。 - **参数优先级**：如果同时提供了 `image_url` 和上传的 `file` 文件，系统将 **优先使用 `image_url`**。 - **背景颜色**：同样支持 `bg_color` 表单字段来控制GIF背景。
     * 生成摸摸头GIF
     */
    async postImageMotouRaw(requestParameters: PostImageMotouRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['imageUrl'] != null) {
            formParams.append('image_url', requestParameters['imageUrl'] as any);
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }

        if (requestParameters['bgColor'] != null) {
            formParams.append('bg_color', requestParameters['bgColor'] as any);
        }


        let urlPath = `/image/motou`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * 除了使用QQ头像，你还可以通过上传自己的图片或提供图片URL来制作独一无二的摸摸头GIF。  ## 功能概述 此接口通过POST方法，支持两种方式生成GIF： 1.  **图片URL**：在表单中提供 `image_url` 字段。 2.  **上传图片**：在表单中上传 `file` 文件。  ## 使用须知 - **响应格式**：接口成功时直接返回 `image/gif` 格式的二进制数据。 - **参数优先级**：如果同时提供了 `image_url` 和上传的 `file` 文件，系统将 **优先使用 `image_url`**。 - **背景颜色**：同样支持 `bg_color` 表单字段来控制GIF背景。
     * 生成摸摸头GIF
     */
    async postImageMotou(requestParameters: PostImageMotouRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.postImageMotouRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 这是一个图片内容审核接口，自动识别图片中的违规内容并返回处理建议。  ## 功能概述 上传图片文件或提供图片URL，接口会自动分析图片内容，返回是否违规、风险等级和处理建议。适合对接到用户上传流程中，实现自动化内容审核。  ## 返回字段说明 - **is_nsfw**: 是否判定为违规内容，`true` 表示违规，`false` 表示正常 - **nsfw_score**: 违规内容置信度，0-1 之间，越高表示越可能违规 - **normal_score**: 正常内容置信度，0-1 之间，与 nsfw_score 互补 - **suggestion**: 处理建议   - `pass`: 内容正常，可以直接放行   - `review`: 存在风险，建议转人工复核   - `block`: 高风险内容，建议直接拦截 - **risk_level**: 风险等级   - `low`: 低风险   - `medium`: 中风险   - `high`: 高风险 - **label**: 内容标签，`nsfw` 或 `normal` - **confidence**: 模型对当前判断的整体置信度 - **inference_time_ms**: 模型推理耗时，单位毫秒
     * 图片敏感检测
     */
    async postImageNsfwRaw(requestParameters: PostImageNsfwRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostImageNsfw200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }

        if (requestParameters['url'] != null) {
            formParams.append('url', requestParameters['url'] as any);
        }


        let urlPath = `/image/nsfw`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostImageNsfw200ResponseFromJSON(jsonValue));
    }

    /**
     * 这是一个图片内容审核接口，自动识别图片中的违规内容并返回处理建议。  ## 功能概述 上传图片文件或提供图片URL，接口会自动分析图片内容，返回是否违规、风险等级和处理建议。适合对接到用户上传流程中，实现自动化内容审核。  ## 返回字段说明 - **is_nsfw**: 是否判定为违规内容，`true` 表示违规，`false` 表示正常 - **nsfw_score**: 违规内容置信度，0-1 之间，越高表示越可能违规 - **normal_score**: 正常内容置信度，0-1 之间，与 nsfw_score 互补 - **suggestion**: 处理建议   - `pass`: 内容正常，可以直接放行   - `review`: 存在风险，建议转人工复核   - `block`: 高风险内容，建议直接拦截 - **risk_level**: 风险等级   - `low`: 低风险   - `medium`: 中风险   - `high`: 高风险 - **label**: 内容标签，`nsfw` 或 `normal` - **confidence**: 模型对当前判断的整体置信度 - **inference_time_ms**: 模型推理耗时，单位毫秒
     * 图片敏感检测
     */
    async postImageNsfw(requestParameters: PostImageNsfwRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostImageNsfw200Response> {
        const response = await this.postImageNsfwRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 无论您是需要实现票据的自动化录入，还是在网页前端对图片上的文字进行坐标框选，这个高精度的 OCR 接口都能为您提供强大的基础能力。  ## 功能概述 > [!IMPORTANT] > 如果您只关心图片上写了什么（例如截图取字或内容安全审核），强烈建议将 `need_location` 设置为 `false`。这会大幅精简返回的 JSON 数据体积，提升网络传输与系统解析效率。  除了常规的图片转文字，这个接口还针对实际开发场景做了一些实用设计： - **前端文字高亮与结构化分析**：默认返回每一段文字的矩形坐标和四个顶点坐标。这非常适合使用 Canvas 在原图上画框高亮，或者在后端根据相对位置提取票据中的键值对信息。 - **复杂拍摄环境下的抗畸变**：针对手机拍摄导致的旋转或倾斜，可以开启 `enable_cls=true`。服务端在识别前会自动进行方向预校正，显著提升识别准确率。 - **灵活的输入与请求要求**：接口支持 `file`、`url` 或 `image_base64` 三种方式输入。请确保请求格式为 `multipart/form-data`，且图片链接在公网可直接访问。
     * 通用 OCR 文字识别
     */
    async postImageOcrRaw(requestParameters: PostImageOcrRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostImageOcr200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }

        if (requestParameters['url'] != null) {
            formParams.append('url', requestParameters['url'] as any);
        }

        if (requestParameters['imageBase64'] != null) {
            formParams.append('image_base64', requestParameters['imageBase64'] as any);
        }

        if (requestParameters['imageName'] != null) {
            formParams.append('image_name', requestParameters['imageName'] as any);
        }

        if (requestParameters['needLocation'] != null) {
            formParams.append('need_location', requestParameters['needLocation'] as any);
        }

        if (requestParameters['returnMarkdown'] != null) {
            formParams.append('return_markdown', requestParameters['returnMarkdown'] as any);
        }

        if (requestParameters['enableCls'] != null) {
            formParams.append('enable_cls', requestParameters['enableCls'] as any);
        }


        let urlPath = `/image/ocr`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostImageOcr200ResponseFromJSON(jsonValue));
    }

    /**
     * 无论您是需要实现票据的自动化录入，还是在网页前端对图片上的文字进行坐标框选，这个高精度的 OCR 接口都能为您提供强大的基础能力。  ## 功能概述 > [!IMPORTANT] > 如果您只关心图片上写了什么（例如截图取字或内容安全审核），强烈建议将 `need_location` 设置为 `false`。这会大幅精简返回的 JSON 数据体积，提升网络传输与系统解析效率。  除了常规的图片转文字，这个接口还针对实际开发场景做了一些实用设计： - **前端文字高亮与结构化分析**：默认返回每一段文字的矩形坐标和四个顶点坐标。这非常适合使用 Canvas 在原图上画框高亮，或者在后端根据相对位置提取票据中的键值对信息。 - **复杂拍摄环境下的抗畸变**：针对手机拍摄导致的旋转或倾斜，可以开启 `enable_cls=true`。服务端在识别前会自动进行方向预校正，显著提升识别准确率。 - **灵活的输入与请求要求**：接口支持 `file`、`url` 或 `image_base64` 三种方式输入。请确保请求格式为 `multipart/form-data`，且图片链接在公网可直接访问。
     * 通用 OCR 文字识别
     */
    async postImageOcr(requestParameters: PostImageOcrRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostImageOcr200Response> {
        const response = await this.postImageOcrRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 你们怎么不说话了？是不是都在偷偷玩Uapi，求求你们不要玩Uapi了  ## 使用须知 - **响应格式**：接口成功时直接返回 `image/png` 格式的二进制数据。 - **文字内容**：至少需要提供 `top_text`（上方文字）或 `bottom_text`（下方文字）之一。 - **梗图逻辑**：上方描述某个行为，下方通常以「们」开头表示劝阻，形成戏谑的对比效果。
     * 生成你们怎么不说话了表情包
     */
    async postImageSpeechlessRaw(requestParameters: PostImageSpeechlessOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        if (requestParameters['postImageSpeechlessRequest'] == null) {
            throw new runtime.RequiredError(
                'postImageSpeechlessRequest',
                'Required parameter "postImageSpeechlessRequest" was null or undefined when calling postImageSpeechless().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/image/speechless`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostImageSpeechlessRequestToJSON(requestParameters['postImageSpeechlessRequest']),
        }, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * 你们怎么不说话了？是不是都在偷偷玩Uapi，求求你们不要玩Uapi了  ## 使用须知 - **响应格式**：接口成功时直接返回 `image/png` 格式的二进制数据。 - **文字内容**：至少需要提供 `top_text`（上方文字）或 `bottom_text`（下方文字）之一。 - **梗图逻辑**：上方描述某个行为，下方通常以「们」开头表示劝阻，形成戏谑的对比效果。
     * 生成你们怎么不说话了表情包
     */
    async postImageSpeechless(requestParameters: PostImageSpeechlessOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.postImageSpeechlessRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 需要将灵活的 SVG 矢量图形转换为常见的光栅图像格式吗？这个接口可以帮你轻松实现。  ## 功能概述 上传一个 SVG 文件，并指定目标格式（如 PNG、JPEG 等），接口将返回转换后的图像。你还可以调整输出图像的尺寸和（对于JPEG）压缩质量，以满足不同场景的需求。
     * SVG转图片
     */
    async postImageSvgRaw(requestParameters: PostImageSvgRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        const queryParameters: any = {};

        if (requestParameters['format'] != null) {
            queryParameters['format'] = requestParameters['format'];
        }

        if (requestParameters['width'] != null) {
            queryParameters['width'] = requestParameters['width'];
        }

        if (requestParameters['height'] != null) {
            queryParameters['height'] = requestParameters['height'];
        }

        if (requestParameters['quality'] != null) {
            queryParameters['quality'] = requestParameters['quality'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }


        let urlPath = `/image/svg`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * 需要将灵活的 SVG 矢量图形转换为常见的光栅图像格式吗？这个接口可以帮你轻松实现。  ## 功能概述 上传一个 SVG 文件，并指定目标格式（如 PNG、JPEG 等），接口将返回转换后的图像。你还可以调整输出图像的尺寸和（对于JPEG）压缩质量，以满足不同场景的需求。
     * SVG转图片
     */
    async postImageSvg(requestParameters: PostImageSvgRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.postImageSvgRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetImageBingDailyResolutionEnum = {
    _4k: '4k',
    _1080: '1080'
} as const;
export type GetImageBingDailyResolutionEnum = typeof GetImageBingDailyResolutionEnum[keyof typeof GetImageBingDailyResolutionEnum];
/**
 * @export
 */
export const GetImageBingDailyFormatEnum = {
    Image: 'image',
    Json: 'json',
    Redirect: 'redirect'
} as const;
export type GetImageBingDailyFormatEnum = typeof GetImageBingDailyFormatEnum[keyof typeof GetImageBingDailyFormatEnum];
/**
 * @export
 */
export const GetImageBingDailyHistoryResolutionEnum = {
    _4k: '4k',
    _1080: '1080'
} as const;
export type GetImageBingDailyHistoryResolutionEnum = typeof GetImageBingDailyHistoryResolutionEnum[keyof typeof GetImageBingDailyHistoryResolutionEnum];
/**
 * @export
 */
export const GetImageMotouBgColorEnum = {
    White: 'white',
    Black: 'black',
    Transparent: 'transparent'
} as const;
export type GetImageMotouBgColorEnum = typeof GetImageMotouBgColorEnum[keyof typeof GetImageMotouBgColorEnum];
/**
 * @export
 */
export const GetImageQrcodeFormatEnum = {
    Image: 'image',
    Json: 'json',
    JsonUrl: 'json_url'
} as const;
export type GetImageQrcodeFormatEnum = typeof GetImageQrcodeFormatEnum[keyof typeof GetImageQrcodeFormatEnum];
/**
 * @export
 */
export const PostImageCompressLevelEnum = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4,
    NUMBER_5: 5
} as const;
export type PostImageCompressLevelEnum = typeof PostImageCompressLevelEnum[keyof typeof PostImageCompressLevelEnum];
/**
 * @export
 */
export const PostImageCompressFormatEnum = {
    Png: 'png',
    Jpeg: 'jpeg'
} as const;
export type PostImageCompressFormatEnum = typeof PostImageCompressFormatEnum[keyof typeof PostImageCompressFormatEnum];
/**
 * @export
 */
export const PostImageDecodeFormatEnum = {
    Bmp: 'bmp',
    Rgb565: 'rgb565',
    Rgb888: 'rgb888'
} as const;
export type PostImageDecodeFormatEnum = typeof PostImageDecodeFormatEnum[keyof typeof PostImageDecodeFormatEnum];
/**
 * @export
 */
export const PostImageDecodeColorModeEnum = {
    Rgb565: 'RGB565',
    Rgb888: 'RGB888'
} as const;
export type PostImageDecodeColorModeEnum = typeof PostImageDecodeColorModeEnum[keyof typeof PostImageDecodeColorModeEnum];
/**
 * @export
 */
export const PostImageDecodeFitEnum = {
    Contain: 'contain',
    Cover: 'cover',
    Fill: 'fill'
} as const;
export type PostImageDecodeFitEnum = typeof PostImageDecodeFitEnum[keyof typeof PostImageDecodeFitEnum];
/**
 * @export
 */
export const PostImageMotouBgColorEnum = {
    White: 'white',
    Black: 'black',
    Transparent: 'transparent'
} as const;
export type PostImageMotouBgColorEnum = typeof PostImageMotouBgColorEnum[keyof typeof PostImageMotouBgColorEnum];
/**
 * @export
 */
export const PostImageOcrNeedLocationEnum = {
    True: 'true',
    False: 'false'
} as const;
export type PostImageOcrNeedLocationEnum = typeof PostImageOcrNeedLocationEnum[keyof typeof PostImageOcrNeedLocationEnum];
/**
 * @export
 */
export const PostImageOcrReturnMarkdownEnum = {
    True: 'true',
    False: 'false'
} as const;
export type PostImageOcrReturnMarkdownEnum = typeof PostImageOcrReturnMarkdownEnum[keyof typeof PostImageOcrReturnMarkdownEnum];
/**
 * @export
 */
export const PostImageOcrEnableClsEnum = {
    True: 'true',
    False: 'false'
} as const;
export type PostImageOcrEnableClsEnum = typeof PostImageOcrEnableClsEnum[keyof typeof PostImageOcrEnableClsEnum];
/**
 * @export
 */
export const PostImageSvgFormatEnum = {
    Png: 'png',
    Jpeg: 'jpeg',
    Jpg: 'jpg',
    Gif: 'gif',
    Tiff: 'tiff',
    Bmp: 'bmp'
} as const;
export type PostImageSvgFormatEnum = typeof PostImageSvgFormatEnum[keyof typeof PostImageSvgFormatEnum];
