/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetTextMd5200Response,
  GetTextMd5400Response,
  PostTextAesDecrypt200Response,
  PostTextAesDecrypt400Response,
  PostTextAesDecrypt500Response,
  PostTextAesDecryptRequest,
  PostTextAesEncrypt200Response,
  PostTextAesEncrypt400Response,
  PostTextAesEncrypt500Response,
  PostTextAesEncryptRequest,
  PostTextAnalyze200Response,
  PostTextAnalyze400Response,
  PostTextAnalyzeRequest,
  PostTextBase64Decode200Response,
  PostTextBase64Decode400Response,
  PostTextBase64DecodeRequest,
  PostTextBase64Encode200Response,
  PostTextBase64Encode400Response,
  PostTextBase64EncodeRequest,
  PostTextMd5400Response,
  PostTextMd5Request,
  PostTextMd5Verify200Response,
  PostTextMd5Verify400Response,
  PostTextMd5VerifyRequest,
} from '../models/index';
import {
    GetTextMd5200ResponseFromJSON,
    GetTextMd5200ResponseToJSON,
    GetTextMd5400ResponseFromJSON,
    GetTextMd5400ResponseToJSON,
    PostTextAesDecrypt200ResponseFromJSON,
    PostTextAesDecrypt200ResponseToJSON,
    PostTextAesDecrypt400ResponseFromJSON,
    PostTextAesDecrypt400ResponseToJSON,
    PostTextAesDecrypt500ResponseFromJSON,
    PostTextAesDecrypt500ResponseToJSON,
    PostTextAesDecryptRequestFromJSON,
    PostTextAesDecryptRequestToJSON,
    PostTextAesEncrypt200ResponseFromJSON,
    PostTextAesEncrypt200ResponseToJSON,
    PostTextAesEncrypt400ResponseFromJSON,
    PostTextAesEncrypt400ResponseToJSON,
    PostTextAesEncrypt500ResponseFromJSON,
    PostTextAesEncrypt500ResponseToJSON,
    PostTextAesEncryptRequestFromJSON,
    PostTextAesEncryptRequestToJSON,
    PostTextAnalyze200ResponseFromJSON,
    PostTextAnalyze200ResponseToJSON,
    PostTextAnalyze400ResponseFromJSON,
    PostTextAnalyze400ResponseToJSON,
    PostTextAnalyzeRequestFromJSON,
    PostTextAnalyzeRequestToJSON,
    PostTextBase64Decode200ResponseFromJSON,
    PostTextBase64Decode200ResponseToJSON,
    PostTextBase64Decode400ResponseFromJSON,
    PostTextBase64Decode400ResponseToJSON,
    PostTextBase64DecodeRequestFromJSON,
    PostTextBase64DecodeRequestToJSON,
    PostTextBase64Encode200ResponseFromJSON,
    PostTextBase64Encode200ResponseToJSON,
    PostTextBase64Encode400ResponseFromJSON,
    PostTextBase64Encode400ResponseToJSON,
    PostTextBase64EncodeRequestFromJSON,
    PostTextBase64EncodeRequestToJSON,
    PostTextMd5400ResponseFromJSON,
    PostTextMd5400ResponseToJSON,
    PostTextMd5RequestFromJSON,
    PostTextMd5RequestToJSON,
    PostTextMd5Verify200ResponseFromJSON,
    PostTextMd5Verify200ResponseToJSON,
    PostTextMd5Verify400ResponseFromJSON,
    PostTextMd5Verify400ResponseToJSON,
    PostTextMd5VerifyRequestFromJSON,
    PostTextMd5VerifyRequestToJSON,
} from '../models/index';

export interface GetTextMd5Request {
    text: string;
}

export interface PostTextAesDecryptOperationRequest {
    postTextAesDecryptRequest: PostTextAesDecryptRequest;
}

export interface PostTextAesEncryptOperationRequest {
    postTextAesEncryptRequest: PostTextAesEncryptRequest;
}

export interface PostTextAnalyzeOperationRequest {
    postTextAnalyzeRequest: PostTextAnalyzeRequest;
}

export interface PostTextBase64DecodeOperationRequest {
    postTextBase64DecodeRequest: PostTextBase64DecodeRequest;
}

export interface PostTextBase64EncodeOperationRequest {
    postTextBase64EncodeRequest: PostTextBase64EncodeRequest;
}

export interface PostTextMd5OperationRequest {
    postTextMd5Request: PostTextMd5Request;
}

export interface PostTextMd5VerifyOperationRequest {
    postTextMd5VerifyRequest: PostTextMd5VerifyRequest;
}

/**
 * 
 */
export class TextApi extends runtime.BaseAPI {

    /**
     * 一个快速计算文本 MD5 哈希值的工具，适用于短文本且不关心参数暴露的场景。  ## 功能概述 通过GET请求的查询参数传入文本，返回其32位小写的MD5哈希值。  > [!NOTE] > 对于较长或敏感的文本，我们推荐使用本接口的 POST 版本，以避免URL长度限制和参数暴露问题。
     * 计算文本的MD5哈希值(GET)
     */
    async getTextMd5Raw(requestParameters: GetTextMd5Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetTextMd5200Response>> {
        if (requestParameters['text'] == null) {
            throw new runtime.RequiredError(
                'text',
                'Required parameter "text" was null or undefined when calling getTextMd5().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['text'] != null) {
            queryParameters['text'] = requestParameters['text'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/text/md5`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetTextMd5200ResponseFromJSON(jsonValue));
    }

    /**
     * 一个快速计算文本 MD5 哈希值的工具，适用于短文本且不关心参数暴露的场景。  ## 功能概述 通过GET请求的查询参数传入文本，返回其32位小写的MD5哈希值。  > [!NOTE] > 对于较长或敏感的文本，我们推荐使用本接口的 POST 版本，以避免URL长度限制和参数暴露问题。
     * 计算文本的MD5哈希值(GET)
     */
    async getTextMd5(requestParameters: GetTextMd5Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetTextMd5200Response> {
        const response = await this.getTextMd5Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 收到了用AES加密的密文？把它、密钥和随机数（nonce）交给我们，就能还原出原始内容。  ## 功能概述 这是一个标准的AES解密接口。你需要提供经过Base64编码的密文、加密时使用的密钥和nonce（随机数，通常为16字节字符串）。  > [!IMPORTANT] > **关于密钥 `key`** > 我们支持 AES-128, AES-192, 和 AES-256。请确保你提供的密钥 `key` 的长度（字节数）正好是 **16**、**24** 或 **32**，以分别对应这三种加密强度。 >  > **关于随机数 `nonce`** > 通常为16字节字符串，需与加密时一致。
     * 使用AES算法解密文本
     */
    async postTextAesDecryptRaw(requestParameters: PostTextAesDecryptOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostTextAesDecrypt200Response>> {
        if (requestParameters['postTextAesDecryptRequest'] == null) {
            throw new runtime.RequiredError(
                'postTextAesDecryptRequest',
                'Required parameter "postTextAesDecryptRequest" was null or undefined when calling postTextAesDecrypt().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/text/aes/decrypt`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostTextAesDecryptRequestToJSON(requestParameters['postTextAesDecryptRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostTextAesDecrypt200ResponseFromJSON(jsonValue));
    }

    /**
     * 收到了用AES加密的密文？把它、密钥和随机数（nonce）交给我们，就能还原出原始内容。  ## 功能概述 这是一个标准的AES解密接口。你需要提供经过Base64编码的密文、加密时使用的密钥和nonce（随机数，通常为16字节字符串）。  > [!IMPORTANT] > **关于密钥 `key`** > 我们支持 AES-128, AES-192, 和 AES-256。请确保你提供的密钥 `key` 的长度（字节数）正好是 **16**、**24** 或 **32**，以分别对应这三种加密强度。 >  > **关于随机数 `nonce`** > 通常为16字节字符串，需与加密时一致。
     * 使用AES算法解密文本
     */
    async postTextAesDecrypt(requestParameters: PostTextAesDecryptOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostTextAesDecrypt200Response> {
        const response = await this.postTextAesDecryptRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 需要安全地传输或存储一些文本信息？AES加密是一个可靠的选择。  ## 功能概述 这是一个标准的AES加密接口。你提供需要加密的明文和密钥，我们返回经过Base64编码的密文。  > [!IMPORTANT] > **关于密钥 `key`** > 我们支持 AES-128, AES-192, 和 AES-256。请确保你提供的密钥 `key` 的长度（字节数）正好是 **16**、**24** 或 **32**，以分别对应这三种加密强度。
     * 使用AES算法加密文本
     */
    async postTextAesEncryptRaw(requestParameters: PostTextAesEncryptOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostTextAesEncrypt200Response>> {
        if (requestParameters['postTextAesEncryptRequest'] == null) {
            throw new runtime.RequiredError(
                'postTextAesEncryptRequest',
                'Required parameter "postTextAesEncryptRequest" was null or undefined when calling postTextAesEncrypt().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/text/aes/encrypt`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostTextAesEncryptRequestToJSON(requestParameters['postTextAesEncryptRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostTextAesEncrypt200ResponseFromJSON(jsonValue));
    }

    /**
     * 需要安全地传输或存储一些文本信息？AES加密是一个可靠的选择。  ## 功能概述 这是一个标准的AES加密接口。你提供需要加密的明文和密钥，我们返回经过Base64编码的密文。  > [!IMPORTANT] > **关于密钥 `key`** > 我们支持 AES-128, AES-192, 和 AES-256。请确保你提供的密钥 `key` 的长度（字节数）正好是 **16**、**24** 或 **32**，以分别对应这三种加密强度。
     * 使用AES算法加密文本
     */
    async postTextAesEncrypt(requestParameters: PostTextAesEncryptOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostTextAesEncrypt200Response> {
        const response = await this.postTextAesEncryptRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 想知道一篇文章有多少字、多少个词、或者多少行？这个接口可以帮你快速统计。  ## 功能概述 你提供一段文本，我们会从多个维度进行分析，并返回其字符数、词数、句子数、段落数和行数。这对于文本编辑、内容管理等场景非常有用。
     * 多维度分析文本内容
     */
    async postTextAnalyzeRaw(requestParameters: PostTextAnalyzeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostTextAnalyze200Response>> {
        if (requestParameters['postTextAnalyzeRequest'] == null) {
            throw new runtime.RequiredError(
                'postTextAnalyzeRequest',
                'Required parameter "postTextAnalyzeRequest" was null or undefined when calling postTextAnalyze().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/text/analyze`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostTextAnalyzeRequestToJSON(requestParameters['postTextAnalyzeRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostTextAnalyze200ResponseFromJSON(jsonValue));
    }

    /**
     * 想知道一篇文章有多少字、多少个词、或者多少行？这个接口可以帮你快速统计。  ## 功能概述 你提供一段文本，我们会从多个维度进行分析，并返回其字符数、词数、句子数、段落数和行数。这对于文本编辑、内容管理等场景非常有用。
     * 多维度分析文本内容
     */
    async postTextAnalyze(requestParameters: PostTextAnalyzeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostTextAnalyze200Response> {
        const response = await this.postTextAnalyzeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 这是一个简单实用的 Base64 解码工具。  ## 功能概述 你提供一个 Base64 编码的字符串，我们帮你解码成原始的 UTF-8 文本。
     * 解码Base64编码的文本
     */
    async postTextBase64DecodeRaw(requestParameters: PostTextBase64DecodeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostTextBase64Decode200Response>> {
        if (requestParameters['postTextBase64DecodeRequest'] == null) {
            throw new runtime.RequiredError(
                'postTextBase64DecodeRequest',
                'Required parameter "postTextBase64DecodeRequest" was null or undefined when calling postTextBase64Decode().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/text/base64/decode`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostTextBase64DecodeRequestToJSON(requestParameters['postTextBase64DecodeRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostTextBase64Decode200ResponseFromJSON(jsonValue));
    }

    /**
     * 这是一个简单实用的 Base64 解码工具。  ## 功能概述 你提供一个 Base64 编码的字符串，我们帮你解码成原始的 UTF-8 文本。
     * 解码Base64编码的文本
     */
    async postTextBase64Decode(requestParameters: PostTextBase64DecodeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostTextBase64Decode200Response> {
        const response = await this.postTextBase64DecodeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 这是一个简单实用的 Base64 编码工具。  ## 功能概述 你提供一段原始文本，我们帮你转换成 Base64 编码的字符串。
     * 将文本进行Base64编码
     */
    async postTextBase64EncodeRaw(requestParameters: PostTextBase64EncodeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostTextBase64Encode200Response>> {
        if (requestParameters['postTextBase64EncodeRequest'] == null) {
            throw new runtime.RequiredError(
                'postTextBase64EncodeRequest',
                'Required parameter "postTextBase64EncodeRequest" was null or undefined when calling postTextBase64Encode().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/text/base64/encode`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostTextBase64EncodeRequestToJSON(requestParameters['postTextBase64EncodeRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostTextBase64Encode200ResponseFromJSON(jsonValue));
    }

    /**
     * 这是一个简单实用的 Base64 编码工具。  ## 功能概述 你提供一段原始文本，我们帮你转换成 Base64 编码的字符串。
     * 将文本进行Base64编码
     */
    async postTextBase64Encode(requestParameters: PostTextBase64EncodeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostTextBase64Encode200Response> {
        const response = await this.postTextBase64EncodeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 一个用于计算文本 MD5 哈希值的标准工具，推荐使用此版本。  ## 功能概述 通过POST请求的表单体传入文本，返回其32位小写的MD5哈希值。相比GET版本，此方法更适合处理较长或包含敏感信息的文本。
     * 计算文本的MD5哈希值 (POST)
     */
    async postTextMd5Raw(requestParameters: PostTextMd5OperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetTextMd5200Response>> {
        if (requestParameters['postTextMd5Request'] == null) {
            throw new runtime.RequiredError(
                'postTextMd5Request',
                'Required parameter "postTextMd5Request" was null or undefined when calling postTextMd5().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/text/md5`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostTextMd5RequestToJSON(requestParameters['postTextMd5Request']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetTextMd5200ResponseFromJSON(jsonValue));
    }

    /**
     * 一个用于计算文本 MD5 哈希值的标准工具，推荐使用此版本。  ## 功能概述 通过POST请求的表单体传入文本，返回其32位小写的MD5哈希值。相比GET版本，此方法更适合处理较长或包含敏感信息的文本。
     * 计算文本的MD5哈希值 (POST)
     */
    async postTextMd5(requestParameters: PostTextMd5OperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetTextMd5200Response> {
        const response = await this.postTextMd5Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 下载了一个文件，想确认它在传输过程中有没有损坏？校验MD5值是最常用的方法。  ## 功能概述 你提供原始文本和一个MD5哈希值，我们帮你计算文本的哈希，并与你提供的哈希进行比对，告诉你它们是否匹配。这在文件完整性校验等场景下非常有用。
     * 校验MD5哈希值
     */
    async postTextMd5VerifyRaw(requestParameters: PostTextMd5VerifyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostTextMd5Verify200Response>> {
        if (requestParameters['postTextMd5VerifyRequest'] == null) {
            throw new runtime.RequiredError(
                'postTextMd5VerifyRequest',
                'Required parameter "postTextMd5VerifyRequest" was null or undefined when calling postTextMd5Verify().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/text/md5/verify`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostTextMd5VerifyRequestToJSON(requestParameters['postTextMd5VerifyRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostTextMd5Verify200ResponseFromJSON(jsonValue));
    }

    /**
     * 下载了一个文件，想确认它在传输过程中有没有损坏？校验MD5值是最常用的方法。  ## 功能概述 你提供原始文本和一个MD5哈希值，我们帮你计算文本的哈希，并与你提供的哈希进行比对，告诉你它们是否匹配。这在文件完整性校验等场景下非常有用。
     * 校验MD5哈希值
     */
    async postTextMd5Verify(requestParameters: PostTextMd5VerifyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostTextMd5Verify200Response> {
        const response = await this.postTextMd5VerifyRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
