/* tslint:disable */
/* eslint-disable */
/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetAiTranslateLanguages200Response,
  PostAiTranslate200Response,
  PostAiTranslate400Response,
  PostAiTranslate401Response,
  PostAiTranslate429Response,
  PostAiTranslate500Response,
  PostAiTranslateRequest,
  PostTranslateStream400Response,
  PostTranslateStream500Response,
  PostTranslateStreamRequest,
  PostTranslateText200Response,
  PostTranslateText400Response,
  PostTranslateText500Response,
  PostTranslateTextRequest,
} from '../models/index';
import {
    GetAiTranslateLanguages200ResponseFromJSON,
    GetAiTranslateLanguages200ResponseToJSON,
    PostAiTranslate200ResponseFromJSON,
    PostAiTranslate200ResponseToJSON,
    PostAiTranslate400ResponseFromJSON,
    PostAiTranslate400ResponseToJSON,
    PostAiTranslate401ResponseFromJSON,
    PostAiTranslate401ResponseToJSON,
    PostAiTranslate429ResponseFromJSON,
    PostAiTranslate429ResponseToJSON,
    PostAiTranslate500ResponseFromJSON,
    PostAiTranslate500ResponseToJSON,
    PostAiTranslateRequestFromJSON,
    PostAiTranslateRequestToJSON,
    PostTranslateStream400ResponseFromJSON,
    PostTranslateStream400ResponseToJSON,
    PostTranslateStream500ResponseFromJSON,
    PostTranslateStream500ResponseToJSON,
    PostTranslateStreamRequestFromJSON,
    PostTranslateStreamRequestToJSON,
    PostTranslateText200ResponseFromJSON,
    PostTranslateText200ResponseToJSON,
    PostTranslateText400ResponseFromJSON,
    PostTranslateText400ResponseToJSON,
    PostTranslateText500ResponseFromJSON,
    PostTranslateText500ResponseToJSON,
    PostTranslateTextRequestFromJSON,
    PostTranslateTextRequestToJSON,
} from '../models/index';

export interface PostAiTranslateOperationRequest {
    targetLang: PostAiTranslateOperationTargetLangEnum;
    postAiTranslateRequest: PostAiTranslateRequest;
}

export interface PostTranslateStreamOperationRequest {
    postTranslateStreamRequest: PostTranslateStreamRequest;
}

export interface PostTranslateTextOperationRequest {
    toLang: PostTranslateTextOperationToLangEnum;
    postTranslateTextRequest: PostTranslateTextRequest;
}

/**
 * 
 */
export class TranslateApi extends runtime.BaseAPI {

    /**
     * Creates request options for getAiTranslateLanguages without sending the request
     */
    async getAiTranslateLanguagesRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/ai/translate/languages`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 获取AI智能翻译服务支持的完整语言列表、翻译风格选项、上下文场景选项以及性能指标信息。
     * AI翻译配置
     */
    async getAiTranslateLanguagesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetAiTranslateLanguages200Response>> {
        const requestOptions = await this.getAiTranslateLanguagesRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetAiTranslateLanguages200ResponseFromJSON(jsonValue));
    }

    /**
     * 获取AI智能翻译服务支持的完整语言列表、翻译风格选项、上下文场景选项以及性能指标信息。
     * AI翻译配置
     */
    async getAiTranslateLanguages(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetAiTranslateLanguages200Response> {
        const response = await this.getAiTranslateLanguagesRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postAiTranslate without sending the request
     */
    async postAiTranslateRequestOpts(requestParameters: PostAiTranslateOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['targetLang'] == null) {
            throw new runtime.RequiredError(
                'targetLang',
                'Required parameter "targetLang" was null or undefined when calling postAiTranslate().'
            );
        }

        if (requestParameters['postAiTranslateRequest'] == null) {
            throw new runtime.RequiredError(
                'postAiTranslateRequest',
                'Required parameter "postAiTranslateRequest" was null or undefined when calling postAiTranslate().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['targetLang'] != null) {
            queryParameters['target_lang'] = requestParameters['targetLang'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/ai/translate`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostAiTranslateRequestToJSON(requestParameters['postAiTranslateRequest']),
        };
    }

    /**
     * 这是一个商业级的AI智能翻译服务，采用最新的神经网络翻译技术和大语言模型，提供远超传统机器翻译的质量。  ## 功能概述  - **单文本翻译**: 专注处理单条文本翻译，适合需要高质量译文的业务场景。 - **多风格适配**: 提供随意口语化、专业商务、学术正式、文学艺术四种翻译风格，能够根据不同场景需求调整翻译的语言风格和表达方式。 - **上下文感知**: 支持通用、商务、技术、医疗、法律、市场营销、娱乐、教育、新闻等九种专业领域的上下文翻译，确保术语准确性和表达地道性。 - **格式保留**: 智能识别并保持原文的格式结构，包括换行、缩进、特殊符号等，确保翻译后的文本保持良好的可读性。  ## 支持的语言  我们支持超过100种语言的互译，详见下方参数列表。
     * AI智能翻译
     */
    async postAiTranslateRaw(requestParameters: PostAiTranslateOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostAiTranslate200Response>> {
        const requestOptions = await this.postAiTranslateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostAiTranslate200ResponseFromJSON(jsonValue));
    }

    /**
     * 这是一个商业级的AI智能翻译服务，采用最新的神经网络翻译技术和大语言模型，提供远超传统机器翻译的质量。  ## 功能概述  - **单文本翻译**: 专注处理单条文本翻译，适合需要高质量译文的业务场景。 - **多风格适配**: 提供随意口语化、专业商务、学术正式、文学艺术四种翻译风格，能够根据不同场景需求调整翻译的语言风格和表达方式。 - **上下文感知**: 支持通用、商务、技术、医疗、法律、市场营销、娱乐、教育、新闻等九种专业领域的上下文翻译，确保术语准确性和表达地道性。 - **格式保留**: 智能识别并保持原文的格式结构，包括换行、缩进、特殊符号等，确保翻译后的文本保持良好的可读性。  ## 支持的语言  我们支持超过100种语言的互译，详见下方参数列表。
     * AI智能翻译
     */
    async postAiTranslate(requestParameters: PostAiTranslateOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostAiTranslate200Response> {
        const response = await this.postAiTranslateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postTranslateStream without sending the request
     */
    async postTranslateStreamRequestOpts(requestParameters: PostTranslateStreamOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['postTranslateStreamRequest'] == null) {
            throw new runtime.RequiredError(
                'postTranslateStreamRequest',
                'Required parameter "postTranslateStreamRequest" was null or undefined when calling postTranslateStream().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/translate/stream`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostTranslateStreamRequestToJSON(requestParameters['postTranslateStreamRequest']),
        };
    }

    /**
     * 想让翻译结果像打字机一样逐字显示出来？这个流式翻译接口能实现这种效果。  ## 功能概述 不同于传统翻译API一次性返回完整结果，这个接口会实时地、一个字一个字地把翻译内容推给你（就像ChatGPT回复消息那样），非常适合用在聊天应用、直播字幕等需要即时反馈的场景。  ## 它能做什么 - **中英互译**：支持中文和英文之间的双向翻译 - **自动识别**：不确定源语言？设置为 `auto` 让我们自动检测 - **逐字返回**：翻译结果会像打字机一样逐字流式返回，用户体验更流畅 - **音频朗读**：部分翻译结果会附带音频链接，方便朗读  ## 支持的语言 目前专注于中英互译，支持以下选项： - `中文`（简体/繁体） - `英文` - `auto`（自动检测）
     * 流式翻译（中英互译）
     */
    async postTranslateStreamRaw(requestParameters: PostTranslateStreamOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.postTranslateStreamRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * 想让翻译结果像打字机一样逐字显示出来？这个流式翻译接口能实现这种效果。  ## 功能概述 不同于传统翻译API一次性返回完整结果，这个接口会实时地、一个字一个字地把翻译内容推给你（就像ChatGPT回复消息那样），非常适合用在聊天应用、直播字幕等需要即时反馈的场景。  ## 它能做什么 - **中英互译**：支持中文和英文之间的双向翻译 - **自动识别**：不确定源语言？设置为 `auto` 让我们自动检测 - **逐字返回**：翻译结果会像打字机一样逐字流式返回，用户体验更流畅 - **音频朗读**：部分翻译结果会附带音频链接，方便朗读  ## 支持的语言 目前专注于中英互译，支持以下选项： - `中文`（简体/繁体） - `英文` - `auto`（自动检测）
     * 流式翻译（中英互译）
     */
    async postTranslateStream(requestParameters: PostTranslateStreamOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.postTranslateStreamRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postTranslateText without sending the request
     */
    async postTranslateTextRequestOpts(requestParameters: PostTranslateTextOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['toLang'] == null) {
            throw new runtime.RequiredError(
                'toLang',
                'Required parameter "toLang" was null or undefined when calling postTranslateText().'
            );
        }

        if (requestParameters['postTranslateTextRequest'] == null) {
            throw new runtime.RequiredError(
                'postTranslateTextRequest',
                'Required parameter "postTranslateTextRequest" was null or undefined when calling postTranslateText().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['toLang'] != null) {
            queryParameters['to_lang'] = requestParameters['toLang'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/translate/text`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostTranslateTextRequestToJSON(requestParameters['postTranslateTextRequest']),
        };
    }

    /**
     * 需要跨越语言的鸿沟进行交流？这个翻译接口是你可靠的\'同声传译\'。  ## 功能概述 你可以将一段源语言文本（我们能自动检测源语言）翻译成你指定的任何目标语言。无论是中译英、日译法，都不在话下。  ## 支持的语言 我们支持超过100种语言的互译，包括但不限于：中文（简体/繁体）、英语、日语、韩语、法语、德语、西班牙语、俄语、阿拉伯语等主流语言，以及各种小语种。详见下方参数列表。
     * 翻译
     */
    async postTranslateTextRaw(requestParameters: PostTranslateTextOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostTranslateText200Response>> {
        const requestOptions = await this.postTranslateTextRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostTranslateText200ResponseFromJSON(jsonValue));
    }

    /**
     * 需要跨越语言的鸿沟进行交流？这个翻译接口是你可靠的\'同声传译\'。  ## 功能概述 你可以将一段源语言文本（我们能自动检测源语言）翻译成你指定的任何目标语言。无论是中译英、日译法，都不在话下。  ## 支持的语言 我们支持超过100种语言的互译，包括但不限于：中文（简体/繁体）、英语、日语、韩语、法语、德语、西班牙语、俄语、阿拉伯语等主流语言，以及各种小语种。详见下方参数列表。
     * 翻译
     */
    async postTranslateText(requestParameters: PostTranslateTextOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostTranslateText200Response> {
        const response = await this.postTranslateTextRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const PostAiTranslateOperationTargetLangEnum = {
    Sq: 'sq',
    Ga: 'ga',
    Et: 'et',
    Ar: 'ar',
    Am: 'am',
    Az: 'az',
    Be: 'be',
    Bg: 'bg',
    Eu: 'eu',
    Is: 'is',
    Pl: 'pl',
    BsLatn: 'bs-Latn',
    Fa: 'fa',
    Da: 'da',
    De: 'de',
    Ru: 'ru',
    Fr: 'fr',
    Tl: 'tl',
    Fi: 'fi',
    Fy: 'fy',
    Km: 'km',
    Ka: 'ka',
    Gu: 'gu',
    Ht: 'ht',
    Ko: 'ko',
    Ha: 'ha',
    Kk: 'kk',
    Nl: 'nl',
    Gl: 'gl',
    Ca: 'ca',
    Cs: 'cs',
    Ky: 'ky',
    Kn: 'kn',
    Tlh: 'tlh',
    Hr: 'hr',
    Otq: 'otq',
    Co: 'co',
    Ku: 'ku',
    La: 'la',
    Lo: 'lo',
    Lv: 'lv',
    Lt: 'lt',
    Ro: 'ro',
    Lb: 'lb',
    Mg: 'mg',
    Mt: 'mt',
    Mr: 'mr',
    Ms: 'ms',
    Ml: 'ml',
    Mi: 'mi',
    Mk: 'mk',
    Mn: 'mn',
    Bn: 'bn',
    My: 'my',
    Mww: 'mww',
    Hmn: 'hmn',
    Xh: 'xh',
    Zu: 'zu',
    Ne: 'ne',
    No: 'no',
    Pa: 'pa',
    Ps: 'ps',
    Pt: 'pt',
    Ny: 'ny',
    Ja: 'ja',
    Sv: 'sv',
    SrLatn: 'sr-Latn',
    SrCyrl: 'sr-Cyrl',
    St: 'st',
    Sm: 'sm',
    Si: 'si',
    Eo: 'eo',
    Sk: 'sk',
    Sl: 'sl',
    Sw: 'sw',
    Gd: 'gd',
    So: 'so',
    Ceb: 'ceb',
    Te: 'te',
    Ta: 'ta',
    Th: 'th',
    Tg: 'tg',
    Tr: 'tr',
    Cy: 'cy',
    ZhLzh: 'zh-lzh',
    Ur: 'ur',
    Uk: 'uk',
    Uz: 'uz',
    Haw: 'haw',
    Es: 'es',
    He: 'he',
    El: 'el',
    Sd: 'sd',
    Hu: 'hu',
    Sn: 'sn',
    Hy: 'hy',
    Ig: 'ig',
    It: 'it',
    Yi: 'yi',
    Hi: 'hi',
    Id: 'id',
    En: 'en',
    Su: 'su',
    Jw: 'jw',
    Yua: 'yua',
    Yo: 'yo',
    Vi: 'vi',
    Zh: 'zh',
    ZhTw: 'zh-TW'
} as const;
export type PostAiTranslateOperationTargetLangEnum = typeof PostAiTranslateOperationTargetLangEnum[keyof typeof PostAiTranslateOperationTargetLangEnum];
/**
 * @export
 */
export const PostTranslateTextOperationToLangEnum = {
    Sq: 'sq',
    Ga: 'ga',
    Et: 'et',
    Ar: 'ar',
    Am: 'am',
    Az: 'az',
    Be: 'be',
    Bg: 'bg',
    Eu: 'eu',
    Is: 'is',
    Pl: 'pl',
    BsLatn: 'bs-Latn',
    Fa: 'fa',
    Da: 'da',
    De: 'de',
    Ru: 'ru',
    Fr: 'fr',
    Tl: 'tl',
    Fi: 'fi',
    Fy: 'fy',
    Km: 'km',
    Ka: 'ka',
    Gu: 'gu',
    Ht: 'ht',
    Ko: 'ko',
    Ha: 'ha',
    Kk: 'kk',
    Nl: 'nl',
    Gl: 'gl',
    Ca: 'ca',
    Cs: 'cs',
    Ky: 'ky',
    Kn: 'kn',
    Tlh: 'tlh',
    Hr: 'hr',
    Otq: 'otq',
    Co: 'co',
    Ku: 'ku',
    La: 'la',
    Lo: 'lo',
    Lv: 'lv',
    Lt: 'lt',
    Ro: 'ro',
    Lb: 'lb',
    Mg: 'mg',
    Mt: 'mt',
    Mr: 'mr',
    Ms: 'ms',
    Ml: 'ml',
    Mi: 'mi',
    Mk: 'mk',
    Mn: 'mn',
    Bn: 'bn',
    My: 'my',
    Mww: 'mww',
    Hmn: 'hmn',
    Xh: 'xh',
    Zu: 'zu',
    Ne: 'ne',
    No: 'no',
    Pa: 'pa',
    Ps: 'ps',
    Pt: 'pt',
    Ny: 'ny',
    Ja: 'ja',
    Sv: 'sv',
    SrLatn: 'sr-Latn',
    SrCyrl: 'sr-Cyrl',
    St: 'st',
    Sm: 'sm',
    Si: 'si',
    Eo: 'eo',
    Sk: 'sk',
    Sl: 'sl',
    Sw: 'sw',
    Gd: 'gd',
    So: 'so',
    Ceb: 'ceb',
    Te: 'te',
    Ta: 'ta',
    Th: 'th',
    Tg: 'tg',
    Tr: 'tr',
    Cy: 'cy',
    ZhLzh: 'zh-lzh',
    Ur: 'ur',
    Uk: 'uk',
    Uz: 'uz',
    Haw: 'haw',
    Es: 'es',
    He: 'he',
    El: 'el',
    Sd: 'sd',
    Hu: 'hu',
    Sn: 'sn',
    Hy: 'hy',
    Ig: 'ig',
    It: 'it',
    Yi: 'yi',
    Hi: 'hi',
    Id: 'id',
    En: 'en',
    Su: 'su',
    Jw: 'jw',
    Yua: 'yua',
    Yo: 'yo',
    Vi: 'vi',
    Zh: 'zh',
    ZhTw: 'zh-TW'
} as const;
export type PostTranslateTextOperationToLangEnum = typeof PostTranslateTextOperationToLangEnum[keyof typeof PostTranslateTextOperationToLangEnum];
